"use client";
import type {AdminAlert,AdminDecision,AdminOperationEvent,AdminOverride,AdminRole,AdminUser,AuditLogEntry,JoinRequestReview,PlatformPolicyVersion,PlatformSetting,SupportAssignment} from "./admin-types";
import {adminAlertsMock,adminOperationsMock,adminRolesMock,adminSettingsMock,adminUsersMock} from "./admin-data";

export const adminStorageKeys={users:"bunya-admin-users",alerts:"bunya-admin-alerts",operations:"bunya-admin-operations",joinReviews:"bunya-admin-join-reviews",productReviews:"bunya-admin-product-reviews",sourcingOverrides:"bunya-admin-sourcing-overrides",orderActions:"bunya-admin-order-actions",projectReviews:"bunya-admin-project-reviews",financeActions:"bunya-admin-finance-actions",support:"bunya-admin-support",policies:"bunya-admin-policies",settings:"bunya-admin-settings",audit:"bunya-admin-audit-log",sidebar:"bunya-admin-sidebar-state",roles:"bunya-admin-role-permissions",decisions:"bunya-admin-decisions"} as const;
type Store={users:AdminUser[];alerts:AdminAlert[];operations:AdminOperationEvent[];joinReviews:JoinRequestReview[];sourcingOverrides:AdminOverride[];support:SupportAssignment[];policies:PlatformPolicyVersion[];settings:PlatformSetting[];audit:AuditLogEntry[];roles:AdminRole[];decisions:AdminDecision[]};
const defaults:Store={users:adminUsersMock,alerts:adminAlertsMock,operations:adminOperationsMock,joinReviews:[],sourcingOverrides:[],support:[],policies:[],settings:adminSettingsMock,audit:[],roles:adminRolesMock,decisions:[]};
export function readAdmin<Key extends keyof Store>(key:Key):Store[Key]{return read(adminStorageKeys[key],defaults[key])}
export function writeAdmin<Key extends keyof Store>(key:Key,value:Store[Key]){write(adminStorageKeys[key],value);window.dispatchEvent(new CustomEvent("bunya-admin-data",{detail:key}))}
export function adminId(prefix:string){return typeof crypto!=="undefined"&&"randomUUID"in crypto?`${prefix}-${crypto.randomUUID()}`:`${prefix}-${Date.now()}`}
export function recordAdminDecision(module:string,entityId:string,action:string,reason:string,previousStatus?:string,nextStatus?:string){const now=new Date().toISOString();const decision:AdminDecision={id:adminId("admin-decision"),module,entityId,action,reason,adminId:"admin-super",adminName:"مدير منصة بُنية",previousStatus,nextStatus,createdAt:now};writeAdmin("decisions",[decision,...readAdmin("decisions")]);const audit:AuditLogEntry={id:adminId("audit"),adminId:"admin-super",adminName:"مدير منصة بُنية",action,entityType:module,entityId,reason,before:previousStatus?{status:previousStatus}:undefined,after:nextStatus?{status:nextStatus}:undefined,ipAddress:"127.0.0.1 Mock",userAgent:"Bunya Admin Console Mock",sensitivity:"sensitive",result:"success",createdAt:now};writeAdmin("audit",[audit,...readAdmin("audit")]);return decision}
export function logAdminAudit(action:string,entityType:string,entityId:string,reason:string,sensitivity:AuditLogEntry["sensitivity"]="sensitive",before?:AuditLogEntry["before"],after?:AuditLogEntry["after"]){const entry:AuditLogEntry={id:adminId("audit"),adminId:"admin-super",adminName:"مدير منصة بُنية",action,entityType,entityId,reason,before,after,ipAddress:"127.0.0.1 Mock",userAgent:"Bunya Admin Console Mock",sensitivity,result:"success",createdAt:new Date().toISOString()};writeAdmin("audit",[entry,...readAdmin("audit")]);return entry}
function read<T>(key:string,fallback:T):T{if(typeof window==="undefined")return structuredClone(fallback);try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw) as T:structuredClone(fallback)}catch{return structuredClone(fallback)}}
function write<T>(key:string,value:T){localStorage.setItem(key,JSON.stringify(value,(field,nested)=>field==="previewUrl"||field==="passwordProof"||field==="code"?undefined:nested))}
