"use client";
import type {AdminModuleKey,AdminRecord} from "./admin-types";
import type {ContractorApplication,CustomerRegistration,ProviderApplication} from "./bunya-types";
import {localStorageKeys,readLocalCollection} from "./bunya-local";
import {customerProfileMock} from "./customer-data";
import {readCustomer} from "./customer-storage";
import {providerProfileMock} from "./provider-data";
import {readProviderCollection,writeProviderCollection,writeProviderProfile} from "./provider-storage";
import {contractorProfileMock} from "./contractor-data";
import {readContractor,writeContractor,writeContractorProfile} from "./contractor-storage";
import {readSourcing} from "./sourcing-storage";
import {publishProjectRequest,readProjectStore,syncPublishedOpportunity,writeProjectStore} from "./project-request-storage";
import {platformProjectPolicies} from "./project-policies";
import {readAdmin} from "./admin-storage";

const record=(id:string,code:string,title:string,subtitle:string,status:string,meta:AdminRecord["meta"],href?:string,priority?:AdminRecord["priority"]):AdminRecord=>({id,code,title,subtitle,status,meta,href,priority});
const date=(value:string)=>new Date(value).toLocaleDateString("ar-SA");
const money=(value:number)=>new Intl.NumberFormat("ar-SA",{style:"currency",currency:"SAR",maximumFractionDigits:0}).format(value);

export function adminModuleRecords(module:AdminModuleKey):AdminRecord[]{
 if(module==="users"){const customers=readLocalCollection<CustomerRegistration>(localStorageKeys.customers);return[record(customerProfileMock.id,customerProfileMock.username,customerProfileMock.fullName,"عميل · تحقق أساسي","active",[{label:"الجوال",value:customerProfileMock.mobile},{label:"البريد",value:customerProfileMock.email},{label:"العمليات",value:String(readCustomer("orders").length)}],`/admin/users/${customerProfileMock.id}`),record(providerProfileMock.id,providerProfileMock.username,providerProfileMock.companyName,"مزود · ملف معتمد",providerProfileMock.accountStatus,[{label:"المسؤول",value:providerProfileMock.contactName},{label:"الجوال",value:providerProfileMock.mobile},{label:"المنتجات",value:String(readProviderCollection("products").length)}],`/admin/users/${providerProfileMock.id}`),record(contractorProfileMock.id,contractorProfileMock.id,contractorProfileMock.companyName??contractorProfileMock.displayName,"مقاول · ملف مهني",contractorProfileMock.accountStatus,[{label:"الجوال",value:contractorProfileMock.mobile},{label:"التقييم",value:String(contractorProfileMock.averageRating)},{label:"المشاريع",value:String(contractorProfileMock.projectsCount)}],`/admin/users/${contractorProfileMock.id}`),...customers.filter(item=>item.id!==customerProfileMock.id).map(item=>record(item.id,item.username,item.fullName,"عميل مسجل محليًا","active",[{label:"الجوال",value:item.mobile},{label:"البريد",value:item.email},{label:"الانضمام",value:date(item.createdAt)}],`/admin/users/${item.id}`)),...readAdmin("users").map(item=>record(item.id,item.email,item.name,"مدير منصة",item.status,[{label:"الجوال",value:item.mobile},{label:"الدور",value:readAdmin("roles").find(role=>role.id===item.roleId)?.label??item.roleId},{label:"آخر نشاط",value:date(item.lastActivityAt)}],`/admin/users/${item.id}`))]}
 if(module==="providers_join"){return readLocalCollection<ProviderApplication>(localStorageKeys.providers).map(item=>record(item.id,item.username,item.companyName,item.contactName,item.status,[{label:"الجوال",value:item.mobile},{label:"الموقع",value:item.mapsUrl},{label:"التصنيفات",value:item.categories.join("، ")},{label:"المناطق",value:item.deliveryRegions.join("، ")||"لا يوجد توصيل"},{label:"الخصم",value:item.discountCode??"—"},{label:"التاريخ",value:date(item.createdAt)}],`/admin/join-requests/providers/${item.id}`))}
 if(module==="contractors_join"){return readLocalCollection<ContractorApplication>(localStorageKeys.contractors).map(item=>record(item.id,item.id,item.contractorName,"طلب مقاول",item.status,[{label:"الجوال",value:item.mobile},{label:"البريد",value:item.email},{label:"المناطق",value:item.workRegions.join("، ")},{label:"التخصصات",value:item.specialties.join("، ")},{label:"المستندات",value:String(item.documents.length)},{label:"التاريخ",value:date(item.createdAt)}],`/admin/join-requests/contractors/${item.id}`))}
 if(module==="drivers"){return readProviderCollection("deliveries").map(item=>record(item.id,item.deliveryCode,item.driverName,"سائق توصيل Mock",item.status,[{label:"الطلب",value:item.orderCode},{label:"المحاولات الفاشلة",value:String(item.verification.attempts)},{label:"التقييم",value:"4.8 Mock"},{label:"آخر نشاط",value:date(item.assignedAt)}]))}
 if(module==="admins"){return readAdmin("users").map(item=>record(item.id,item.email,item.name,readAdmin("roles").find(role=>role.id===item.roleId)?.label??item.roleId,item.status,[{label:"الجوال",value:item.mobile},{label:"آخر نشاط",value:date(item.lastActivityAt)},{label:"الصلاحيات",value:String(readAdmin("roles").find(role=>role.id===item.roleId)?.permissions.length??0)}]))}
 if(module==="catalog"||module==="product_review"){return readProviderCollection("products").map(item=>record(item.id,item.id,item.name,`${item.category} · ${item.offerType==="sale"?"بيع":"تأجير"}`,item.status,[{label:"السعر",value:money(item.price)},{label:"الوحدات",value:item.units.map(unit=>unit.name).join("، ")},{label:"الصور",value:String(item.images.length)},{label:"التوصيل",value:item.delivery.available?"متاح":"غير متاح"}]))}
 if(module==="pricing"){return readSourcing("prices").map(item=>record(item.id,item.id,item.productId,item.providerId,item.freshnessStatus,[{label:"السعر",value:money(item.unitPrice)},{label:"الضريبة",value:item.vatInclusive?"شامل":"غير شامل"},{label:"آخر تحديث",value:date(item.lastUpdatedAt)},{label:"آخر تأكيد",value:date(item.lastConfirmedAt)},{label:"الانتهاء",value:new Date(item.expiresAt).toLocaleString("ar-SA")}]))}
 if(module==="sourcing"){return readSourcing("requests").map(item=>record(item.id,item.internalCode,item.customerRequestCode,`${item.items.length} عنصر · توريد داخلي`,item.stage,[{label:"المهلة",value:new Date(item.responseDeadlineAt).toLocaleString("ar-SA")},{label:"الجاهزية",value:new Date(item.expectedReadyAt).toLocaleString("ar-SA")},{label:"الاستجابات",value:String(readSourcing("responses").filter(response=>response.requestId===item.id).length)}],`/admin/sourcing/${item.id}`))}
 if(module==="bunya_quotes"){return readSourcing("quotes").map(item=>record(item.id,item.quoteCode,item.requestCode,"عرض موحد باسم بُنية",item.status,[{label:"الإجمالي",value:money(item.total)},{label:"الضريبة",value:money(item.vat)},{label:"التوصيل",value:money(item.deliveryFee)},{label:"الصلاحية",value:date(item.validUntil)}]))}
 if(module==="quote_requests"){return readCustomer("quoteRequests").map(item=>record(item.id,item.requestCode,item.projectName,`${item.items.length} منتج`,item.status,[{label:"الموعد",value:date(item.desiredReceiptAt)},{label:"العروض",value:String(item.receivedQuotesCount)},{label:"الإنشاء",value:date(item.createdAt)}]))}
 if(module==="orders"){return readCustomer("orders").map(item=>record(item.id,item.orderCode,item.brandName,`${item.items.length} منتج`,item.status,[{label:"الإجمالي",value:money(item.total)},{label:"الدفع",value:item.paymentStatus},{label:"التوصيل",value:item.deliveryStatus},{label:"الموعد",value:date(item.expectedAt)}]))}
 if(module==="deliveries"){return readCustomer("deliveries").map(item=>record(item.id,item.deliveryCode,item.shipmentLabel,item.driverName??"لم يُسند",item.status,[{label:"الطلب",value:item.orderCode},{label:"الموعد",value:date(item.expectedAt)},{label:"التأكيد",value:item.deliveredAt?date(item.deliveredAt):"بانتظار التأكيد"}]))}
 if(module==="delivery_codes"){return readCustomer("deliveryCodes").map(item=>record(item.deliveryId,item.deliveryId,item.orderId,"hash محمي — لا يعرض الكود",item.verifiedAt?"verified":"pending",[{label:"Hash",value:`${item.proof.slice(0,12)}…${item.proof.slice(-8)}`},{label:"المحاولات",value:`${item.attempts}/${item.maxAttempts}`},{label:"التأكيد",value:item.verifiedAt?date(item.verifiedAt):"—"}]))}
 if(module==="project_requests"){return readProjectStore("requests").map(item=>record(item.id,item.requestCode,item.title,`${item.projectType} · ${item.city}`,item.status,[{label:"الميزانية",value:money(item.budgetMax)},{label:"المدة",value:`${item.durationValue} ${item.durationUnit}`},{label:"المخططات",value:String(item.attachments.length)},{label:"العروض",value:String(item.proposalCount)},{label:"التعليقات",value:String(item.approvedCommentCount)}],`/admin/project-requests/${item.id}`))}
 if(module==="contractor_opportunities"){return readContractor("opportunities").map(item=>record(item.id,item.opportunityCode,item.title,`${item.projectType} · ${item.city}`,item.status,[{label:"الميزانية",value:`${money(item.estimatedBudgetMin)} – ${money(item.estimatedBudgetMax)}`},{label:"المدة",value:item.estimatedDuration},{label:"المهلة",value:date(item.deadlineAt)}]))}
 if(module==="contractor_proposals"){return readContractor("proposals").map(item=>record(item.id,item.proposalCode,item.projectTitle,item.opportunityCode,item.status,[{label:"القيمة",value:money(item.amount)},{label:"المدة",value:item.executionDuration},{label:"المراحل",value:String(item.stages.length)},{label:"الصلاحية",value:date(item.validUntil)}]))}
 if(module==="contractor_projects"){return readContractor("projects").map(item=>record(item.id,item.projectCode,item.name,item.customerLabel,item.status,[{label:"القيمة",value:money(item.value)},{label:"الإنجاز",value:`${item.progress}%`},{label:"المراحل",value:String(item.milestones.length)},{label:"الدفع",value:item.paymentStatus}]))}
 if(module==="contractor_documents"){return readContractor("documents").map(item=>record(item.id,item.documentNumber??item.id,item.type,item.file?.name??"غير مرفوع",item.status,[{label:"الإصدار",value:item.issuedAt?date(item.issuedAt):"—"},{label:"الانتهاء",value:item.expiresAt?date(item.expiresAt):"—"},{label:"سبب الرفض",value:item.rejectionReason??"—"}]))}
 if(module==="reviews"){return readContractor("reviews").map(item=>record(item.id,item.projectCode,`${item.rating} ★`,item.customerLabel,item.reply?"replied":"published",[{label:"الالتزام",value:String(item.commitment)},{label:"الجودة",value:String(item.quality)},{label:"التواصل",value:String(item.communication)},{label:"التعليق",value:item.comment}]))}
 if(module==="finance"){const contractor=readContractor("transactions").map(item=>record(item.id,item.transactionCode,item.projectCode,item.milestoneLabel,item.status,[{label:"النوع",value:item.type},{label:"المبلغ",value:money(item.amount)},{label:"الرصيد",value:money(item.balanceAfter)}]));const provider=readProviderCollection("transactions").map(item=>record(item.id,item.transactionCode,item.reference,"مزود",item.status,[{label:"النوع",value:item.type},{label:"المبلغ",value:money(item.amount)},{label:"التاريخ",value:date(item.date)},{label:"الرصيد",value:money(item.balanceAfter)}]));return[...contractor,...provider]}
 if(module==="provider_settlements"){return readProviderCollection("settlements").map(item=>record(item.id,item.settlementCode,item.bankLabel,"تصفية مزود",item.status,[{label:"المبلغ",value:money(item.amount)},{label:"التاريخ",value:date(item.createdAt)},{label:"الملاحظات",value:item.notes??"—"}]))}
 if(module==="contractor_settlements"){return readContractor("settlements").map(item=>record(item.id,item.settlementCode,item.bankAccountLabel,"تصفية مقاول",item.status,[{label:"المبلغ",value:money(item.amount)},{label:"التاريخ",value:date(item.createdAt)},{label:"الملاحظات",value:item.notes??"—"}]))}
 if(module==="invoices"){return readCustomer("invoices").map(item=>record(item.id,item.invoiceCode,item.orderCode,item.issuerName,item.status,[{label:"الإجمالي",value:money(item.total)},{label:"الضريبة",value:money(item.vat)},{label:"التوصيل",value:money(item.deliveryFee)},{label:"الإصدار",value:date(item.issuedAt)}]))}
 if(module==="notifications"){const project=readProjectStore("notifications").map(item=>record(item.id,item.type,item.title,`${item.recipientRole} · ${item.message}`,item.read?"read":"unread",[{label:"المسار",value:item.link},{label:"التاريخ",value:date(item.createdAt)}]));const customer=readCustomer("notifications").map(item=>record(item.id,item.type,item.title,`عميل · ${item.message}`,item.read?"read":"unread",[{label:"المسار",value:item.link},{label:"التاريخ",value:date(item.createdAt)}]));return[...project,...customer]}
 if(module==="support"){const customer=readCustomer("tickets").map(item=>record(item.id,item.ticketCode,item.subject,"عميل",item.status,[{label:"الأولوية",value:item.priority},{label:"النوع",value:item.issueType},{label:"الرسالة",value:item.message}]));const provider=readProviderCollection("supportTickets").map(item=>record(item.id,item.ticketCode,item.subject,"مزود",item.status,[{label:"الأولوية",value:item.priority},{label:"التصنيف",value:item.category},{label:"الرسالة",value:item.message}]));const contractor=readContractor("tickets").map(item=>record(item.id,item.ticketCode,item.subject,"مقاول",item.status,[{label:"الأولوية",value:item.priority},{label:"التصنيف",value:item.category},{label:"الرسالة",value:item.message}]));return[...customer,...provider,...contractor]}
 if(module==="policies"){return platformProjectPolicies.map(item=>record(item.id,item.version,item.title,item.content.join(" · "),item.active?"active":"inactive",[{label:"الموافقة",value:item.requiresAcceptance?"مطلوبة":"غير مطلوبة"},{label:"آخر تحديث",value:date(item.updatedAt)},{label:"القبولات",value:String(readProjectStore("acceptances").filter(value=>value.policyId===item.id).length)}]))}
 if(module==="audit"){const admin=readAdmin("audit").map(item=>record(item.id,item.action,item.entityType,item.adminName,item.result,[{label:"المعرف",value:item.entityId},{label:"السبب",value:item.reason},{label:"الحساسية",value:item.sensitivity},{label:"الوقت",value:new Date(item.createdAt).toLocaleString("ar-SA")}]));const project=readProjectStore("audit").map(item=>record(item.id,item.action,item.projectRequestId,item.actorLabel,item.actorRole,[{label:"السبب",value:item.reason??"—"},{label:"الوقت",value:new Date(item.createdAt).toLocaleString("ar-SA")} ]));return[...admin,...project]}
 if(module==="settings"){return readAdmin("settings").map(item=>record(item.id,item.key,item.label,item.section,item.sensitive?"sensitive":"standard",[{label:"القيمة",value:`${String(item.value)} ${item.unit??""}`},{label:"الحد الأدنى",value:String(item.validation.min??"—")},{label:"الحد الأعلى",value:String(item.validation.max??"—")},{label:"آخر تحديث",value:date(item.updatedAt)}]))}
 return[];
}

export function applyAdminSourceAction(module:AdminModuleKey,entityId:string,action:string,reason:string):string{
 const now=new Date().toISOString();
 if(module==="providers_join"){const applications=readLocalCollection<ProviderApplication>(localStorageKeys.providers);const target=applications.find(item=>item.id===entityId);const status=action==="اعتماد"?"approved" as const:action==="رفض"?"rejected" as const:action==="طلب تعديلات"?"needs_changes" as const:undefined;if(target&&status){localStorage.setItem(localStorageKeys.providers,JSON.stringify(applications.map(item=>item.id===entityId?{...item,status}:item)));if(status==="approved")writeProviderProfile({...providerProfileMock,id:target.id,companyName:target.companyName,contactName:target.contactName,mobile:target.mobile,email:target.email,username:target.username,mapsUrl:target.mapsUrl,latitude:target.latitude??0,longitude:target.longitude??0,categories:target.categories,deliveryAvailable:target.deliveryAvailable,deliveryRegions:target.deliveryRegions,accountStatus:"approved"});return status}}
 if(module==="contractors_join"){const applications=readLocalCollection<ContractorApplication>(localStorageKeys.contractors);const target=applications.find(item=>item.id===entityId);const status=action==="اعتماد"?"approved" as const:action==="رفض"?"rejected" as const:action.includes("تعديل")||action.includes("مستند")?"needs_changes" as const:undefined;if(target&&status){localStorage.setItem(localStorageKeys.contractors,JSON.stringify(applications.map(item=>item.id===entityId?{...item,status}:item)));if(status==="approved")writeContractorProfile({...contractorProfileMock,id:target.id,displayName:target.contractorName,companyName:target.contractorName,mobile:target.mobile,email:target.email,specialties:target.specialties,workRegions:target.workRegions,accountStatus:"approved",directoryVisible:true});return status}}
 if(module==="product_review"){const status=action==="اعتماد"?"active" as const:action==="رفض"?"rejected" as const:action==="طلب تعديل"?"pending_review" as const:action==="إيقاف"||action==="حظر المنتج"?"unavailable" as const:undefined;if(status){writeProviderCollection("products",readProviderCollection("products").map(item=>item.id===entityId?{...item,status,rejectionReason:status==="rejected"?reason:item.rejectionReason,updatedAt:now}:item));return status}}
 if(module==="project_requests"){const request=readProjectStore("requests").find(item=>item.id===entityId);if(request&&action==="اعتماد ونشر"){publishProjectRequest(entityId);return"receiving_proposals"}if(request&&["رفض","إعادة للعميل","إيقاف النشر","أرشفة"].includes(action)){const status=action==="رفض"?"rejected" as const:action==="إعادة للعميل"?"needs_customer_changes" as const:action==="أرشفة"?"expired" as const:"pending_admin_review" as const;const next={...request,status,adminNote:reason,updatedAt:now};writeProjectStore("requests",readProjectStore("requests").map(item=>item.id===entityId?next:item));syncPublishedOpportunity(next);return status}}
 if(module==="provider_settlements"){const status=action==="اعتماد"?"approved" as const:action==="رفض"?"rejected" as const:action==="قيد التحويل"?"transferring" as const:action==="تم التحويل"?"transferred" as const:undefined;if(status){writeProviderCollection("settlements",readProviderCollection("settlements").map(item=>item.id===entityId?{...item,status,adminNotes:reason}:item));return status}}
 if(module==="contractor_settlements"){const status=action==="اعتماد"?"approved" as const:action==="رفض"?"rejected" as const:action==="قيد التحويل"?"transferring" as const:action==="تم التحويل"?"transferred" as const:undefined;if(status){writeContractor("settlements",readContractor("settlements").map(item=>item.id===entityId?{...item,status,reviewNotes:reason}:item));return status}}
 return action;
}
