"use client";
import type {ContractorDashboardProfile,ContractorDocument,ContractorFinancialTransaction,ContractorNotification,ContractorOpportunity,ContractorPortfolioItem,ContractorProject,ContractorProposal,ContractorReview,ContractorService,ContractorSettlementRequest,ContractorSupportTicket} from "./contractor-types";
import {contractorDocumentsMock,contractorNotificationsMock,contractorOpportunitiesMock,contractorPortfolioMock,contractorProfileMock,contractorProjectsMock,contractorProposalsMock,contractorReviewsMock,contractorServicesMock,contractorSettlementsMock,contractorTicketsMock,contractorTransactionsMock} from "./contractor-data";
export const contractorStorageKeys={profile:"bunya-contractor-profile",services:"bunya-contractor-services",opportunities:"bunya-contractor-opportunities",proposals:"bunya-contractor-proposals",projects:"bunya-contractor-projects",portfolio:"bunya-contractor-portfolio",reviews:"bunya-contractor-reviews",documents:"bunya-contractor-documents",transactions:"bunya-contractor-financial-transactions",settlements:"bunya-contractor-settlements",notifications:"bunya-contractor-notifications",tickets:"bunya-contractor-support-tickets",sidebar:"bunya-contractor-sidebar-state"} as const;
type Collections={services:ContractorService[];opportunities:ContractorOpportunity[];proposals:ContractorProposal[];projects:ContractorProject[];portfolio:ContractorPortfolioItem[];reviews:ContractorReview[];documents:ContractorDocument[];transactions:ContractorFinancialTransaction[];settlements:ContractorSettlementRequest[];notifications:ContractorNotification[];tickets:ContractorSupportTicket[]};
const defaults:Collections={services:contractorServicesMock,opportunities:contractorOpportunitiesMock,proposals:contractorProposalsMock,projects:contractorProjectsMock,portfolio:contractorPortfolioMock,reviews:contractorReviewsMock,documents:contractorDocumentsMock,transactions:contractorTransactionsMock,settlements:contractorSettlementsMock,notifications:contractorNotificationsMock,tickets:contractorTicketsMock};
export function readContractorProfile(){return read(contractorStorageKeys.profile,contractorProfileMock)}
export function writeContractorProfile(value:ContractorDashboardProfile){write(contractorStorageKeys.profile,value);signal("profile")}
export function readContractor<K extends keyof Collections>(key:K):Collections[K]{return read(contractorStorageKeys[key],defaults[key])}
export function writeContractor<K extends keyof Collections>(key:K,value:Collections[K]){write(contractorStorageKeys[key],value);signal(key)}
export function contractorId(prefix:string){return typeof crypto!=="undefined"&&"randomUUID"in crypto?`${prefix}-${crypto.randomUUID()}`:`${prefix}-${Date.now()}`}
export function createProjectFromAcceptedProposal(proposal:ContractorProposal){const projects=readContractor("projects");const existing=projects.find(item=>item.proposalId===proposal.id);if(existing)return existing;const now=new Date().toISOString();const project:ContractorProject={id:contractorId("project"),projectCode:`PRJ-${Date.now().toString().slice(-5)}`,proposalId:proposal.id,name:proposal.projectTitle,customerLabel:"عميل مشروع موثّق",value:proposal.amount,startAt:proposal.proposedStartAt,expectedEndAt:proposal.stages.at(-1)?.expectedAt??proposal.proposedStartAt,currentMilestoneId:proposal.stages[0]?.id??"",progress:0,status:"awaiting_start",nextPaymentLabel:proposal.payments[0]?.label??"حسب العقد",paymentStatus:"pending",scope:proposal.scopeDetails,mapsUrl:readContractor("opportunities").find(item=>item.id===proposal.opportunityId)?.mapsUrl??"",documents:proposal.attachments,team:proposal.team.split("،").map(item=>item.trim()),milestones:proposal.stages.map((stage,index)=>({...stage,startAt:index===0?proposal.proposedStartAt:proposal.stages[index-1]?.expectedAt??proposal.proposedStartAt,expectedEndAt:stage.expectedAt,progress:0,status:"not_started" as const,evidence:[]})),updates:[],createdAt:now};writeContractor("projects",[project,...projects]);const transaction:ContractorFinancialTransaction={id:contractorId("transaction"),transactionCode:`CTX-${Date.now().toString().slice(-5)}`,projectId:project.id,projectCode:project.projectCode,milestoneLabel:"دفعة مقدمة",type:"advance",amount:proposal.amount*(proposal.payments[0]?.percentage??0)/100,status:"pending",date:now.slice(0,10),balanceAfter:readContractor("transactions")[0]?.balanceAfter??0};writeContractor("transactions",[transaction,...readContractor("transactions")]);return project}
function read<T>(key:string,fallback:T):T{if(typeof window==="undefined")return structuredClone(fallback);try{const value=localStorage.getItem(key);return value?JSON.parse(value) as T:structuredClone(fallback)}catch{return structuredClone(fallback)}}
function write<T>(key:string,value:T){localStorage.setItem(key,JSON.stringify(value,(field,nested)=>field==="previewUrl"?undefined:nested))}
function signal(detail:string){window.dispatchEvent(new CustomEvent("bunya-contractor-data",{detail}))}
