import type {CustomerAddress,CustomerDelivery,CustomerInvoice,CustomerNotification,CustomerOrder,CustomerProfile,CustomerQuoteRequest,CustomerSupportTicket,DeliveryCodeState,ReceivedProviderQuote,SavedContractor} from "./customer-types";
import {customerAddressesMock,customerDeliveriesMock,customerInvoicesMock,customerNotificationsMock,customerOrdersMock,customerProfileMock,customerQuoteRequestsMock,customerSupportTicketsMock,deliveryCodesMock,receivedQuotesMock,savedContractorsMock} from "./customer-data";
import type {DeliveryAssignment,ProviderOrder,QuoteRequest} from "./provider-types";
import {providerDeliveriesMock,providerOrdersMock,providerQuoteRequestsMock} from "./provider-data";
import type {BunyaCustomerQuote,InternalFulfillmentOrder,InternalSourcingRequest} from "./sourcing-types";
import {readSourcing,writeSourcing} from "./sourcing-storage";

export const customerStorageKeys={profile:"bunya-customer-profile",addresses:"bunya-customer-addresses",cart:"bunya-customer-quote-cart",homeCart:"bunya-home-quote-items",quoteRequests:"bunya-customer-quote-requests",quotes:"bunya-customer-received-quotes",orders:"bunya-customer-orders",deliveries:"bunya-customer-deliveries",deliveryCodes:"bunya-customer-delivery-codes",invoices:"bunya-customer-invoices",notifications:"bunya-customer-notifications",contractors:"bunya-customer-saved-contractors",tickets:"bunya-customer-support-tickets",sidebar:"bunya-customer-sidebar-state"} as const;
type Map={addresses:CustomerAddress[];quoteRequests:CustomerQuoteRequest[];quotes:ReceivedProviderQuote[];orders:CustomerOrder[];deliveries:CustomerDelivery[];deliveryCodes:DeliveryCodeState[];invoices:CustomerInvoice[];notifications:CustomerNotification[];contractors:SavedContractor[];tickets:CustomerSupportTicket[]};
const defaults:Map={addresses:customerAddressesMock,quoteRequests:customerQuoteRequestsMock,quotes:receivedQuotesMock,orders:customerOrdersMock,deliveries:customerDeliveriesMock,deliveryCodes:deliveryCodesMock,invoices:customerInvoicesMock,notifications:customerNotificationsMock,contractors:savedContractorsMock,tickets:customerSupportTicketsMock};

export function readCustomerProfile(){return read(customerStorageKeys.profile,customerProfileMock)}
export function writeCustomerProfile(value:CustomerProfile){write(customerStorageKeys.profile,value)}
export function readCustomer<Key extends keyof Map>(key:Key):Map[Key]{const own=read(customerStorageKeys[key],defaults[key]) as Map[Key];if(key==="orders")return syncOrders(own as CustomerOrder[]) as Map[Key];if(key==="deliveries")return syncDeliveries(own as CustomerDelivery[]) as Map[Key];if(key==="deliveryCodes")return syncCodes(own as DeliveryCodeState[]) as Map[Key];return own}
export function writeCustomer<Key extends keyof Map>(key:Key,value:Map[Key]){write(customerStorageKeys[key],value);window.dispatchEvent(new CustomEvent("bunya-customer-data",{detail:key}))}
export function createCustomerId(prefix:string){return typeof crypto!=="undefined"&&"randomUUID"in crypto?`${prefix}-${crypto.randomUUID()}`:`${prefix}-${Date.now()}`}

export function publishRequestToProvider(request:CustomerQuoteRequest){
 const now=request.submittedAt??request.createdAt;
 const internalId=`source-${request.id}`;
 const sourcing:InternalSourcingRequest={id:internalId,internalCode:`ISR-${request.requestCode.replace("RFQ-","")}`,customerRequestId:request.id,customerRequestCode:request.requestCode,items:request.items.map(item=>({id:`source-${item.id}`,customerRequestItemId:item.id,productId:item.productId,productName:item.productName,quantity:item.quantity,unit:item.unit,measurement:item.measurementLabel,region:request.projectName,requiredAt:request.desiredReceiptAt})),stage:"received",expectedReadyAt:new Date(new Date(now).getTime()+60*60000).toISOString(),responseDeadlineAt:new Date(new Date(now).getTime()+45*60000).toISOString(),createdAt:now};
 const all=readSourcing("requests");if(!all.some(item=>item.id===internalId))writeSourcing("requests",[sourcing,...all]);
 const provider=read<QuoteRequest[]>("bunya-provider-quote-requests",providerQuoteRequestsMock);
 for(const item of sourcing.items){if(provider.some(value=>value.id===item.id))continue;provider.unshift({id:item.id,requestCode:sourcing.internalCode,productId:item.productId,productName:item.productName,productImageLabel:item.productName.slice(0,1),category:"مواد بناء",quantity:item.quantity,unit:item.unit,measurement:item.measurement,deliveryRegion:item.region,mapsUrl:request.mapsUrl,desiredReceiptAt:item.requiredAt,receivedAt:now,deadlineAt:sourcing.responseDeadlineAt,customerLabel:"طلب داخلي من بُنية",customerNotes:request.generalNotes,specifications:[],status:"new"});}
 write("bunya-provider-quote-requests",provider);
}

export function acceptBunyaQuote(request:CustomerQuoteRequest,quote:BunyaCustomerQuote){
 const now=new Date().toISOString();
 writeCustomer("quoteRequests",readCustomer("quoteRequests").map(item=>item.id===request.id?{...item,status:"accepted",awardedQuoteId:quote.id}:item));
 writeSourcing("quotes",readSourcing("quotes").map(item=>item.id===quote.id?{...item,status:"accepted"}:item));
 const invoiceId=createCustomerId("invoice");
 const order:CustomerOrder={id:createCustomerId("order"),orderCode:`BO-${Date.now().toString().slice(-5)}`,quoteId:quote.id,requestId:request.id,brandName:"بُنية",items:request.items,subtotal:quote.subtotal,vat:quote.vat,deliveryFee:quote.deliveryFee,total:quote.total,paymentStatus:"unpaid",status:"confirmed",deliveryStatus:"بانتظار الدفع وبدء التجهيز",expectedAt:quote.expectedDeliveryAt,mapsUrl:request.mapsUrl,invoiceId,createdAt:now,history:[{id:createCustomerId("history"),status:"confirmed",label:"تم اعتماد عرض بُنية وتأكيد الطلب",at:now}]};
 writeCustomer("orders",[order,...readCustomer("orders")]);
 const invoice:CustomerInvoice={id:invoiceId,invoiceCode:`INV-${order.orderCode.replace("BO-","")}`,orderId:order.id,orderCode:order.orderCode,issuerName:"بُنية",subtotal:order.subtotal,vat:order.vat,deliveryFee:order.deliveryFee,total:order.total,status:"unpaid",issuedAt:now};
 writeCustomer("invoices",[invoice,...readCustomer("invoices")]);
 const source=readSourcing("requests").find(item=>item.customerRequestId===request.id);const selection=source&&readSourcing("selections").find(item=>item.requestId===source.id);
 if(source&&selection){const providerIds=[...new Set(selection.selectedItems.map(item=>item.providerId))];const fulfillment:InternalFulfillmentOrder[]=providerIds.map((providerId,index)=>({id:createCustomerId("fulfillment"),fulfillmentCode:`IFO-${Date.now().toString().slice(-5)}-${index+1}`,bunyaOrderId:order.id,providerId,items:selection.selectedItems.filter(item=>item.providerId===providerId),deliveryFee:selection.selectedItems.filter(item=>item.providerId===providerId).reduce((sum,item)=>sum+item.deliveryFee,0),deliveryRegion:request.projectName,requiredAt:request.desiredReceiptAt,status:"assigned",createdAt:now}));writeSourcing("fulfillment",[...fulfillment,...readSourcing("fulfillment")]);const providerOrders=read<ProviderOrder[]>("bunya-provider-orders",providerOrdersMock);const own=fulfillment.filter(item=>item.providerId==="provider-modern-materials").map(item=>({id:item.id,orderCode:item.fulfillmentCode,quoteId:item.items[0]?.responseId??quote.id,customerLabel:"بُنية",projectLabel:`إسناد داخلي ${source.internalCode}`,productName:item.items.map(selected=>request.items.find(value=>value.productId===selected.productId)?.productName??"منتج").join("، "),productImageLabel:"ب",quantity:item.items.reduce((sum,value)=>sum+value.quantity,0),unit:request.items[0]?.unit??"وحدة",total:item.items.reduce((sum,value)=>sum+value.totalLandedCost,0),paymentStatus:"pending" as const,status:"confirmed" as const,deliveryStatus:"تم الإسناد من بُنية",deliveryRegion:request.projectName,mapsUrl:request.mapsUrl,deliveryCodeVerified:false,createdAt:now,history:[{id:createCustomerId("history"),status:"confirmed" as const,label:"تم إسناد أمر التوريد داخليًا من بُنية",at:now}]}));write("bunya-provider-orders",[...own,...providerOrders]);}
 return order;
}

export function rejectBunyaQuote(requestId:string,quoteId:string){writeSourcing("quotes",readSourcing("quotes").map(item=>item.id===quoteId?{...item,status:"rejected"}:item));writeCustomer("quoteRequests",readCustomer("quoteRequests").map(item=>item.id===requestId?{...item,status:"rejected"}:item))}
function syncOrders(orders:CustomerOrder[]){const provider=read<ProviderOrder[]>("bunya-provider-orders",providerOrdersMock);return orders.map(order=>{const fulfillment=readSourcing("fulfillment").filter(item=>item.bunyaOrderId===order.id);const matches=provider.filter(item=>fulfillment.some(value=>value.id===item.id));const match=matches[0];return match?{...order,status:match.status,deliveryStatus:match.deliveryStatus,driverName:match.driverName,history:match.history}:order})}
function syncDeliveries(items:CustomerDelivery[]){const provider=read<DeliveryAssignment[]>("bunya-provider-deliveries",providerDeliveriesMock);return items.map(item=>{const match=provider.find(value=>value.id===item.id||value.orderId===item.orderId);return match?{...item,status:match.status==="delivered"?"delivered":match.status==="out_for_delivery"?"out_for_delivery":"assigned",driverName:match.driverName,deliveredAt:match.deliveredAt}:item})}
function syncCodes(codes:DeliveryCodeState[]){const provider=read<DeliveryAssignment[]>("bunya-provider-deliveries",providerDeliveriesMock);return codes.map(code=>{const match=provider.find(item=>item.id===code.deliveryId||item.orderId===code.orderId);return match?{...code,proof:match.verification.proof,attempts:match.verification.attempts,maxAttempts:match.verification.maxAttempts,verifiedAt:match.verification.verifiedAt}:code})}
function read<T>(key:string,fallback:T):T{if(typeof window==="undefined")return structuredClone(fallback);try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw) as T:structuredClone(fallback)}catch{return structuredClone(fallback)}}
function write<T>(key:string,value:T){localStorage.setItem(key,JSON.stringify(value))}
