"use client";
import type {DeliveryConfirmationRecord,DriverAdminAction,DriverDeliveryAssignment,DriverDeliveryStatus,ProviderDriver,PwaInstallState} from "./driver-types";
import {normalizeValue} from "./bunya-local";
import {createProviderId,readProviderCollection,readProviderProfile,writeProviderCollection} from "./provider-storage";
import type {DeliveryAssignment,FinancialTransaction,ProviderOrder} from "./provider-types";

export const driverStorageKeys={drivers:"bunya-provider-drivers",assignments:"bunya-provider-delivery-assignments",confirmations:"bunya-delivery-confirmations",adminActions:"bunya-admin-driver-actions",installState:"bunya-pwa-install-state",lastRoleRoute:"bunya-pwa-last-role-route"} as const;

export function readDrivers(){return read<ProviderDriver[]>(driverStorageKeys.drivers,[])}
export function writeDrivers(value:ProviderDriver[]){write(driverStorageKeys.drivers,value);emit("drivers")}
export function readDriverAssignments(){return read<DriverDeliveryAssignment[]>(driverStorageKeys.assignments,[])}
export function writeDriverAssignments(value:DriverDeliveryAssignment[]){write(driverStorageKeys.assignments,value);emit("assignments")}
export function readDeliveryConfirmations(){return read<DeliveryConfirmationRecord[]>(driverStorageKeys.confirmations,[])}
export function readDriverAdminActions(){return read<DriverAdminAction[]>(driverStorageKeys.adminActions,[])}
export function readPwaInstallState(){return read<PwaInstallState>(driverStorageKeys.installState,{installed:false})}
export function writePwaInstallState(value:PwaInstallState){write(driverStorageKeys.installState,value)}
export async function createProviderDriver(input:Omit<ProviderDriver,"id"|"providerId"|"providerName"|"mustChangePassword"|"failedCodeAttempts"|"violations"|"createdAt"|"updatedAt"> & {password:string}){
  const drivers=readDrivers();
  const duplicate=drivers.find(item=>[item.email,item.mobile,item.username].some(value=>[input.email,input.mobile,input.username].some(candidate=>normalizeValue(value)===normalizeValue(candidate))));
  if(duplicate)return {ok:false as const,message:"البريد أو الجوال أو اسم المستخدم مستخدم لحساب سائق آخر."};
  const profile=readProviderProfile();const now=new Date().toISOString();
  const {password,...safeInput}=input;void password;
  const driver:ProviderDriver={...safeInput,id:createProviderId("driver"),providerId:profile.id,providerName:profile.companyName,email:normalizeValue(input.email),username:input.username.trim(),mobile:input.mobile.trim(),mustChangePassword:true,status:input.status==="suspended"?"suspended":"must_change_password",failedCodeAttempts:0,violations:0,createdAt:now,updatedAt:now};
  writeDrivers([driver,...drivers]);return {ok:true as const,driver};
}
export function endDriverSessions(driverId:string,reason:string,actorId="provider-local"){recordDriverAdminAction(driverId,"طلب إنهاء جلسات Supabase",reason,actorId)}
export async function resetDriverPassword(driverId:string,password:string,reason:string){void password;recordDriverAdminAction(driverId,"طلب إعادة تعيين كلمة مرور Supabase",reason,"provider-local");return{ok:false as const,message:"إعادة تعيين كلمة مرور السائق تتطلب خدمة خادمية مخوّلة، ولم تُخزن كلمة المرور محليًا."}}

export function setDriverStatus(driverId:string,status:ProviderDriver["status"],reason:string,actorId="provider-local"){const now=new Date().toISOString();writeDrivers(readDrivers().map(item=>item.id===driverId?{...item,status,mustChangePassword:status==="must_change_password",updatedAt:now}:item));if(status==="suspended")endDriverSessions(driverId,reason,actorId);recordDriverAdminAction(driverId,status==="suspended"?"إيقاف الحساب":"تفعيل الحساب",reason,actorId)}
export function recordDriverAdminAction(driverId:string,action:string,reason:string,adminId:string){const value:DriverAdminAction={id:createProviderId("driver-action"),driverId,action,reason,adminId,createdAt:new Date().toISOString()};write(driverStorageKeys.adminActions,[value,...readDriverAdminActions()])}

export function syncProviderAssignments(){
  const current=readDriverAssignments();const deliveries=readProviderCollection("deliveries");const orders=readProviderCollection("orders");const profile=readProviderProfile();
  const missing=deliveries.filter(delivery=>!current.some(item=>item.sourceDeliveryId===delivery.id)).map((delivery):DriverDeliveryAssignment=>{const order=orders.find(item=>item.id===delivery.orderId);return{id:createProviderId("assignment"),providerId:profile.id,sourceDeliveryId:delivery.id,orderId:delivery.orderId,orderCode:delivery.orderCode,deliveryCode:delivery.deliveryCode,region:order?.deliveryRegion??"غير محدد",mapsUrl:order?.mapsUrl??"",pickupAt:delivery.assignedAt,expectedAt:new Date(new Date(delivery.assignedAt).getTime()+6*60*60*1000).toISOString(),status:mapLegacyStatus(delivery.status),deliveryCodeProof:delivery.verification.proof,codeAttempts:delivery.verification.attempts,maxCodeAttempts:delivery.verification.maxAttempts,updates:[],createdAt:delivery.assignedAt,updatedAt:delivery.assignedAt,deliveredAt:delivery.deliveredAt}});
  const next=[...current,...missing];if(missing.length)writeDriverAssignments(next);return next;
}
export function assignDelivery(assignmentId:string,driverId:string,reason:string){const driver=readDrivers().find(item=>item.id===driverId);if(!driver||driver.status==="suspended")return false;const now=new Date().toISOString();writeDriverAssignments(syncProviderAssignments().map(item=>item.id===assignmentId?{...item,driverId,status:"assigned",updatedAt:now,updates:[...item.updates,{id:createProviderId("update"),status:"assigned",note:reason,actorRole:"provider",actorId:item.providerId,createdAt:now}]}:item));syncLegacyDriver(assignmentId,driver);return true}
export function removeDeliveryAssignment(assignmentId:string,reason:string){const target=readDriverAssignments().find(item=>item.id===assignmentId);if(!target||target.status!=="assigned")return false;const now=new Date().toISOString();writeDriverAssignments(readDriverAssignments().map(item=>item.id===assignmentId?{...item,driverId:undefined,updatedAt:now,updates:[...item.updates,{id:createProviderId("update"),status:"assigned",note:`أزيل الإسناد: ${reason}`,actorRole:"provider",actorId:item.providerId,createdAt:now}]}:item));return true}
export function updateDriverDeliveryStatus(assignmentId:string,driverId:string,status:DriverDeliveryStatus,note?:string){const current=readDriverAssignments();const item=current.find(value=>value.id===assignmentId&&value.driverId===driverId);if(!item)return false;const allowed:Record<DriverDeliveryStatus,DriverDeliveryStatus[]>={assigned:["picked_up","failed_delivery"],picked_up:["in_transit","failed_delivery"],in_transit:["arrived","failed_delivery"],arrived:["failed_delivery"],delivered:[],failed_delivery:[]};if(!allowed[item.status].includes(status))return false;const now=new Date().toISOString();writeDriverAssignments(current.map(value=>value.id===assignmentId?{...value,status,deliveryNote:note??value.deliveryNote,updatedAt:now,updates:[...value.updates,{id:createProviderId("update"),status,note,actorRole:"driver",actorId:driverId,createdAt:now}]}:value));syncLegacyStatus(item.sourceDeliveryId,status);return true}

export async function confirmDelivery(assignmentId:string,code:string,method:"driver"|"provider",actorId:string,details?:{delegateName?:string;deliveryReference?:string;note?:string}){
  const assignments=readDriverAssignments();const assignment=assignments.find(item=>item.id===assignmentId);if(!assignment)return {ok:false as const,message:"التوصيل غير موجود."};if(assignment.status==="delivered")return {ok:true as const,message:"تم تأكيد هذا التوصيل مسبقًا."};if(assignment.lockedUntil&&new Date(assignment.lockedUntil)>new Date())return {ok:false as const,message:"المحاولات مجمدة مؤقتًا. حاول لاحقًا."};
  const proof=await import("./provider-storage").then(module=>module.createDeliveryProof(code.trim()));const now=new Date().toISOString();
  if(proof!==assignment.deliveryCodeProof){const attempts=assignment.codeAttempts+1;const locked=attempts>=assignment.maxCodeAttempts?new Date(Date.now()+15*60*1000).toISOString():undefined;writeDriverAssignments(assignments.map(item=>item.id===assignmentId?{...item,codeAttempts:attempts,lockedUntil:locked,updatedAt:now}:item));if(assignment.driverId)writeDrivers(readDrivers().map(item=>item.id===assignment.driverId?{...item,failedCodeAttempts:item.failedCodeAttempts+1,updatedAt:now}:item));return {ok:false as const,message:locked?"الكود غير مطابق وتم تجميد المحاولات 15 دقيقة.":`الكود غير مطابق. متبقٍ ${(assignment.maxCodeAttempts-attempts).toLocaleString("ar-SA")} محاولات.`};}
  const confirmed:DriverDeliveryAssignment={...assignment,status:"delivered",deliveredAt:now,updatedAt:now,lockedUntil:undefined,updates:[...assignment.updates,{id:createProviderId("update"),status:"delivered",note:details?.note,actorRole:method,actorId,createdAt:now}]};writeDriverAssignments(assignments.map(item=>item.id===assignmentId?confirmed:item));
  const record:DeliveryConfirmationRecord={id:createProviderId("confirmation"),assignmentId,orderId:assignment.orderId,providerId:assignment.providerId,driverId:assignment.driverId,method,confirmedById:actorId,delegateName:details?.delegateName,deliveryReference:details?.deliveryReference,note:details?.note,confirmedAt:now};write(driverStorageKeys.confirmations,[record,...readDeliveryConfirmations()]);completeProviderDelivery(confirmed);return {ok:true as const,message:"تم تأكيد التسليم وتحديث الطلب بنجاح."};
}

function completeProviderDelivery(assignment:DriverDeliveryAssignment){const deliveries=readProviderCollection("deliveries");writeProviderCollection("deliveries",deliveries.map(item=>item.id===assignment.sourceDeliveryId?{...item,status:"delivered",deliveredAt:assignment.deliveredAt,customerConfirmed:true,verification:{...item.verification,attempts:assignment.codeAttempts,verifiedAt:assignment.deliveredAt}}:item));const orders=readProviderCollection("orders");const order=orders.find(item=>item.id===assignment.orderId);if(!order)return;const now=assignment.deliveredAt??new Date().toISOString();const updated:ProviderOrder={...order,status:"completed",deliveryStatus:"تم التسليم وتأكيد الكود",deliveryCodeVerified:true,history:[...order.history,{id:createProviderId("history"),status:"delivered",label:"تم التحقق من كود العميل وتأكيد التسليم",at:now},{id:createProviderId("history"),status:"completed",label:"اكتمل الطلب",at:now}]};writeProviderCollection("orders",orders.map(item=>item.id===order.id?updated:item));const transactions=readProviderCollection("transactions");if(!transactions.some(item=>item.reference===order.orderCode&&item.type==="order_amount")){const transaction:FinancialTransaction={id:createProviderId("transaction"),transactionCode:`TX-${Date.now().toString().slice(-4)}`,date:now,type:"order_amount",reference:order.orderCode,amount:order.total,status:"available",balanceAfter:transactions[0]?.balanceAfter??0};writeProviderCollection("transactions",[transaction,...transactions])}}
function syncLegacyDriver(assignmentId:string,driver:ProviderDriver){const assignment=readDriverAssignments().find(item=>item.id===assignmentId);if(!assignment)return;writeProviderCollection("deliveries",readProviderCollection("deliveries").map(item=>item.id===assignment.sourceDeliveryId?{...item,driverName:driver.fullName,driverPhone:driver.mobile}:item));writeProviderCollection("orders",readProviderCollection("orders").map(item=>item.id===assignment.orderId?{...item,driverName:driver.fullName}:item))}
function syncLegacyStatus(sourceDeliveryId:string,status:DriverDeliveryStatus){const legacy:DeliveryAssignment["status"]=status==="picked_up"?"picked_up":status==="in_transit"||status==="arrived"?"out_for_delivery":status==="delivered"?"delivered":"assigned";writeProviderCollection("deliveries",readProviderCollection("deliveries").map(item=>item.id===sourceDeliveryId?{...item,status:legacy}:item))}
function mapLegacyStatus(status:DeliveryAssignment["status"]):DriverDeliveryStatus{return status==="out_for_delivery"?"in_transit":status}
function emit(detail:string){window.dispatchEvent(new CustomEvent("bunya-driver-data",{detail}))}
function read<T>(key:string,fallback:T):T{if(typeof window==="undefined")return structuredClone(fallback);try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw) as T:structuredClone(fallback)}catch{return structuredClone(fallback)}}
function write<T>(key:string,value:T){localStorage.setItem(key,JSON.stringify(value,(field,nested)=>field==="plainCode"||field==="password"?undefined:nested))}
