"use client";
import type {ContractorOpportunity} from "./contractor-types";
import type {AdminCommentReview,ContractorProjectComment,CustomerProjectChangeRequest,CustomerProjectRequest,PlatformPolicy,PolicyAcceptance,ProjectAuditEntry,ProjectNotification} from "./project-request-types";
import {adminCommentReviewsMock,contractorProjectCommentsMock,customerProjectChangeRequestsMock,customerProjectRequestsMock,policyAcceptancesMock,projectAuditMock,projectNotificationsMock,projectPoliciesMock} from "./project-request-data";
import {contractorId,readContractor,writeContractor} from "./contractor-storage";

export const projectStorageKeys={requests:"bunya-customer-project-requests",opportunities:"bunya-contractor-opportunities",comments:"bunya-contractor-project-comments",reviews:"bunya-admin-project-comment-reviews",changes:"bunya-customer-project-change-requests",policies:"bunya-platform-policies",acceptances:"bunya-policy-acceptances",notifications:"bunya-project-notifications",audit:"bunya-project-audit-log"} as const;
type ProjectStore={requests:CustomerProjectRequest[];comments:ContractorProjectComment[];reviews:AdminCommentReview[];changes:CustomerProjectChangeRequest[];policies:PlatformPolicy[];acceptances:PolicyAcceptance[];notifications:ProjectNotification[];audit:ProjectAuditEntry[]};
const defaults:ProjectStore={requests:customerProjectRequestsMock,comments:contractorProjectCommentsMock,reviews:adminCommentReviewsMock,changes:customerProjectChangeRequestsMock,policies:projectPoliciesMock,acceptances:policyAcceptancesMock,notifications:projectNotificationsMock,audit:projectAuditMock};
export function readProjectStore<Key extends keyof ProjectStore>(key:Key):ProjectStore[Key]{return read(projectStorageKeys[key],defaults[key])}
export function writeProjectStore<Key extends keyof ProjectStore>(key:Key,value:ProjectStore[Key]){write(projectStorageKeys[key],value);window.dispatchEvent(new CustomEvent("bunya-project-cycle",{detail:key}))}
export function createProjectCycleId(prefix:string){return typeof crypto!=="undefined"&&"randomUUID"in crypto?`${prefix}-${crypto.randomUUID()}`:`${prefix}-${Date.now()}`}
export function projectDuration(request:CustomerProjectRequest){const labels={day:"يوم",week:"أسبوع",month:"شهر",year:"سنة",other:request.customDurationUnit||"وحدة"};return `${request.durationValue} ${labels[request.durationUnit]}`}
export function toContractorOpportunity(request:CustomerProjectRequest):ContractorOpportunity{return{id:request.id,opportunityCode:request.requestCode,title:request.title,projectType:request.otherProjectType||request.projectType,description:request.description,requiredSpecialties:request.requiredSpecialties,region:request.region,city:request.city,scope:request.scope,quantityLabel:request.technical.area?`${request.technical.area} ${request.technical.areaUnit||"م²"}`:undefined,estimatedBudgetMin:request.budgetMin??request.budgetMax,estimatedBudgetMax:request.budgetMax,expectedStartAt:request.expectedStartAt,estimatedDuration:projectDuration(request),deadlineAt:request.proposalDeadlineAt,customerLabel:"هوية العميل محمية بواسطة بُنية",mapsUrl:request.mapsUrl,terms:[request.technical.qualitySafety||"الالتزام بمتطلبات الجودة والسلامة",request.technical.requiresInspection?"يتطلب معاينة للموقع":"المعاينة غير إلزامية",`المواد: ${request.technical.materialsResponsibility}`],documents:request.attachments.map(file=>({id:file.id,name:file.name,type:file.type,size:file.size})),status:"new",createdAt:request.publishedAt??request.createdAt}}
export function syncPublishedOpportunity(request:CustomerProjectRequest){const opportunities=readContractor("opportunities");const allowed=request.status==="published"||request.status==="receiving_proposals";const next=allowed?[toContractorOpportunity(request),...opportunities.filter(item=>item.id!==request.id)]:opportunities.filter(item=>item.id!==request.id);writeContractor("opportunities",next)}
export function publishProjectRequest(id:string){const now=new Date().toISOString();const requests=readProjectStore("requests");const request=requests.find(item=>item.id===id);if(!request)return;const next={...request,status:"receiving_proposals" as const,publishedAt:now,updatedAt:now,adminNote:undefined};writeProjectStore("requests",requests.map(item=>item.id===id?next:item));syncPublishedOpportunity(next);addProjectNotification({recipientRole:"contractor",projectRequestId:id,type:"new_opportunity",title:"فرصة مشروع جديدة",message:`فرصة ${next.requestCode} أصبحت متاحة للمقاولين المؤهلين.`,link:`/contractor/opportunities/${id}`});addProjectNotification({recipientRole:"customer",recipientId:request.customerId,projectRequestId:id,type:"published",title:"تم نشر طلب المشروع",message:"اجتاز الطلب مراجعة بُنية وبدأ استقبال العروض.",link:`/customer/project-requests/${id}`});addProjectAudit(id,"admin","مراجع بُنية","اعتماد الطلب ونشره")}
export function acceptPolicy(policyId:string,userRole:PolicyAcceptance["userRole"],contextType:PolicyAcceptance["contextType"],contextId:string){const policy=readProjectStore("policies").find(item=>item.id===policyId);if(!policy)throw new Error("السياسة غير متاحة");const acceptance:PolicyAcceptance={id:createProjectCycleId("policy-acceptance"),policyId,policyVersion:policy.version,userRole,contextType,contextId,acceptedAt:new Date().toISOString()};writeProjectStore("acceptances",[acceptance,...readProjectStore("acceptances")]);return acceptance}
export function addProjectNotification(value:Omit<ProjectNotification,"id"|"read"|"createdAt">){const item:ProjectNotification={...value,id:createProjectCycleId("project-notification"),read:false,createdAt:new Date().toISOString()};writeProjectStore("notifications",[item,...readProjectStore("notifications")])}
export function addProjectAudit(projectRequestId:string,actorRole:ProjectAuditEntry["actorRole"],actorLabel:string,action:string,reason?:string,oldValue?:ProjectAuditEntry["oldValue"],newValue?:ProjectAuditEntry["newValue"]){const entry:ProjectAuditEntry={id:createProjectCycleId("project-audit"),projectRequestId,actorRole,actorLabel,action,reason,oldValue,newValue,createdAt:new Date().toISOString()};writeProjectStore("audit",[entry,...readProjectStore("audit")])}
export function ensurePublishedOpportunities(){for(const request of readProjectStore("requests")){if(request.status==="published"||request.status==="receiving_proposals")syncPublishedOpportunity(request)}}
export function createCommentOpportunityId(){return contractorId("comment")}
function read<T>(key:string,fallback:T):T{if(typeof window==="undefined")return structuredClone(fallback);try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw) as T:structuredClone(fallback)}catch{return structuredClone(fallback)}}
function write<T>(key:string,value:T){localStorage.setItem(key,JSON.stringify(value,(field,nested)=>field==="previewUrl"?undefined:nested))}
