import type {AdminCommentReview,ContractorProjectComment,CustomerProjectChangeRequest,CustomerProjectRequest,PolicyAcceptance,ProjectAuditEntry,ProjectNotification} from "./project-request-types";
import {platformProjectPolicies} from "./project-policies";

export const customerProjectRequestsMock:CustomerProjectRequest[]=[{id:"project-request-1701",requestCode:"BPR-01701",customerId:"customer-demo",title:"تشطيب وتجهيز فيلا سكنية",projectType:"تشطيب",description:"تشطيب داخلي متكامل لفيلا سكنية مع تنسيق الأعمال الكهربائية والسباكة.",scope:"الأرضيات والأسقف والدهانات والأبواب والأعمال الكهربائية والسباكة النهائية.",requiredSpecialties:["تشطيبات","إشراف هندسي"],region:"شمال الرياض",city:"الرياض",mapsUrl:"https://www.google.com/maps?q=24.82,46.65",latitude:24.82,longitude:46.65,locationName:"مشروع فيلا شمال الرياض",accessDescription:"مدخل الموقع من الطريق الفرعي الشرقي.",budgetMin:600000,budgetMax:780000,budgetNegotiable:true,durationValue:7,durationUnit:"month",expectedStartAt:"2026-09-01",proposalDeadlineAt:"2026-08-05T18:00:00.000Z",technical:{area:720,areaUnit:"م²",floors:3,siteCondition:"الهيكل مكتمل",preferredMaterials:"مواد متوسطة إلى فاخرة",qualitySafety:"خطة سلامة وتقارير جودة أسبوعية",requiresInspection:true,hasLicense:true,hasOfficialApprovals:true,materialsResponsibility:"contractor",workerAccommodationTransport:"على المقاول",additionalNotes:"التنفيذ المرحلي حسب الأدوار."},attachments:[{id:"pra-1",name:"مخطط-معماري.pdf",type:"application/pdf",size:820000,category:"architectural"},{id:"pra-2",name:"صور-الموقع.zip",type:"application/zip",size:1400000,category:"site_photos"}],status:"receiving_proposals",proposalCount:2,approvedCommentCount:0,createdAt:"2026-07-15T09:00:00.000Z",updatedAt:"2026-07-16T08:00:00.000Z",submittedAt:"2026-07-15T09:30:00.000Z",publishedAt:"2026-07-16T08:00:00.000Z"}];
export const contractorProjectCommentsMock:ContractorProjectComment[]=[];
export const adminCommentReviewsMock:AdminCommentReview[]=[];
export const customerProjectChangeRequestsMock:CustomerProjectChangeRequest[]=[];
export const policyAcceptancesMock:PolicyAcceptance[]=[];
export const projectNotificationsMock:ProjectNotification[]=[{id:"pn-1",recipientRole:"contractor",projectRequestId:"project-request-1701",type:"new_opportunity",title:"فرصة مشروع جديدة",message:"فرصة مطابقة للتشطيبات في الرياض.",link:"/contractor/opportunities/project-request-1701",read:false,createdAt:"2026-07-16T08:00:00.000Z"}];
export const projectAuditMock:ProjectAuditEntry[]=[{id:"pa-1",projectRequestId:"project-request-1701",actorRole:"admin",actorLabel:"مراجع بُنية",action:"نشر طلب المشروع",createdAt:"2026-07-16T08:00:00.000Z"}];
export const projectPoliciesMock=platformProjectPolicies;
