import "server-only";
import type {ContractorProfile} from "@/lib/bunya-types";
import{createClient}from"@/lib/supabase/server";
import{createAdminClient}from"@/lib/supabase/admin";

type Media={storage_path:string;mime_type:string;is_primary:boolean;sort_order:number};
export async function loadPublicContractors():Promise<ContractorProfile[]>{const supabase=await createClient();const profiles=await supabase.from("contractor_profiles").select("id,display_name,commercial_name,city,badge,years_experience,summary,phone,email,subscription_active,approval_status").eq("approval_status","approved").eq("subscription_active",true).eq("directory_visible",true).order("commercial_name");if(profiles.error)throw new Error(`تعذر تحميل دليل المقاولين: ${profiles.error.message}`);const rows=profiles.data??[],ids=rows.map(row=>row.id);if(!ids.length)return[];
 const[services,portfolio]=await Promise.all([supabase.from("contractor_services").select("contractor_profile_id,title,primary_specialty").in("contractor_profile_id",ids).eq("review_status","approved").eq("is_active",true).is("deleted_at",null),supabase.from("contractor_portfolio_items").select("id,profile_id,title,sort_order,contractor_portfolio_media(storage_path,mime_type,is_primary,sort_order)").in("profile_id",ids).eq("is_visible",true).eq("review_status","approved").is("deleted_at",null).order("sort_order")]);if(services.error)throw new Error(`تعذر تحميل خدمات المقاولين: ${services.error.message}`);if(portfolio.error)throw new Error(`تعذر تحميل أعمال المقاولين: ${portfolio.error.message}`);
 const admin=createAdminClient(),signed=new Map<string,string>();await Promise.all((portfolio.data??[]).flatMap(item=>((item.contractor_portfolio_media as unknown as Media[])??[]).sort(mediaSort).slice(0,1).map(async media=>{const result=await admin.storage.from("contractor-portfolio").createSignedUrl(media.storage_path,300);if(result.data?.signedUrl)signed.set(media.storage_path,result.data.signedUrl)})));
 return rows.map(row=>({id:row.id,displayName:row.display_name,commercialName:row.commercial_name,city:row.city??"غير محدد",badge:row.badge??"مقاول معتمد",serviceTypes:Array.from(new Set((services.data??[]).filter(item=>item.contractor_profile_id===row.id).map(item=>item.title))),yearsExperience:row.years_experience??0,summary:row.summary??"لم يضف المقاول نبذة مهنية بعد.",workItems:(portfolio.data??[]).filter(item=>item.profile_id===row.id).slice(0,3).map(item=>{const media=((item.contractor_portfolio_media as unknown as Media[])??[]).sort(mediaSort)[0];return{title:item.title,mediaUrl:media?signed.get(media.storage_path)??null:null,mimeType:media?.mime_type??null}}),phone:row.phone,email:row.email,subscriptionActive:row.subscription_active,approvalStatus:"approved" as const}))}
function mediaSort(a:Media,b:Media){return Number(b.is_primary)-Number(a.is_primary)||a.sort_order-b.sort_order}
