"use client";
import type {ReactNode} from "react";
import Link from "next/link";
export const money=(value:number)=>new Intl.NumberFormat("ar-SA",{style:"currency",currency:"SAR",maximumFractionDigits:2}).format(value);
export const customerDate=(value:string)=>new Intl.DateTimeFormat("ar-SA",{day:"numeric",month:"short",year:"numeric"}).format(new Date(value));
const labels:Record<string,string>={draft:"مسودة",pending_admin_review:"بانتظار مراجعة الإدارة",needs_customer_changes:"يحتاج تعديلًا",published:"منشور",receiving_proposals:"يستقبل عروضًا",under_customer_review:"قيد مراجعتك",awarded:"تم الإسناد",pending_customer_decision:"بانتظار قرارك",accepted_by_customer:"تم قبول التعديل",rejected_by_customer:"تم رفض التعديل",customer_requested_clarification:"طُلب توضيح",submitted:"تم الإرسال",sourcing:"جارٍ البحث عن أفضل سعر",verifying:"جارٍ التحقق من التوفر والتوصيل",quote_ready:"عرض بُنية جاهز",customer_review:"بانتظار قرارك",accepted:"تم الاعتماد",expired:"منتهي",cancelled:"ملغي",new:"جديد",reviewing:"قيد المراجعة",ready:"جاهز للمراجعة",approved:"تم الاعتماد",rejected:"تم الرفض",confirmed:"مؤكد",pending_payment:"بانتظار الدفع",preparing:"قيد التجهيز",ready_for_pickup:"جاهز للاستلام",assigned_driver:"تم إسناده لسائق",out_for_delivery:"خرج للتوصيل",delivered:"تم التسليم",completed:"مكتمل",unpaid:"غير مدفوعة",paid:"مدفوعة Mock",refunded:"مسترجعة",assigned:"تم الإسناد",open:"مفتوحة",in_progress:"قيد المعالجة",resolved:"محلولة"};
export function CustomerStatus({value}:{value:string}){const good=["approved","accepted","paid","delivered","completed","resolved"].includes(value);const bad=["rejected","expired","cancelled","refunded"].includes(value);return <span className={`customer-status ${good?"success":bad?"danger":["new","submitted","confirmed","out_for_delivery","quote_ready","customer_review","ready"].includes(value)?"info":"warning"}`}>{labels[value]??value}</span>}
export function CustomerHeader({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:ReactNode}){return <header className="customer-page-header"><div><p>{eyebrow}</p><h2>{title}</h2><span>{description}</span></div>{action}</header>}
export function CustomerEmpty({title,description,href,action}:{title:string;description:string;href?:string;action?:string}){return <div className="customer-empty"><span>◇</span><h3>{title}</h3><p>{description}</p>{href&&action?<Link className="customer-primary" href={href}>{action}</Link>:null}</div>}
export function CustomerToast({message,tone="success"}:{message:string;tone?:"success"|"error"}){return message?<div role="status" className={`customer-toast ${tone}`}>{tone==="success"?"✓":"!"} {message}</div>:null}
export function CustomerConfirm({title,description,onConfirm,onCancel}:{title:string;description:string;onConfirm:()=>void;onCancel:()=>void}){return <div className="customer-modal-backdrop" onMouseDown={onCancel}><section className="customer-modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><span>!</span><h3>{title}</h3><p>{description}</p><footer><button className="customer-secondary" onClick={onCancel}>تراجع</button><button className="customer-primary" onClick={onConfirm}>تأكيد</button></footer></section></div>}
