import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

const supportedBunyaLocales = <Locale>[
  Locale('ar'),
  Locale('en'),
  Locale('ur'),
  Locale('hi'),
  Locale('bn'),
  Locale('fil'),
];

const bunyaLanguageNames = <String, String>{
  'ar': 'العربية',
  'en': 'English',
  'ur': 'اردو',
  'hi': 'हिन्दी',
  'bn': 'বাংলা',
  'fil': 'Filipino',
};

abstract final class BunyaLocaleController {
  static const _preferenceKey = 'bunya_locale';
  static final locale = ValueNotifier<Locale>(const Locale('ar'));

  static Future<void> initialize() async {
    final saved = (await SharedPreferences.getInstance()).getString(
      _preferenceKey,
    );
    if (saved != null && bunyaLanguageNames.containsKey(saved)) {
      locale.value = Locale(saved);
    }
  }

  static Future<void> change(String code) async {
    if (!bunyaLanguageNames.containsKey(code)) return;
    await (await SharedPreferences.getInstance()).setString(
      _preferenceKey,
      code,
    );
    try {
      final client = Supabase.instance.client;
      final user = client.auth.currentUser;
      if (user != null) {
        await client
            .from('profiles')
            .update({'preferred_locale': code})
            .eq('id', user.id)
            .timeout(const Duration(seconds: 4));
      }
    } catch (_) {
      // Local persistence remains available while offline.
    } finally {
      // Rebuild after the profile update so localized RPC payloads use the
      // same locale as the visible interface on their first request.
      locale.value = Locale(code);
    }
  }

  static Future<void> adoptProfileLocale(String? code) async {
    if (code == null || !bunyaLanguageNames.containsKey(code)) return;
    locale.value = Locale(code);
    await (await SharedPreferences.getInstance()).setString(
      _preferenceKey,
      code,
    );
  }
}

const _messages = <String, Map<String, String>>{
  'ar': {
    'paySecurely': 'الدفع الآمن عبر Paymob',
    'acceptAndPay': 'قبول العرض والمتابعة للدفع',
    'paymentOpening': 'جاري فتح صفحة الدفع الآمنة...',
    'paymentStartFailed': 'تعذر بدء الدفع الآن. حاول مجددًا بعد قليل.',
    'paymentSucceeded': 'تم الدفع بنجاح وتحديث الطلب.',
    'language': 'اللغة',
    'chooseLanguage': 'اختر اللغة',
    'home': 'الرئيسية',
    'products': 'المنتجات',
    'pricing': 'التسعير',
    'deliveries': 'التوصيلات',
    'services': 'الخدمات',
    'notifications': 'الإشعارات',
    'account': 'الحساب',
    'homeNav': 'الرئيسية',
    'pricingNav': 'التسعير',
    'deliveriesNav': 'التوصيل',
    'servicesNav': 'الخدمات',
    'notificationsNav': 'التنبيهات',
    'accountNav': 'الحساب',
    'approvalsNav': 'الاعتمادات',
    'opportunitiesNav': 'الفرص',
    'adminPortal': 'لوحة الإدارة',
    'providerPortal': 'لوحة المزود',
    'contractorPortal': 'لوحة المقاول',
    'driverPortal': 'لوحة السائق',
    'bunyaAccount': 'حساب بُنية',
    'adminWelcome': 'المنصة تحت سيطرتك',
    'adminWelcomeCaption': 'راقب، اعتمد، وتابع التشغيل من التطبيق.',
    'providerWelcome': 'حوّل الطلبات إلى مبيعات',
    'providerWelcomeCaption': 'استلم طلب التسعير ونفّذ التوريد والتوصيل.',
    'contractorWelcome': 'فرصك ومشاريعك في مكان واحد',
    'contractorWelcomeCaption': 'استلم الفرص وقدّم العروض وتابع التنفيذ.',
    'driverWelcome': 'توصيلاتك واضحة خطوة بخطوة',
    'driverWelcomeCaption':
        'راجع الموقع وسجّل الرحلة وأثبت التسليم برمز العميل.',
    'activeTasks': 'المهام النشطة',
    'arrivedAtSite': 'وصلت للموقع',
    'deliveredCount': 'تم تسليمها',
    'pricingRequests': 'طلبات التسعير',
    'supplyOrders': 'أوامر التوريد',
    'opportunities': 'الفرص',
    'offers': 'العروض',
    'projects': 'المشاريع',
    'providerApplications': 'طلبات المزودين',
    'contractorApplications': 'طلبات المقاولين',
    'productReviews': 'مراجعة المنتجات',
    'liveConnectedData': 'بيانات حية ومتصلة',
    'liveConnectedDataCaption':
        'تُحفظ كل مهمة وإجراء بأمان، وتظهر تحديثاتهما مباشرة في الإشعارات.',
    'operationsAndServices': 'الخدمات والعمليات',
    'operationsAndServicesCaption': 'كل وحدات دورك في مكان واحد.',
    'notificationsCaption': 'التسعير والاستلام والتنفيذ والقرارات.',
    'noNotifications': 'لا توجد إشعارات حاليًا',
    'notificationDetails': 'تفاصيل الإشعار',
    'bunyaAlert': 'تنبيه من منصة بُنية',
    'read': 'مقروء',
    'new': 'جديد',
    'name': 'الاسم',
    'email': 'البريد',
    'mobile': 'الجوال',
    'role': 'الدور',
    'notAdded': 'غير مضاف',
    'resetPassword': 'إعادة تعيين كلمة المرور',
    'noRecords': 'لا توجد سجلات حاليًا',
    'deliverySitesAndStatus': 'المواقع وحالة الاستلام والتسليم',
    'updateHistory': 'سجل التحديثات',
    'recordedDeliveryTransitions': 'كل انتقالات التوصيل المسجلة',
    'logout': 'تسجيل الخروج',
    'cancel': 'إلغاء',
    'deliveryTasks': 'مهام التوصيل',
    'deliveryTasksCaption':
        'راجع الموقع والبيانات، وسجّل كل خطوة حتى رمز التسليم.',
    'noAssignedTasks':
        'لا توجد مهام مسندة. تظهر المهمة هنا بعد إسنادها لك من المزود.',
    'activeDeliveries': 'الطلبات النشطة',
    'completedDeliveries': 'الطلبات المكتملة',
    'noActiveDeliveries': 'لا توجد طلبات توصيل نشطة حاليًا.',
    'noCompletedDeliveries': 'لا توجد طلبات مكتملة حتى الآن.',
    'tapForDetails': 'اضغط لعرض التفاصيل',
    'deliveryStatusUpdated': 'تم تحديث حالة التوصيل وحفظها.',
    'recipient': 'المستلم',
    'siteResponsible': 'مسؤول الموقع',
    'deliveryContacts': 'جهات التواصل للتسليم',
    'siteReadiness': 'الموقع وتجهيز الاستلام',
    'workingHours': 'مواعيد العمل',
    'loadingUnloading': 'التحميل والتنزيل',
    'roadAccess': 'سهولة الوصول',
    'accessInstructions': 'تعليمات الوصول',
    'openGoogleMaps': 'فتح موقع التسليم في Google Maps',
    'callRecipient': 'اتصال بالمستلم',
    'callSiteResponsible': 'اتصال بمسؤول الموقع',
    'callFailed': 'تعذر فتح الاتصال. تحقق من إعدادات الهاتف.',
    'mapsFailed': 'تعذر فتح Google Maps على هذا الهاتف.',
    'pickedUpFromProvider': 'تم الاستلام من المزود',
    'outForDelivery': 'خرجت للتوصيل',
    'arrivedCustomer': 'وصلت إلى العميل',
    'deliveryFailed': 'تعذر التوصيل',
    'customerDeliveryCode': 'رمز التسليم من العميل',
    'deliveryCodeWarning': 'لا تطلب الرمز قبل تسليم كامل البضاعة.',
    'customerCode': 'رمز العميل',
    'confirmAndClose': 'تأكيد التسليم وإغلاق الطلب',
    'enterDeliveryCode': 'أدخل رمز التسليم الذي يقدمه العميل.',
    'deliveryCompleted': 'تم إثبات التسليم وإغلاق الطلب بنجاح.',
    'invalidDeliveryCode': 'الرمز غير صحيح أو منتهي أو تم قفل المحاولات.',
    'confirmLogout': 'هل تريد تسجيل الخروج من حساب السائق؟',
    'welcomeBack': 'مرحبًا بعودتك',
    'loginCaption': 'سجّل دخولك لإدارة مشروعك من بُنية',
    'emailOrPhone': 'البريد الإلكتروني أو رقم الجوال',
    'password': 'كلمة المرور',
    'forgotPassword': 'نسيت كلمة المرور؟',
    'signIn': 'تسجيل الدخول',
    'orderItems': 'منتجات الطلب',
    'quantity': 'الكمية',
    'unit': 'الوحدة',
    'measurement': 'القياس',
    'myRequests': 'طلباتي',
    'myAccount': 'حسابي',
    'quoteRequest': 'طلب عرض السعر',
  },
  'en': {
    'paySecurely': 'Pay securely with Paymob',
    'acceptAndPay': 'Accept quote and continue to payment',
    'paymentOpening': 'Opening secure checkout...',
    'paymentStartFailed':
        'Payment could not be started. Please try again shortly.',
    'paymentSucceeded': 'Payment completed and the order was updated.',
    'language': 'Language',
    'chooseLanguage': 'Choose language',
    'home': 'Home',
    'products': 'Products',
    'pricing': 'Pricing',
    'deliveries': 'Deliveries',
    'services': 'Services',
    'notifications': 'Notifications',
    'account': 'Account',
    'homeNav': 'Home',
    'pricingNav': 'Pricing',
    'deliveriesNav': 'Delivery',
    'servicesNav': 'Services',
    'notificationsNav': 'Alerts',
    'accountNav': 'Account',
    'approvalsNav': 'Reviews',
    'opportunitiesNav': 'Jobs',
    'adminPortal': 'Admin portal',
    'providerPortal': 'Provider portal',
    'contractorPortal': 'Contractor portal',
    'driverPortal': 'Driver portal',
    'bunyaAccount': 'Bunya account',
    'adminWelcome': 'Your operations at a glance',
    'adminWelcomeCaption':
        'Review approvals and track daily operations from the app.',
    'providerWelcome': 'Turn requests into sales',
    'providerWelcomeCaption':
        'Price requests, prepare orders, and manage delivery.',
    'contractorWelcome': 'Your opportunities and projects in one place',
    'contractorWelcomeCaption':
        'Review opportunities, submit proposals, and track delivery.',
    'driverWelcome': 'Every delivery, clear at every step',
    'driverWelcomeCaption': 'Review the location, record the trip, and confirm delivery with the customer code.',
    'activeTasks': 'Active tasks',
    'arrivedAtSite': 'At site',
    'deliveredCount': 'Delivered',
    'pricingRequests': 'Pricing requests',
    'supplyOrders': 'Supply orders',
    'opportunities': 'Opportunities',
    'offers': 'Offers',
    'projects': 'Projects',
    'providerApplications': 'Provider applications',
    'contractorApplications': 'Contractor applications',
    'productReviews': 'Product reviews',
    'liveConnectedData': 'Live, connected updates',
    'liveConnectedDataCaption': 'Every task and action is stored securely, with updates shown directly in notifications.',
    'operationsAndServices': 'Services and operations',
    'operationsAndServicesCaption': 'All tools for your role in one place.',
    'notificationsCaption': 'Pricing, receiving, fulfillment, and decisions.',
    'noNotifications': 'No notifications yet',
    'notificationDetails': 'Notification details',
    'bunyaAlert': 'Alert from Bunya',
    'read': 'Read',
    'new': 'New',
    'name': 'Name',
    'email': 'Email',
    'mobile': 'Mobile',
    'role': 'Role',
    'notAdded': 'Not provided',
    'resetPassword': 'Reset password',
    'noRecords': 'No records yet',
    'deliverySitesAndStatus': 'Locations, collection, and delivery status',
    'updateHistory': 'Update history',
    'recordedDeliveryTransitions': 'Every recorded delivery status change',
    'logout': 'Sign out',
    'cancel': 'Cancel',
    'deliveryTasks': 'Delivery tasks',
    'deliveryTasksCaption': 'Review the location and details, and record every step through the delivery code.',
    'noAssignedTasks': 'No tasks are assigned. A task appears here after the provider assigns it to you.',
    'activeDeliveries': 'Active deliveries',
    'completedDeliveries': 'Completed deliveries',
    'noActiveDeliveries': 'There are no active delivery tasks right now.',
    'noCompletedDeliveries': 'There are no completed deliveries yet.',
    'tapForDetails': 'Tap to view details',
    'deliveryStatusUpdated': 'The delivery status was updated and saved.',
    'recipient': 'Recipient',
    'siteResponsible': 'Site contact',
    'deliveryContacts': 'Delivery contacts',
    'siteReadiness': 'Site and handling details',
    'workingHours': 'Working hours',
    'loadingUnloading': 'Loading and unloading',
    'roadAccess': 'Road accessibility',
    'accessInstructions': 'Access instructions',
    'openGoogleMaps': 'Open delivery location in Google Maps',
    'callRecipient': 'Call recipient',
    'callSiteResponsible': 'Call site contact',
    'callFailed': 'Could not open the phone app. Check the phone settings.',
    'mapsFailed': 'Could not open Google Maps on this phone.',
    'pickedUpFromProvider': 'Collected from provider',
    'outForDelivery': 'Start delivery',
    'arrivedCustomer': 'Arrived at customer',
    'deliveryFailed': 'Delivery failed',
    'customerDeliveryCode': 'Customer delivery code',
    'deliveryCodeWarning':
        'Do not request the code before delivering the complete shipment.',
    'customerCode': 'Customer code',
    'confirmAndClose': 'Confirm delivery and close order',
    'enterDeliveryCode': 'Enter the delivery code provided by the customer.',
    'deliveryCompleted':
        'Delivery confirmed and the order was closed successfully.',
    'invalidDeliveryCode':
        'The code is incorrect, expired, or attempts are locked.',
    'confirmLogout': 'Do you want to sign out of the driver account?',
    'welcomeBack': 'Welcome back',
    'loginCaption': 'Sign in to manage your project with Bunya',
    'emailOrPhone': 'Email or mobile number',
    'password': 'Password',
    'forgotPassword': 'Forgot your password?',
    'signIn': 'Sign in',
    'orderItems': 'Order items',
    'quantity': 'Quantity',
    'unit': 'Unit',
    'measurement': 'Measurement',
    'myRequests': 'My requests',
    'myAccount': 'My account',
    'quoteRequest': 'Request a quote',
  },
  'ur': {
    'paySecurely': 'Paymob کے ذریعے محفوظ ادائیگی',
    'acceptAndPay': 'کوٹیشن قبول کریں اور ادائیگی کریں',
    'paymentOpening': 'محفوظ ادائیگی کا صفحہ کھولا جا رہا ہے...',
    'paymentStartFailed': 'ادائیگی شروع نہیں ہوسکی۔ دوبارہ کوشش کریں۔',
    'paymentSucceeded': 'ادائیگی کامیاب اور آرڈر اپ ڈیٹ ہوگیا۔',
    'language': 'زبان',
    'chooseLanguage': 'زبان منتخب کریں',
    'home': 'ہوم',
    'products': 'مصنوعات',
    'pricing': 'قیمت لگانا',
    'deliveries': 'ڈیلیوریز',
    'services': 'خدمات',
    'notifications': 'اطلاعات',
    'account': 'اکاؤنٹ',
    'homeNav': 'ہوم',
    'pricingNav': 'قیمتیں',
    'deliveriesNav': 'ڈیلیوری',
    'servicesNav': 'خدمات',
    'notificationsNav': 'اطلاعات',
    'accountNav': 'اکاؤنٹ',
    'approvalsNav': 'جائزے',
    'opportunitiesNav': 'مواقع',
    'adminPortal': 'انتظامیہ پورٹل',
    'providerPortal': 'فراہم کنندہ پورٹل',
    'contractorPortal': 'ٹھیکیدار پورٹل',
    'driverPortal': 'ڈرائیور پورٹل',
    'bunyaAccount': 'بُنیہ اکاؤنٹ',
    'adminWelcome': 'تمام کام ایک نظر میں',
    'adminWelcomeCaption':
        'منظوریاں دیکھیں اور ایپ سے روزمرہ کام کی نگرانی کریں۔',
    'providerWelcome': 'درخواستوں کو فروخت میں بدلیں',
    'providerWelcomeCaption': 'قیمت دیں، آرڈر تیار کریں اور ڈیلیوری سنبھالیں۔',
    'contractorWelcome': 'مواقع اور منصوبے ایک جگہ',
    'contractorWelcomeCaption':
        'مواقع دیکھیں، پیشکشیں دیں اور کام کی پیش رفت دیکھیں۔',
    'driverWelcome': 'ہر ڈیلیوری، ہر مرحلے پر واضح',
    'driverWelcomeCaption': 'مقام دیکھیں، سفر ریکارڈ کریں اور گاہک کے کوڈ سے ڈیلیوری کی تصدیق کریں۔',
    'activeTasks': 'فعال کام',
    'arrivedAtSite': 'مقام پر پہنچے',
    'deliveredCount': 'ڈیلیور شدہ',
    'pricingRequests': 'قیمت کی درخواستیں',
    'supplyOrders': 'سپلائی آرڈرز',
    'opportunities': 'مواقع',
    'offers': 'پیشکشیں',
    'projects': 'منصوبے',
    'providerApplications': 'فراہم کنندہ درخواستیں',
    'contractorApplications': 'ٹھیکیدار درخواستیں',
    'productReviews': 'مصنوعات کا جائزہ',
    'liveConnectedData': 'براہ راست مربوط معلومات',
    'liveConnectedDataCaption': 'ہر کام اور کارروائی محفوظ رہتی ہے، اور اس کی تازہ خبر براہ راست اطلاعات میں آتی ہے۔',
    'operationsAndServices': 'خدمات اور کارروائیاں',
    'operationsAndServicesCaption': 'آپ کے کردار کے تمام اوزار ایک جگہ۔',
    'notificationsCaption': 'قیمت، وصولی، تکمیل اور فیصلے۔',
    'noNotifications': 'ابھی کوئی اطلاع نہیں',
    'notificationDetails': 'اطلاع کی تفصیل',
    'bunyaAlert': 'بُنیہ کی اطلاع',
    'read': 'پڑھی گئی',
    'new': 'نئی',
    'name': 'نام',
    'email': 'ای میل',
    'mobile': 'موبائل',
    'role': 'کردار',
    'notAdded': 'درج نہیں',
    'resetPassword': 'پاس ورڈ دوبارہ مقرر کریں',
    'noRecords': 'ابھی کوئی ریکارڈ نہیں',
    'deliverySitesAndStatus': 'مقامات، وصولی اور ڈیلیوری کی حالت',
    'updateHistory': 'تازہ کاریوں کا ریکارڈ',
    'recordedDeliveryTransitions': 'ڈیلیوری کی تمام محفوظ شدہ حالتیں',
    'logout': 'لاگ آؤٹ',
    'cancel': 'منسوخ کریں',
    'deliveryTasks': 'ڈیلیوری کے کام',
    'deliveryTasksCaption': 'مقام اور تفصیلات کا جائزہ لیں، اور ڈیلیوری کوڈ تک ہر مرحلہ ریکارڈ کریں۔',
    'noAssignedTasks': 'کوئی کام تفویض نہیں ہوا۔ فراہم کنندہ کے تفویض کرنے کے بعد کام یہاں نظر آئے گا۔',
    'activeDeliveries': 'فعال ڈیلیوریز',
    'completedDeliveries': 'مکمل ڈیلیوریز',
    'noActiveDeliveries': 'اس وقت کوئی فعال ڈیلیوری موجود نہیں۔',
    'noCompletedDeliveries': 'ابھی کوئی مکمل ڈیلیوری موجود نہیں۔',
    'tapForDetails': 'تفصیلات دیکھنے کے لیے دبائیں',
    'deliveryStatusUpdated': 'ڈیلیوری کی حالت اپ ڈیٹ اور محفوظ ہو گئی۔',
    'recipient': 'وصول کنندہ',
    'siteResponsible': 'سائٹ کا ذمہ دار',
    'deliveryContacts': 'ڈیلیوری کے رابطے',
    'siteReadiness': 'سائٹ اور سامان سنبھالنے کی تفصیلات',
    'workingHours': 'کام کے اوقات',
    'loadingUnloading': 'لوڈنگ اور اَن لوڈنگ',
    'roadAccess': 'راستے تک رسائی',
    'accessInstructions': 'رسائی کی ہدایات',
    'openGoogleMaps': 'Google Maps میں ڈیلیوری کا مقام کھولیں',
    'callRecipient': 'وصول کنندہ کو کال کریں',
    'callSiteResponsible': 'سائٹ کے ذمہ دار کو کال کریں',
    'callFailed': 'فون ایپ نہیں کھل سکی۔ فون کی ترتیبات چیک کریں۔',
    'mapsFailed': 'اس فون پر Google Maps نہیں کھل سکا۔',
    'pickedUpFromProvider': 'فراہم کنندہ سے سامان لے لیا',
    'outForDelivery': 'ڈیلیوری شروع کریں',
    'arrivedCustomer': 'گاہک کے پاس پہنچ گیا',
    'deliveryFailed': 'ڈیلیوری ناکام',
    'customerDeliveryCode': 'گاہک کا ڈیلیوری کوڈ',
    'deliveryCodeWarning': 'مکمل سامان حوالے کرنے سے پہلے کوڈ نہ مانگیں۔',
    'customerCode': 'گاہک کا کوڈ',
    'confirmAndClose': 'ڈیلیوری کی تصدیق اور آرڈر بند کریں',
    'enterDeliveryCode': 'گاہک کا دیا ہوا ڈیلیوری کوڈ درج کریں۔',
    'deliveryCompleted':
        'ڈیلیوری کی تصدیق ہو گئی اور آرڈر کامیابی سے بند ہو گیا۔',
    'invalidDeliveryCode': 'کوڈ غلط، میعاد ختم، یا کوششیں مقفل ہیں۔',
    'confirmLogout': 'کیا آپ ڈرائیور اکاؤنٹ سے لاگ آؤٹ کرنا چاہتے ہیں؟',
    'welcomeBack': 'خوش آمدید',
    'loginCaption': 'بُنیہ کے ساتھ اپنا پراجیکٹ سنبھالنے کے لیے لاگ اِن کریں',
    'emailOrPhone': 'ای میل یا موبائل نمبر',
    'password': 'پاس ورڈ',
    'forgotPassword': 'پاس ورڈ بھول گئے؟',
    'signIn': 'لاگ اِن',
    'orderItems': 'آرڈر کی مصنوعات',
    'quantity': 'مقدار',
    'unit': 'اکائی',
    'measurement': 'پیمائش',
    'myRequests': 'میری درخواستیں',
    'myAccount': 'میرا اکاؤنٹ',
    'quoteRequest': 'قیمت کی درخواست',
  },
  'hi': {
    'paySecurely': 'Paymob से सुरक्षित भुगतान',
    'acceptAndPay': 'कोटेशन स्वीकार करें और भुगतान करें',
    'paymentOpening': 'सुरक्षित भुगतान पेज खुल रहा है...',
    'paymentStartFailed': 'भुगतान शुरू नहीं हो सका। फिर प्रयास करें।',
    'paymentSucceeded': 'भुगतान सफल हुआ और ऑर्डर अपडेट हो गया।',
    'language': 'भाषा',
    'chooseLanguage': 'भाषा चुनें',
    'home': 'होम',
    'products': 'उत्पाद',
    'pricing': 'मूल्य निर्धारण',
    'deliveries': 'डिलीवरी',
    'services': 'सेवाएँ',
    'notifications': 'सूचनाएँ',
    'account': 'खाता',
    'homeNav': 'होम',
    'pricingNav': 'कीमत',
    'deliveriesNav': 'डिलीवरी',
    'servicesNav': 'सेवाएँ',
    'notificationsNav': 'सूचनाएँ',
    'accountNav': 'खाता',
    'approvalsNav': 'समीक्षा',
    'opportunitiesNav': 'अवसर',
    'adminPortal': 'प्रशासन पोर्टल',
    'providerPortal': 'प्रदाता पोर्टल',
    'contractorPortal': 'ठेकेदार पोर्टल',
    'driverPortal': 'ड्राइवर पोर्टल',
    'bunyaAccount': 'बुन्या खाता',
    'adminWelcome': 'सारा काम एक नज़र में',
    'adminWelcomeCaption':
        'स्वीकृतियों की समीक्षा करें और ऐप से रोज़मर्रा का संचालन देखें।',
    'providerWelcome': 'अनुरोधों को बिक्री में बदलें',
    'providerWelcomeCaption': 'मूल्य दें, ऑर्डर तैयार करें और डिलीवरी संभालें।',
    'contractorWelcome': 'अवसर और परियोजनाएँ एक जगह',
    'contractorWelcomeCaption':
        'अवसर देखें, प्रस्ताव दें और काम की प्रगति देखें।',
    'driverWelcome': 'हर डिलीवरी, हर चरण पर स्पष्ट',
    'driverWelcomeCaption': 'स्थान देखें, यात्रा दर्ज करें और ग्राहक के कोड से डिलीवरी की पुष्टि करें।',
    'activeTasks': 'सक्रिय कार्य',
    'arrivedAtSite': 'स्थान पर पहुँचे',
    'deliveredCount': 'डिलीवर हुए',
    'pricingRequests': 'मूल्य अनुरोध',
    'supplyOrders': 'आपूर्ति ऑर्डर',
    'opportunities': 'अवसर',
    'offers': 'प्रस्ताव',
    'projects': 'परियोजनाएँ',
    'providerApplications': 'प्रदाता आवेदन',
    'contractorApplications': 'ठेकेदार आवेदन',
    'productReviews': 'उत्पाद समीक्षा',
    'liveConnectedData': 'लाइव और जुड़ी जानकारी',
    'liveConnectedDataCaption': 'हर कार्य और कार्रवाई सुरक्षित रहती है, और उसके अपडेट सीधे सूचनाओं में दिखते हैं।',
    'operationsAndServices': 'सेवाएँ और संचालन',
    'operationsAndServicesCaption': 'आपकी भूमिका के सभी साधन एक जगह।',
    'notificationsCaption': 'मूल्य, प्राप्ति, पूर्ति और निर्णय।',
    'noNotifications': 'अभी कोई सूचना नहीं',
    'notificationDetails': 'सूचना का विवरण',
    'bunyaAlert': 'बुन्या की सूचना',
    'read': 'पढ़ी गई',
    'new': 'नई',
    'name': 'नाम',
    'email': 'ईमेल',
    'mobile': 'मोबाइल',
    'role': 'भूमिका',
    'notAdded': 'दर्ज नहीं',
    'resetPassword': 'पासवर्ड रीसेट करें',
    'noRecords': 'अभी कोई रिकॉर्ड नहीं',
    'deliverySitesAndStatus': 'स्थान, सामान लेने और डिलीवरी की स्थिति',
    'updateHistory': 'अपडेट का इतिहास',
    'recordedDeliveryTransitions': 'डिलीवरी की दर्ज की गई सभी स्थिति बदलियाँ',
    'logout': 'साइन आउट',
    'cancel': 'रद्द करें',
    'deliveryTasks': 'डिलीवरी कार्य',
    'deliveryTasksCaption':
        'स्थान और विवरण की समीक्षा करें और डिलीवरी कोड तक हर चरण दर्ज करें।',
    'noAssignedTasks': 'कोई कार्य नहीं सौंपा गया है। प्रदाता द्वारा सौंपे जाने के बाद कार्य यहाँ दिखाई देगा।',
    'activeDeliveries': 'सक्रिय डिलीवरी',
    'completedDeliveries': 'पूर्ण की गई डिलीवरी',
    'noActiveDeliveries': 'अभी कोई सक्रिय डिलीवरी नहीं है।',
    'noCompletedDeliveries': 'अभी कोई पूर्ण की गई डिलीवरी नहीं है।',
    'tapForDetails': 'विवरण देखने के लिए टैप करें',
    'deliveryStatusUpdated': 'डिलीवरी की स्थिति अपडेट होकर सहेज दी गई।',
    'recipient': 'प्राप्तकर्ता',
    'siteResponsible': 'साइट प्रभारी',
    'deliveryContacts': 'डिलीवरी संपर्क',
    'siteReadiness': 'साइट और माल संभालने का विवरण',
    'workingHours': 'काम के घंटे',
    'loadingUnloading': 'लोडिंग और अनलोडिंग',
    'roadAccess': 'सड़क की पहुँच',
    'accessInstructions': 'पहुँचने के निर्देश',
    'openGoogleMaps': 'Google Maps में डिलीवरी स्थान खोलें',
    'callRecipient': 'प्राप्तकर्ता को कॉल करें',
    'callSiteResponsible': 'साइट प्रभारी को कॉल करें',
    'callFailed': 'फ़ोन ऐप नहीं खुल सका। फ़ोन की सेटिंग जाँचें।',
    'mapsFailed': 'इस फ़ोन पर Google Maps नहीं खुल सका।',
    'pickedUpFromProvider': 'प्रदाता से सामान ले लिया',
    'outForDelivery': 'डिलीवरी शुरू करें',
    'arrivedCustomer': 'ग्राहक के पास पहुँच गया',
    'deliveryFailed': 'डिलीवरी विफल',
    'customerDeliveryCode': 'ग्राहक का डिलीवरी कोड',
    'deliveryCodeWarning': 'पूरा सामान देने से पहले कोड न माँगें।',
    'customerCode': 'ग्राहक कोड',
    'confirmAndClose': 'डिलीवरी की पुष्टि करके ऑर्डर बंद करें',
    'enterDeliveryCode': 'ग्राहक द्वारा दिया गया डिलीवरी कोड दर्ज करें।',
    'deliveryCompleted':
        'डिलीवरी की पुष्टि हुई और ऑर्डर सफलतापूर्वक बंद हो गया।',
    'invalidDeliveryCode': 'कोड गलत है, समाप्त हो चुका है या प्रयास लॉक हैं।',
    'confirmLogout': 'क्या आप ड्राइवर खाते से साइन आउट करना चाहते हैं?',
    'welcomeBack': 'वापसी पर स्वागत है',
    'loginCaption': 'बुन्या के साथ अपना प्रोजेक्ट संभालने के लिए साइन इन करें',
    'emailOrPhone': 'ईमेल या मोबाइल नंबर',
    'password': 'पासवर्ड',
    'forgotPassword': 'पासवर्ड भूल गए?',
    'signIn': 'साइन इन',
    'orderItems': 'ऑर्डर के उत्पाद',
    'quantity': 'मात्रा',
    'unit': 'इकाई',
    'measurement': 'माप',
    'myRequests': 'मेरे अनुरोध',
    'myAccount': 'मेरा खाता',
    'quoteRequest': 'मूल्य प्रस्ताव माँगें',
  },
  'bn': {
    'paySecurely': 'Paymob-এর মাধ্যমে নিরাপদ পেমেন্ট',
    'acceptAndPay': 'কোটেশন গ্রহণ করে পেমেন্ট করুন',
    'paymentOpening': 'নিরাপদ পেমেন্ট পেজ খোলা হচ্ছে...',
    'paymentStartFailed': 'পেমেন্ট শুরু করা যায়নি। আবার চেষ্টা করুন।',
    'paymentSucceeded': 'পেমেন্ট সফল এবং অর্ডার আপডেট হয়েছে।',
    'language': 'ভাষা',
    'chooseLanguage': 'ভাষা নির্বাচন করুন',
    'home': 'হোম',
    'products': 'পণ্য',
    'pricing': 'মূল্য নির্ধারণ',
    'deliveries': 'ডেলিভারি',
    'services': 'সেবা',
    'notifications': 'বিজ্ঞপ্তি',
    'account': 'অ্যাকাউন্ট',
    'homeNav': 'হোম',
    'pricingNav': 'মূল্য',
    'deliveriesNav': 'ডেলিভারি',
    'servicesNav': 'সেবা',
    'notificationsNav': 'বার্তা',
    'accountNav': 'অ্যাকাউন্ট',
    'approvalsNav': 'পর্যালোচনা',
    'opportunitiesNav': 'সুযোগ',
    'adminPortal': 'প্রশাসন পোর্টাল',
    'providerPortal': 'সরবরাহকারী পোর্টাল',
    'contractorPortal': 'ঠিকাদার পোর্টাল',
    'driverPortal': 'ড্রাইভার পোর্টাল',
    'bunyaAccount': 'বুন্যা অ্যাকাউন্ট',
    'adminWelcome': 'সব কার্যক্রম এক নজরে',
    'adminWelcomeCaption':
        'অনুমোদন যাচাই করুন এবং অ্যাপ থেকে দৈনন্দিন কার্যক্রম দেখুন।',
    'providerWelcome': 'অনুরোধকে বিক্রয়ে রূপ দিন',
    'providerWelcomeCaption':
        'দাম দিন, অর্ডার প্রস্তুত করুন এবং ডেলিভারি পরিচালনা করুন।',
    'contractorWelcome': 'সুযোগ ও প্রকল্প এক জায়গায়',
    'contractorWelcomeCaption':
        'সুযোগ দেখুন, প্রস্তাব দিন এবং কাজের অগ্রগতি দেখুন।',
    'driverWelcome': 'প্রতিটি ডেলিভারি, প্রতিটি ধাপে পরিষ্কার',
    'driverWelcomeCaption': 'অবস্থান দেখুন, যাত্রা নথিভুক্ত করুন এবং গ্রাহকের কোডে ডেলিভারি নিশ্চিত করুন।',
    'activeTasks': 'সক্রিয় কাজ',
    'arrivedAtSite': 'স্থানে পৌঁছেছে',
    'deliveredCount': 'ডেলিভারি হয়েছে',
    'pricingRequests': 'মূল্য অনুরোধ',
    'supplyOrders': 'সরবরাহ অর্ডার',
    'opportunities': 'সুযোগ',
    'offers': 'প্রস্তাব',
    'projects': 'প্রকল্প',
    'providerApplications': 'সরবরাহকারীর আবেদন',
    'contractorApplications': 'ঠিকাদারের আবেদন',
    'productReviews': 'পণ্য পর্যালোচনা',
    'liveConnectedData': 'সরাসরি সংযুক্ত তথ্য',
    'liveConnectedDataCaption': 'প্রতিটি কাজ ও পদক্ষেপ নিরাপদে সংরক্ষিত থাকে এবং হালনাগাদ সরাসরি বিজ্ঞপ্তিতে দেখা যায়।',
    'operationsAndServices': 'সেবা ও কার্যক্রম',
    'operationsAndServicesCaption': 'আপনার ভূমিকার সব সরঞ্জাম এক জায়গায়।',
    'notificationsCaption': 'মূল্য, গ্রহণ, পূরণ ও সিদ্ধান্ত।',
    'noNotifications': 'এখনও কোনো বিজ্ঞপ্তি নেই',
    'notificationDetails': 'বিজ্ঞপ্তির বিবরণ',
    'bunyaAlert': 'বুন্যা থেকে বিজ্ঞপ্তি',
    'read': 'পঠিত',
    'new': 'নতুন',
    'name': 'নাম',
    'email': 'ইমেইল',
    'mobile': 'মোবাইল',
    'role': 'ভূমিকা',
    'notAdded': 'দেওয়া হয়নি',
    'resetPassword': 'পাসওয়ার্ড রিসেট করুন',
    'noRecords': 'এখনও কোনো রেকর্ড নেই',
    'deliverySitesAndStatus': 'অবস্থান, সংগ্রহ ও ডেলিভারির অবস্থা',
    'updateHistory': 'হালনাগাদের ইতিহাস',
    'recordedDeliveryTransitions': 'ডেলিভারির নথিভুক্ত সব অবস্থা পরিবর্তন',
    'logout': 'সাইন আউট',
    'cancel': 'বাতিল',
    'deliveryTasks': 'ডেলিভারি কাজ',
    'deliveryTasksCaption': 'অবস্থান ও বিস্তারিত যাচাই করুন এবং ডেলিভারি কোড পর্যন্ত প্রতিটি ধাপ নথিভুক্ত করুন।',
    'noAssignedTasks':
        'কোনো কাজ নির্ধারিত নেই। সরবরাহকারী কাজ দেওয়ার পর এখানে দেখা যাবে।',
    'activeDeliveries': 'সক্রিয় ডেলিভারি',
    'completedDeliveries': 'সম্পন্ন ডেলিভারি',
    'noActiveDeliveries': 'এই মুহূর্তে কোনো সক্রিয় ডেলিভারি নেই।',
    'noCompletedDeliveries': 'এখনও কোনো সম্পন্ন ডেলিভারি নেই।',
    'tapForDetails': 'বিস্তারিত দেখতে ট্যাপ করুন',
    'deliveryStatusUpdated': 'ডেলিভারির অবস্থা হালনাগাদ ও সংরক্ষিত হয়েছে।',
    'recipient': 'প্রাপক',
    'siteResponsible': 'সাইটের দায়িত্বপ্রাপ্ত ব্যক্তি',
    'deliveryContacts': 'ডেলিভারি যোগাযোগ',
    'siteReadiness': 'সাইট ও মালামাল ওঠানো-নামানোর তথ্য',
    'workingHours': 'কাজের সময়',
    'loadingUnloading': 'লোডিং ও আনলোডিং',
    'roadAccess': 'রাস্তার প্রবেশযোগ্যতা',
    'accessInstructions': 'প্রবেশের নির্দেশনা',
    'openGoogleMaps': 'Google Maps-এ ডেলিভারির স্থান খুলুন',
    'callRecipient': 'প্রাপককে কল করুন',
    'callSiteResponsible': 'সাইটের দায়িত্বপ্রাপ্ত ব্যক্তিকে কল করুন',
    'callFailed': 'ফোন অ্যাপ খোলা যায়নি। ফোনের সেটিংস যাচাই করুন।',
    'mapsFailed': 'এই ফোনে Google Maps খোলা যায়নি।',
    'pickedUpFromProvider': 'সরবরাহকারীর কাছ থেকে নেওয়া হয়েছে',
    'outForDelivery': 'ডেলিভারি শুরু করুন',
    'arrivedCustomer': 'গ্রাহকের কাছে পৌঁছেছি',
    'deliveryFailed': 'ডেলিভারি ব্যর্থ',
    'customerDeliveryCode': 'গ্রাহকের ডেলিভারি কোড',
    'deliveryCodeWarning': 'সম্পূর্ণ পণ্য দেওয়ার আগে কোড চাইবেন না।',
    'customerCode': 'গ্রাহকের কোড',
    'confirmAndClose': 'ডেলিভারি নিশ্চিত করে অর্ডার বন্ধ করুন',
    'enterDeliveryCode': 'গ্রাহকের দেওয়া ডেলিভারি কোড লিখুন।',
    'deliveryCompleted':
        'ডেলিভারি নিশ্চিত হয়েছে এবং অর্ডার সফলভাবে বন্ধ হয়েছে।',
    'invalidDeliveryCode':
        'কোডটি ভুল, মেয়াদোত্তীর্ণ অথবা চেষ্টা লক করা হয়েছে।',
    'confirmLogout': 'আপনি কি ড্রাইভার অ্যাকাউন্ট থেকে সাইন আউট করতে চান?',
    'welcomeBack': 'আবারও স্বাগতম',
    'loginCaption': 'বুন্যার মাধ্যমে আপনার প্রকল্প পরিচালনা করতে সাইন ইন করুন',
    'emailOrPhone': 'ইমেইল বা মোবাইল নম্বর',
    'password': 'পাসওয়ার্ড',
    'forgotPassword': 'পাসওয়ার্ড ভুলে গেছেন?',
    'signIn': 'সাইন ইন',
    'orderItems': 'অর্ডারের পণ্য',
    'quantity': 'পরিমাণ',
    'unit': 'একক',
    'measurement': 'পরিমাপ',
    'myRequests': 'আমার অনুরোধ',
    'myAccount': 'আমার অ্যাকাউন্ট',
    'quoteRequest': 'মূল্য প্রস্তাব চান',
  },
  'fil': {
    'paySecurely': 'Ligtas na magbayad gamit ang Paymob',
    'acceptAndPay': 'Tanggapin ang quote at magbayad',
    'paymentOpening': 'Binubuksan ang ligtas na checkout...',
    'paymentStartFailed': 'Hindi masimulan ang bayad. Subukan muli.',
    'paymentSucceeded': 'Matagumpay ang bayad at na-update ang order.',
    'language': 'Wika',
    'chooseLanguage': 'Pumili ng wika',
    'home': 'Home',
    'products': 'Mga Produkto',
    'pricing': 'Pagpepresyo',
    'deliveries': 'Mga Delivery',
    'services': 'Mga Serbisyo',
    'notifications': 'Mga Abiso',
    'account': 'Account',
    'homeNav': 'Home',
    'pricingNav': 'Presyo',
    'deliveriesNav': 'Delivery',
    'servicesNav': 'Serbisyo',
    'notificationsNav': 'Abiso',
    'accountNav': 'Account',
    'approvalsNav': 'Review',
    'opportunitiesNav': 'Trabaho',
    'adminPortal': 'Admin portal',
    'providerPortal': 'Provider portal',
    'contractorPortal': 'Contractor portal',
    'driverPortal': 'Driver portal',
    'bunyaAccount': 'Bunya account',
    'adminWelcome': 'Lahat ng operasyon sa isang tingin',
    'adminWelcomeCaption':
        'Suriin ang approvals at bantayan ang araw-araw na operasyon sa app.',
    'providerWelcome': 'Gawing benta ang mga request',
    'providerWelcomeCaption':
        'Magbigay ng presyo, ihanda ang order, at pamahalaan ang delivery.',
    'contractorWelcome': 'Mga oportunidad at proyekto sa isang lugar',
    'contractorWelcomeCaption': 'Suriin ang mga oportunidad, magsumite ng alok, at subaybayan ang trabaho.',
    'driverWelcome': 'Malinaw ang bawat delivery, sa bawat hakbang',
    'driverWelcomeCaption': 'Suriin ang lokasyon, itala ang biyahe, at kumpirmahin ang delivery gamit ang code ng customer.',
    'activeTasks': 'Aktibong gawain',
    'arrivedAtSite': 'Nasa site',
    'deliveredCount': 'Naihatid',
    'pricingRequests': 'Mga request sa presyo',
    'supplyOrders': 'Supply orders',
    'opportunities': 'Mga oportunidad',
    'offers': 'Mga alok',
    'projects': 'Mga proyekto',
    'providerApplications': 'Aplikasyon ng provider',
    'contractorApplications': 'Aplikasyon ng contractor',
    'productReviews': 'Review ng produkto',
    'liveConnectedData': 'Live at konektadong impormasyon',
    'liveConnectedDataCaption': 'Ligtas na naka-save ang bawat gawain at aksyon, at direktang lumalabas sa mga abiso ang updates.',
    'operationsAndServices': 'Serbisyo at operasyon',
    'operationsAndServicesCaption':
        'Lahat ng tool para sa iyong tungkulin sa isang lugar.',
    'notificationsCaption': 'Presyo, pagtanggap, fulfillment, at mga desisyon.',
    'noNotifications': 'Wala pang abiso',
    'notificationDetails': 'Detalye ng abiso',
    'bunyaAlert': 'Abiso mula sa Bunya',
    'read': 'Nabasa',
    'new': 'Bago',
    'name': 'Pangalan',
    'email': 'Email',
    'mobile': 'Mobile',
    'role': 'Tungkulin',
    'notAdded': 'Hindi ibinigay',
    'resetPassword': 'I-reset ang password',
    'noRecords': 'Wala pang record',
    'deliverySitesAndStatus': 'Lokasyon at status ng pickup at delivery',
    'updateHistory': 'History ng updates',
    'recordedDeliveryTransitions':
        'Lahat ng naitalang pagbabago sa delivery status',
    'logout': 'Mag-sign out',
    'cancel': 'Kanselahin',
    'deliveryTasks': 'Mga Gawain sa Delivery',
    'deliveryTasksCaption': 'Suriin ang lokasyon at mga detalye, at itala ang bawat hakbang hanggang sa delivery code.',
    'noAssignedTasks': 'Walang nakatalagang gawain. Lalabas dito ang gawain kapag itinalaga ito ng provider.',
    'activeDeliveries': 'Mga aktibong delivery',
    'completedDeliveries': 'Mga natapos na delivery',
    'noActiveDeliveries': 'Walang aktibong delivery sa ngayon.',
    'noCompletedDeliveries': 'Wala pang natapos na delivery.',
    'tapForDetails': 'I-tap para tingnan ang detalye',
    'deliveryStatusUpdated': 'Na-update at nai-save ang status ng delivery.',
    'recipient': 'Tatanggap',
    'siteResponsible': 'Taong namamahala sa site',
    'deliveryContacts': 'Mga contact sa delivery',
    'siteReadiness': 'Detalye ng site at paghawak ng kargamento',
    'workingHours': 'Oras ng trabaho',
    'loadingUnloading': 'Pagkarga at pagbaba',
    'roadAccess': 'Daan papunta sa site',
    'accessInstructions': 'Mga tagubilin sa pagpunta',
    'openGoogleMaps': 'Buksan ang lokasyon ng delivery sa Google Maps',
    'callRecipient': 'Tawagan ang tatanggap',
    'callSiteResponsible': 'Tawagan ang namamahala sa site',
    'callFailed':
        'Hindi mabuksan ang phone app. Suriin ang settings ng telepono.',
    'mapsFailed': 'Hindi mabuksan ang Google Maps sa teleponong ito.',
    'pickedUpFromProvider': 'Nakuha na sa provider',
    'outForDelivery': 'Simulan ang delivery',
    'arrivedCustomer': 'Nakarating na sa customer',
    'deliveryFailed': 'Hindi naihatid',
    'customerDeliveryCode': 'Delivery code ng customer',
    'deliveryCodeWarning':
        'Huwag hingin ang code bago maihatid ang kumpletong kargamento.',
    'customerCode': 'Code ng customer',
    'confirmAndClose': 'Kumpirmahin ang delivery at isara ang order',
    'enterDeliveryCode': 'Ilagay ang delivery code na ibinigay ng customer.',
    'deliveryCompleted':
        'Nakumpirma ang delivery at matagumpay na isinara ang order.',
    'invalidDeliveryCode':
        'Mali o expired ang code, o naka-lock ang mga pagsubok.',
    'confirmLogout': 'Gusto mo bang mag-sign out sa driver account?',
    'welcomeBack': 'Maligayang pagbabalik',
    'loginCaption': 'Mag-sign in para pamahalaan ang iyong proyekto sa Bunya',
    'emailOrPhone': 'Email o mobile number',
    'password': 'Password',
    'forgotPassword': 'Nakalimutan ang password?',
    'signIn': 'Mag-sign in',
    'orderItems': 'Mga produkto sa order',
    'quantity': 'Dami',
    'unit': 'Yunit',
    'measurement': 'Sukat',
    'myRequests': 'Mga request ko',
    'myAccount': 'Account ko',
    'quoteRequest': 'Humingi ng presyo',
  },
};

const _statusKeys = <String, String>{
  'assigned': 'statusAssigned',
  'picked_up': 'statusPickedUp',
  'in_transit': 'statusInTransit',
  'arrived': 'statusArrived',
  'delivered': 'statusDelivered',
  'failed_delivery': 'statusFailed',
};

const _statusMessages = <String, Map<String, String>>{
  'ar': {
    'statusAssigned': 'مسند',
    'statusPickedUp': 'تم الاستلام',
    'statusInTransit': 'في الطريق',
    'statusArrived': 'وصل للموقع',
    'statusDelivered': 'تم التسليم',
    'statusFailed': 'تعذر التسليم',
  },
  'en': {
    'statusAssigned': 'Assigned',
    'statusPickedUp': 'Collected',
    'statusInTransit': 'In transit',
    'statusArrived': 'Arrived',
    'statusDelivered': 'Delivered',
    'statusFailed': 'Delivery failed',
  },
  'ur': {
    'statusAssigned': 'تفویض شدہ',
    'statusPickedUp': 'وصول شدہ',
    'statusInTransit': 'راستے میں',
    'statusArrived': 'مقام پر پہنچ گیا',
    'statusDelivered': 'ڈیلیور ہو گیا',
    'statusFailed': 'ڈیلیوری ناکام',
  },
  'hi': {
    'statusAssigned': 'सौंपा गया',
    'statusPickedUp': 'सामान लिया गया',
    'statusInTransit': 'रास्ते में',
    'statusArrived': 'स्थान पर पहुँचा',
    'statusDelivered': 'डिलीवर हो गया',
    'statusFailed': 'डिलीवरी विफल',
  },
  'bn': {
    'statusAssigned': 'নির্ধারিত',
    'statusPickedUp': 'সংগ্রহ করা হয়েছে',
    'statusInTransit': 'পথে আছে',
    'statusArrived': 'স্থানে পৌঁছেছে',
    'statusDelivered': 'ডেলিভারি হয়েছে',
    'statusFailed': 'ডেলিভারি ব্যর্থ',
  },
  'fil': {
    'statusAssigned': 'Nakatalaga',
    'statusPickedUp': 'Nakuha na',
    'statusInTransit': 'Papunta na',
    'statusArrived': 'Nakarating na',
    'statusDelivered': 'Naihatid na',
    'statusFailed': 'Hindi naihatid',
  },
};

final _arabicLiteralKeys = <String, String>{
  for (final entry in _messages['ar']!.entries) entry.value: entry.key,
};

final _arabicStatusKeys = <String, String>{
  for (final entry in _statusMessages['ar']!.entries) entry.value: entry.key,
};

extension BunyaTranslations on BuildContext {
  String tr(String key) {
    final code = Localizations.localeOf(this).languageCode;
    return _messages[code]?[key] ?? _messages['ar']?[key] ?? key;
  }

  String localizedStatus(String raw) {
    final code = Localizations.localeOf(this).languageCode;
    final key = _statusKeys[raw];
    return key == null ? raw : (_statusMessages[code]?[key] ?? raw);
  }

  String localizedUiText(String value) {
    final code = Localizations.localeOf(this).languageCode;
    if (code == 'ar') return value;
    final trimmed = value.trim();
    final messageKey = _arabicLiteralKeys[trimmed];
    if (messageKey != null) {
      return value.replaceFirst(
        trimmed,
        _messages[code]?[messageKey] ?? trimmed,
      );
    }
    final statusKey = _arabicStatusKeys[trimmed];
    if (statusKey != null) {
      return value.replaceFirst(
        trimmed,
        _statusMessages[code]?[statusKey] ?? trimmed,
      );
    }
    return value;
  }

  String localizedSnapshot(Object? source, Object? translations) {
    final fallback = '${source ?? '—'}';
    final code = Localizations.localeOf(this).languageCode;
    if (code == 'ar' || translations is! Map) return fallback;
    final translated = '${translations[code] ?? ''}'.trim();
    return translated.isEmpty ? fallback : translated;
  }
}

class BunyaLanguageButton extends StatelessWidget {
  const BunyaLanguageButton({super.key});

  @override
  Widget build(BuildContext context) => IconButton(
    tooltip: context.tr('chooseLanguage'),
    icon: const Icon(Icons.translate_rounded),
    onPressed: () => showModalBottomSheet<void>(
      context: context,
      showDragHandle: true,
      builder: (sheetContext) => SafeArea(
        child: ListView(
          shrinkWrap: true,
          padding: const EdgeInsets.fromLTRB(16, 0, 16, 20),
          children: [
            Padding(
              padding: const EdgeInsets.symmetric(vertical: 8),
              child: Text(
                context.tr('chooseLanguage'),
                style: Theme.of(context).textTheme.titleLarge
                    ?.copyWith(fontWeight: FontWeight.w900),
              ),
            ),
            for (final locale in supportedBunyaLocales)
              ListTile(
                minTileHeight: 52,
                title: Text(bunyaLanguageNames[locale.languageCode]!),
                trailing:
                    locale.languageCode ==
                        Localizations.localeOf(context).languageCode
                    ? const Icon(Icons.check_circle_rounded)
                    : const Icon(Icons.circle_outlined),
                onTap: () async {
                  Navigator.pop(sheetContext);
                  await BunyaLocaleController.change(locale.languageCode);
                },
              ),
          ],
        ),
      ),
    ),
  );
}
