/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import {useEffect,useState} from "react";
import {endDriverSessions,readDeliveryConfirmations,readDriverAssignments,readDrivers,recordDriverAdminAction,setDriverStatus,syncProviderAssignments} from "@/lib/driver-storage";
import type {ProviderDriver} from "@/lib/driver-types";
import {recordAdminDecision} from "@/lib/admin-storage";
import {AdminDecisionDialog,AdminHeader,AdminStatus,AdminToast} from "./AdminUI";

export function AdminDriversMonitoring(){const[drivers,setDrivers]=useState<ProviderDriver[]>([]);const[decision,setDecision]=useState<{driver:ProviderDriver;action:string}|null>(null);const[toast,setToast]=useState("");const[reason,setReason]=useState("");const refresh=()=>setDrivers(readDrivers());useEffect(refresh,[]);const act=(reason:string)=>{if(!decision)return;const{driver,action}=decision;if(action==="إيقاف الحساب")setDriverStatus(driver.id,"suspended",reason,"admin-super");else if(action==="إعادة التفعيل")setDriverStatus(driver.id,"active",reason,"admin-super");else if(action==="إنهاء الجلسات")endDriverSessions(driver.id,reason,"admin-super");else recordDriverAdminAction(driver.id,action,reason,"admin-super");recordAdminDecision("drivers",driver.id,action,reason,driver.status,action==="إيقاف الحساب"?"suspended":action==="إعادة التفعيل"?"active":driver.status);setDecision(null);setReason("");setToast("تم تنفيذ الإجراء الرقابي وتسجيل Audit.");refresh()};return <div className="admin-page-stack"><AdminToast message={toast}/><AdminHeader eyebrow="رقابة حسابات المزودين" title="مراقبة السائقين" description="الإدارة تراقب وتحقق وتوقف الحساب؛ المزود وحده ينشئ الحسابات ويسند التشغيل اليومي."/>{drivers.length?<section className="admin-record-grid">{drivers.map(driver=>{const assignments=readDriverAssignments().filter(item=>item.driverId===driver.id);return <article className="admin-panel admin-record-card" key={driver.id}><header><div><small>{driver.providerName}</small><h3>{driver.fullName}</h3><span>{driver.mobile} · {driver.email}</span></div><AdminStatus value={driver.status}/></header><dl className="admin-record-meta"><div><dt>اسم المستخدم</dt><dd>{driver.username}</dd></div><div><dt>التوصيلات الحالية</dt><dd>{assignments.filter(item=>!['delivered','failed_delivery'].includes(item.status)).length}</dd></div><div><dt>المحاولات الفاشلة</dt><dd>{driver.failedCodeAttempts}</dd></div><div><dt>المخالفات</dt><dd>{driver.violations}</dd></div><div><dt>آخر نشاط</dt><dd>{driver.lastActiveAt?new Date(driver.lastActiveAt).toLocaleString('ar-SA'):"لم يدخل"}</dd></div><div><dt>تاريخ الإنشاء</dt><dd>{new Date(driver.createdAt).toLocaleDateString('ar-SA')}</dd></div></dl><footer className="admin-record-actions">{[driver.status==='suspended'?"إعادة التفعيل":"إيقاف الحساب","إنهاء الجلسات","فتح تحقيق","طلب توضيح من المزود"].map(action=><button key={action} onClick={()=>setDecision({driver,action})}>{action}</button>)}</footer></article>})}</section>:<section className="admin-empty"><span>⌖</span><h3>لا توجد حسابات سائقين</h3><p>ينشئ المزود الحسابات من بوابته، ولا تنشئها الإدارة نيابة عنه.</p></section>}{decision?<AdminDecisionDialog title={decision.action} description="السبب إلزامي وسيظهر في سجل التدقيق." reason={reason} onReason={setReason} onCancel={()=>{setDecision(null);setReason("")}} onConfirm={()=>act(reason)}/>:null}</div>}

export function AdminDeliveryMonitoring(){const[version,setVersion]=useState(0);useEffect(()=>{syncProviderAssignments();setVersion(value=>value+1)},[]);const assignments=readDriverAssignments();const drivers=readDrivers();const confirmations=readDeliveryConfirmations();return <div className="admin-page-stack" data-version={version}><AdminHeader eyebrow="مراقبة دون تشغيل يومي" title="مراقبة التوصيل" description="الحالة وطريقة التأكيد والمحاولات والنزاعات والتحديثات، دون كشف الكود الصريح."/><section className="admin-record-grid">{assignments.map(item=>{const driver=drivers.find(value=>value.id===item.driverId);const confirmation=confirmations.find(value=>value.assignmentId===item.id);const late=new Date(item.expectedAt)<new Date()&&!['delivered','failed_delivery'].includes(item.status);return <article className="admin-panel admin-record-card" key={item.id}><header><div><small>{item.deliveryCode}</small><h3>{item.orderCode}</h3><span>{driver?.providerName??"المزود المسؤول"}</span></div><AdminStatus value={item.status}/></header><dl className="admin-record-meta"><div><dt>السائق</dt><dd>{driver?.fullName??"تنفيذ دون حساب"}</dd></div><div><dt>طريقة التأكيد</dt><dd>{confirmation?.method??"بانتظار التأكيد"}</dd></div><div><dt>الموعد المتوقع</dt><dd>{new Date(item.expectedAt).toLocaleString('ar-SA')}</dd></div><div><dt>التأخير</dt><dd>{late?"متأخر":"ضمن الموعد"}</dd></div><div><dt>محاولات الكود</dt><dd>{item.codeAttempts}/{item.maxCodeAttempts}</dd></div><div><dt>النزاعات</dt><dd>{item.status==='failed_delivery'?"يحتاج متابعة":"لا يوجد"}</dd></div></dl><div className="admin-history-placeholder"><b>سجل التحديثات</b>{item.updates.map(update=><p key={update.id}>{new Date(update.createdAt).toLocaleString('ar-SA')} · {update.status} · {update.note??"تحديث حالة"}</p>)}</div></article>})}</section></div>}
