/* eslint-disable @next/next/no-img-element */
"use client";

import Link from "next/link";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
import styles from "./ProviderRfqResponse.module.css";

type Target={sourcing_request_item_id:string;request_code:string|null;internal_code:string|null;response_deadline_at:string;product_name:string;product_sku:string|null;product_description:string|null;product_image_storage_path:string|null;product_image_url:string|null;quantity:number;unit_snapshot:string;measurement_snapshot:string|null;item_notes:string|null;delivery_region:string;required_at:string;location_hint:string;google_maps_url:string|null;delivery_mode:string;request_notes:string|null;current_lowest_unit_price:number|null;current_lowest_landed_cost:number|null};
type Existing={id:string;response_code:string;status:string;unit_price:number;vat_inclusive:boolean;price_expires_at:string;notes:string|null;available:boolean;available_quantity:number;region_eligible:boolean;preparation_hours:number;delivery_hours:number;delivery_fee:number;submitted_at:string};
const format=(value:string)=>new Date(value).toLocaleString("ar-SA",{dateStyle:"medium",timeStyle:"short"});
const localDate=(date:Date)=>new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);
const amount=(value:number)=>`${Number(value).toLocaleString("ar-SA",{maximumFractionDigits:2})} ر.س`;

export function ProviderRfqResponse({id}:{id:string}){
  const router=useRouter(),[target,setTarget]=useState<Target|null>(null),[existing,setExisting]=useState<Existing|null>(null),[image,setImage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[price,setPrice]=useState(""),[deliveryFee,setDeliveryFee]=useState("0"),[vatInclusive,setVatInclusive]=useState(true),[priceWindow,setPriceWindow]=useState({min:"",max:"",initial:""});
  useEffect(()=>{const db=createClient();void Promise.all([db.rpc("get_provider_rfq_context",{p_sourcing_item_id:id}),db.rpc("get_my_provider_rfq_response",{p_sourcing_item_id:id})]).then(async([context,response])=>{if(context.error){setError(context.error.message);return}const value=context.data as unknown as Target,now=new Date(),maximum=new Date(now),initial=new Date(now);maximum.setHours(maximum.getHours()+72);initial.setHours(initial.getHours()+24);setPriceWindow({min:localDate(now),max:localDate(maximum),initial:localDate(initial)});setTarget(value);setExisting((response.data as unknown as Existing|null)||null);if(value.product_image_url)setImage(value.product_image_url);else if(value.product_image_storage_path){const signed=await db.storage.from("provider-product-images").createSignedUrl(value.product_image_storage_path,600);setImage(signed.data?.signedUrl||"")}})},[id]);
  const totals=useMemo(()=>{const subtotal=Number(price||0)*Number(target?.quantity||0),vat=vatInclusive?0:subtotal*.15,total=subtotal+vat+Number(deliveryFee||0);return{subtotal,vat,total}},[price,deliveryFee,vatInclusive,target?.quantity]);
  const submittedTotals=useMemo(()=>{const subtotal=Number(existing?.unit_price||0)*Number(target?.quantity||0),vat=existing?.vat_inclusive?0:subtotal*.15,total=subtotal+vat+Number(existing?.delivery_fee||0);return{subtotal,vat,total}},[existing,target?.quantity]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(existing)return;setBusy(true);setError("");const d=new FormData(event.currentTarget),result=await createClient().rpc("submit_provider_pricing_response",{p_sourcing_item_id:id,p_response:{unit_price:Number(d.get("unit_price")),vat_inclusive:d.get("vat_inclusive")==="on",available:d.get("available")==="on",available_quantity:Number(d.get("available_quantity")),preparation_hours:Number(d.get("preparation_hours")),delivery_hours:Number(d.get("delivery_hours")),delivery_fee:Number(d.get("delivery_fee")),region_eligible:d.get("region_eligible")==="on",price_expires_at:new Date(String(d.get("price_expires_at"))).toISOString(),notes:d.get("notes")}});setBusy(false);if(result.error){setError(result.error.message);return}router.push("/merchant/quotes");router.refresh()}
  if(error&&!target)return <main className="database-page"><section className="database-state database-error"><h1>تعذر فتح الطلب</h1><p>{error}</p></section></main>;
  if(!target)return <main className="database-page"><section className="database-state"><p>جارٍ تحميل بيانات الطلب...</p></section></main>;
  return <main className={`database-page ${styles.page}`}>
    <header className={styles.header}><div><p>{existing?"عرض السعر محفوظ":"طلب تسعير موجّه لمنشأتك"}</p><h1>{existing?"تفاصيل العرض المقدم":"راجع الطلب وقدّم السعر"}</h1></div><div className={styles.deadline}><span>{existing?"تم تقديم العرض":"آخر موعد لإرسال العرض"}</span><strong>{format(existing?.submitted_at||target.response_deadline_at)}</strong></div></header>
    <div className={styles.layout}>
      <div className={styles.panel}>
        <section className={styles.product}><div className={styles.image}>{image?<img src={image} alt={target.product_name}/>:<div className={styles.placeholder}>لا توجد صورة للمنتج</div>}</div><div className={styles.productInfo}><div className={styles.codes}><span>{target.request_code||"—"}</span><span>{target.internal_code||"—"}</span>{target.product_sku?<span>SKU: {target.product_sku}</span>:null}</div><h2>{target.product_name}</h2><p>{target.product_description||"منتج معتمد ومطلوب تسعيره حسب البيانات التالية."}</p><div className={styles.grid}><div className={styles.field}><span>الكمية المطلوبة</span><strong>{target.quantity} {target.unit_snapshot}</strong></div><div className={styles.field}><span>القياس</span><strong>{target.measurement_snapshot||"بدون قياس إضافي"}</strong></div><div className={styles.field}><span>موعد الاستلام</span><strong>{format(target.required_at)}</strong></div></div></div></section>
        <section className={styles.section}><h2>بيانات التسليم والمواصفات</h2><div className={styles.grid}><div className={styles.field}><span>المنطقة</span><strong>{target.delivery_region}</strong></div><div className={styles.field}><span>طريقة الاستلام</span><strong>{target.delivery_mode==="pickup"?"استلام من المزود":"توصيل لموقع العميل"}</strong></div><div className={styles.field}><span>وصف الموقع</span><strong>{target.location_hint||"—"}</strong></div></div><div className={styles.notes}><div className={styles.field}><span>مواصفات المنتج</span><strong>{target.item_notes||"لا توجد مواصفات إضافية"}</strong></div><div className={styles.field}><span>ملاحظات العميل</span><strong>{target.request_notes||"لا توجد ملاحظات إضافية"}</strong></div></div>{target.google_maps_url?<div className={styles.map}><div><span>الموقع الجغرافي للتسليم</span><strong>{target.location_hint||target.delivery_region}</strong></div><a href={target.google_maps_url} target="_blank" rel="noreferrer">فتح خرائط Google ↗</a></div>:null}</section>
      </div>
      <aside className={`${styles.panel} ${styles.formPanel}`}><h2>{existing?`عرضك ${existing.response_code}`:"تفاصيل عرض منشأتك"}</h2><div className={styles.comparison}><div><span>أقل سعر وحدة حاليًا</span><strong>{target.current_lowest_unit_price===null?"لا يوجد":amount(target.current_lowest_unit_price)}</strong></div><div><span>أقل تكلفة واصلة حاليًا</span><strong>{target.current_lowest_landed_cost===null?"لا يوجد":amount(target.current_lowest_landed_cost)}</strong></div></div>
        {existing?<div className={styles.form}><p className={styles.notice}>تم استلام عرضك بنجاح، ولا يمكن تقديم عرض ثانٍ لنفس الطلب.</p><div className={styles.field}><span>سعر الوحدة</span><strong>{amount(existing.unit_price)}</strong></div><div className={styles.field}><span>الكمية المتوفرة</span><strong>{existing.available_quantity} {target.unit_snapshot}</strong></div><div className={styles.field}><span>التجهيز والتوصيل</span><strong>{existing.preparation_hours} ساعة تجهيز + {existing.delivery_hours} ساعة توصيل</strong></div><div className={styles.field}><span>تكلفة التوصيل</span><strong>{amount(existing.delivery_fee)}</strong></div><div className={styles.field}><span>الضريبة</span><strong>{existing.vat_inclusive?"السعر شامل الضريبة":"تضاف ضريبة 15%"}</strong></div><div className={styles.field}><span>صلاحية السعر</span><strong>{format(existing.price_expires_at)}</strong></div><div className={`${styles.summary} ${styles.wide}`}><div><span>قيمة المنتجات</span><strong>{amount(submittedTotals.subtotal)}</strong></div><div><span>الضريبة المضافة</span><strong>{amount(submittedTotals.vat)}</strong></div><div><span>إجمالي العرض الواصل</span><strong>{amount(submittedTotals.total)}</strong></div></div>{existing.notes?<div className={`${styles.field} ${styles.wide}`}><span>ملاحظات العرض</span><strong>{existing.notes}</strong></div>:null}<Link className={styles.submit} href="/merchant/quotes">العودة إلى استجابات التسعير</Link></div>:
        <form className={styles.form} onSubmit={submit}><label>سعر الوحدة (ر.س)<input name="unit_price" type="number" min="0" step="0.01" required value={price} onChange={event=>setPrice(event.target.value)}/></label><label>الكمية المتوفرة<input name="available_quantity" type="number" min={target.quantity} step="0.001" required defaultValue={target.quantity}/></label><label>مدة التجهيز بالساعات<input name="preparation_hours" type="number" min="0" required defaultValue="0"/></label><label>مدة التوصيل بالساعات<input name="delivery_hours" type="number" min="0" required defaultValue="0"/></label><label>تكلفة التوصيل (ر.س)<input name="delivery_fee" type="number" min="0" step="0.01" required value={deliveryFee} onChange={event=>setDeliveryFee(event.target.value)}/></label><label>صلاحية السعر<input name="price_expires_at" type="datetime-local" min={priceWindow.min} max={priceWindow.max} required defaultValue={priceWindow.initial}/></label><div className={`${styles.checks} ${styles.wide}`}><label className={styles.check}><input name="available" type="checkbox" defaultChecked/> المنتج متوفر</label><label className={styles.check}><input name="region_eligible" type="checkbox" defaultChecked/> يمكن التوصيل للمنطقة</label><label className={styles.check}><input name="vat_inclusive" type="checkbox" checked={vatInclusive} onChange={event=>setVatInclusive(event.target.checked)}/> السعر شامل الضريبة</label></div><label className={styles.wide}>ملاحظات العرض<textarea name="notes" rows={3} placeholder="شروط التحميل أو التوصيل وأي تفاصيل يجب أن يعرفها العميل"/></label><div className={`${styles.summary} ${styles.wide}`}><div><span>قيمة المنتجات</span><strong>{amount(totals.subtotal)}</strong></div><div><span>الضريبة المضافة</span><strong>{amount(totals.vat)}</strong></div><div><span>إجمالي العرض الواصل</span><strong>{amount(totals.total)}</strong></div></div><p className={styles.notice}>سيتم اعتماد أقل تكلفة مؤهلة بعد التأكد من توفر كامل الكمية وإمكانية التسليم في الموعد.</p>{error?<p className={styles.error}>{error}</p>:null}<button className={styles.submit} disabled={busy||!price}>{busy?"جارٍ إرسال العرض...":"تأكيد وإرسال عرض السعر"}</button></form>}
      </aside>
    </div>
  </main>
}
