"use client";
import {FormEvent,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {validatePassword} from "@/lib/bunya-local";
import {getSiteUrl} from "@/lib/supabase/env";
import {createClient} from "@/lib/supabase/client";
import {ApplicationSuccessState,AuthCard,PasswordFieldWithVisibilityCheckbox,PortalShell} from "./PortalUI";
type Errors=Record<string,string>;const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/,mobilePattern=/^(?:\+?966|0)?5\d{8}$/;
export function RegisterFlow(){const router=useRouter(),[form,setForm]=useState({fullName:"",mobile:"",email:"",username:"",password:"",confirmPassword:""}),[errors,setErrors]=useState<Errors>({}),[busy,setBusy]=useState(false),[otpPhone,setOtpPhone]=useState(""),[otp,setOtp]=useState("");const update=(key:keyof typeof form,value:string)=>{setForm(current=>({...current,[key]:value}));setErrors({})};
 const submit=async(event:FormEvent)=>{event.preventDefault();const next:Errors={},username=form.username.normalize("NFKC").trim().replace(/\s+/gu," ");if(form.fullName.trim().length<3)next.fullName="أدخل الاسم الكامل.";if(!mobilePattern.test(form.mobile.replace(/\s/g,"")))next.mobile="أدخل رقم جوال سعوديًا صحيحًا.";if(!emailPattern.test(form.email.trim()))next.email="أدخل بريدًا صحيحًا.";if(username.length<4||username.length>40)next.username="اسم المستخدم من 4 إلى 40 حرفًا.";const passwordError=validatePassword(form.password);if(passwordError)next.password=passwordError;if(form.password!==form.confirmPassword)next.confirmPassword="كلمتا المرور غير متطابقتين.";if(Object.keys(next).length)return setErrors(next);setBusy(true);const response=await fetch("/api/auth/register",{method:"POST",headers:{"content-type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({...form,username})}),body=await response.json() as {phone?:string;message?:string};if(!response.ok||!body.phone){setBusy(false);return setErrors({form:body.message||"تعذر إنشاء الحساب."})}const sent=await createClient().auth.signInWithOtp({phone:body.phone,options:{shouldCreateUser:false}});setBusy(false);setOtpPhone(body.phone);if(sent.error)setErrors({form:"تم إنشاء الحساب، لكن تعذر إرسال الرمز. أعد الإرسال."})};
 const verify=async(event:FormEvent)=>{event.preventDefault();if(!/^\d{4,10}$/.test(otp))return setErrors({otp:"أدخل الرمز الصحيح."});setBusy(true);const supabase=createClient(),verified=await supabase.auth.verifyOtp({phone:otpPhone,token:otp,type:"sms"});if(verified.error||!verified.data.session){setBusy(false);return setErrors({otp:"الرمز خاطئ أو منتهي."})}const initialized=await supabase.rpc("initialize_customer_account");if(initialized.error){await supabase.auth.signOut();setBusy(false);return setErrors({form:"تعذر تهيئة ملف العميل."})}router.replace("/customer");router.refresh()};
 const resend=async()=>{setBusy(true);const result=await createClient().auth.resend({type:"sms",phone:otpPhone});setBusy(false);setErrors(result.error?{otp:"انتظر قبل إعادة المحاولة."}:{})};
 if(otpPhone)return <PortalShell><AuthCard eyebrow="تحقق الهاتف" title="أدخل رمز التحقق" description="أرسل Supabase الرمز إلى واتساب عبر القناة الموثوقة."><form className="portal-form" onSubmit={verify}><TextField id="otp" label="رمز التحقق" value={otp} onChange={value=>{setOtp(value);setErrors({})}} error={errors.otp} inputMode="tel"/><button className="portal-primary-button" disabled={busy}>{busy?"جارٍ التحقق...":"تحقق وتفعيل الحساب"}</button><button type="button" disabled={busy} onClick={resend}>إعادة إرسال الرمز</button>{errors.form?<p className="portal-form-error">{errors.form}</p>:null}</form></AuthCard></PortalShell>;
 return <PortalShell><AuthCard eyebrow="حساب جديد" title="انضم إلى بُنية" description="أنشئ حساب عميل ثم تحقق من رقم الجوال."><form className="portal-form portal-form-two" onSubmit={submit}><TextField id="name" label="الاسم الكامل" value={form.fullName} onChange={v=>update("fullName",v)} error={errors.fullName}/><TextField id="mobile" label="رقم الجوال" value={form.mobile} onChange={v=>update("mobile",v)} error={errors.mobile} inputMode="tel"/><TextField id="email" label="البريد الإلكتروني" value={form.email} onChange={v=>update("email",v)} error={errors.email} type="email"/><TextField id="username" label="اسم المستخدم" value={form.username} onChange={v=>update("username",v)} error={errors.username}/><PasswordFieldWithVisibilityCheckbox id="password" label="كلمة المرور" value={form.password} onChange={v=>update("password",v)} error={errors.password}/><PasswordFieldWithVisibilityCheckbox id="confirm" label="تأكيد كلمة المرور" value={form.confirmPassword} onChange={v=>update("confirmPassword",v)} error={errors.confirmPassword} confirm/>{errors.form?<p className="portal-form-error portal-full">{errors.form}</p>:null}<button className="portal-primary-button portal-full" disabled={busy}>{busy?"جارٍ الإنشاء...":"إنشاء الحساب والتحقق"}</button><p className="portal-auth-note portal-full">لديك حساب؟ <Link href="/login">سجل الدخول</Link></p></form></AuthCard></PortalShell>}

export function ForgotPasswordFlow(){const[email,setEmail]=useState(""),[error,setError]=useState(""),[success,setSuccess]=useState(false),[busy,setBusy]=useState(false);const submit=async(event:FormEvent)=>{event.preventDefault();const clean=email.trim().toLowerCase();if(!emailPattern.test(clean))return setError("أدخل بريدًا صحيحًا.");setBusy(true);const result=await createClient().auth.resetPasswordForEmail(clean,{redirectTo:`${getSiteUrl()}/auth/callback?next=/reset-password`});setBusy(false);if(result.error)return setError("تعذر إرسال رابط الاستعادة.");setSuccess(true)};if(success)return <PortalShell><ApplicationSuccessState title="تحقق من بريدك" message="إذا كان البريد مرتبطًا بحساب فسيصلك رابط آمن." actionHref="/login" actionLabel="العودة لتسجيل الدخول"/></PortalShell>;return <PortalShell><AuthCard eyebrow="استعادة الوصول" title="نسيت كلمة المرور؟" description="سنرسل رابط استعادة آمنًا إلى بريدك."><form className="portal-form" onSubmit={submit}><TextField id="forgot" label="البريد الإلكتروني" value={email} onChange={v=>{setEmail(v);setError("")}} error={error} type="email"/><button className="portal-primary-button" disabled={busy}>{busy?"جارٍ الإرسال...":"إرسال رابط الاستعادة"}</button></form></AuthCard></PortalShell>}

export function ResetPasswordFlow(){const router=useRouter(),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[errors,setErrors]=useState<Errors>({}),[busy,setBusy]=useState(false);const submit=async(event:FormEvent)=>{event.preventDefault();const next:Errors={},passwordError=validatePassword(password);if(passwordError)next.password=passwordError;if(password!==confirm)next.confirm="كلمتا المرور غير متطابقتين.";if(Object.keys(next).length)return setErrors(next);setBusy(true);const supabase=createClient(),session=await supabase.auth.getSession();if(!session.data.session){setBusy(false);return setErrors({form:"رابط الاستعادة منتهي أو غير صالح."})}const result=await supabase.auth.updateUser({password});if(result.error){setBusy(false);return setErrors({form:"تعذر تحديث كلمة المرور."})}await supabase.auth.signOut();router.replace("/login?password=updated");router.refresh()};return <PortalShell><AuthCard eyebrow="تعيين كلمة جديدة" title="اختر كلمة مرور قوية" description="سيتم تحديثها داخل Supabase Auth."><form className="portal-form" onSubmit={submit}><PasswordFieldWithVisibilityCheckbox id="reset" label="كلمة المرور الجديدة" value={password} onChange={setPassword} error={errors.password}/><PasswordFieldWithVisibilityCheckbox id="reset-confirm" label="التأكيد" value={confirm} onChange={setConfirm} error={errors.confirm} confirm/>{errors.form?<p className="portal-form-error">{errors.form}</p>:null}<button className="portal-primary-button" disabled={busy}>{busy?"جارٍ الحفظ...":"حفظ كلمة المرور"}</button></form></AuthCard></PortalShell>}

function TextField({id,label,value,onChange,error,type="text",inputMode}:{id:string;label:string;value:string;onChange:(value:string)=>void;error?:string;type?:string;inputMode?:"tel"|"email"}){return <div className="portal-field"><label htmlFor={id}>{label}</label><input id={id} type={type} inputMode={inputMode} value={value} onChange={event=>onChange(event.target.value)}/>{error?<small className="portal-error">{error}</small>:null}</div>}
