import{readFile,readdir}from"node:fs/promises";import{resolve}from"node:path";
const dir=resolve("supabase/migrations"),files=(await readdir(dir)).filter(x=>/^\d{3}_.+\.sql$/.test(x)).sort(),errors=[],warnings=[];
const numbers=files.map(x=>Number(x.slice(0,3)));for(let i=0;i<numbers.length;i++)if(numbers[i]!==i+1)errors.push(`Migration numbering gap/duplicate at ${files[i]}`);
const tables=new Set(["storage.objects","storage.buckets"]),columns=new Map(),rls=new Set(),functions=new Map(),policies=new Set(),allSql=[];
function splitColumns(body){const out=[];let depth=0,start=0;for(let i=0;i<body.length;i++){if(body[i]==='(')depth++;else if(body[i]===')')depth--;else if(body[i]===','&&depth===0){out.push(body.slice(start,i));start=i+1}}out.push(body.slice(start));return out}
function signatureParams(raw){return splitColumns(raw).map(x=>x.trim()).filter(Boolean).length}
for(const file of files){const sql=await readFile(resolve(dir,file),"utf8"),lower=sql.toLowerCase();allSql.push(sql);
 for(const m of lower.matchAll(/create\s+table\s+(?:if\s+not\s+exists\s+)?(?:public\.)?([a-z_][\w]*)\s*\(([^;]+?)\);/gs)){const table=m[1];if(tables.has(table))errors.push(`${file}: duplicate table ${table}`);tables.add(table);const set=new Set();for(const part of splitColumns(m[2])){const name=part.trim().match(/^([a-z_][\w]*)\s+/)?.[1];if(name&&!['constraint','primary','unique','foreign','check'].includes(name))set.add(name)}columns.set(table,set)}
 for(const m of lower.matchAll(/alter\s+table\s+(?:public\.)?([a-z_][\w]*)\s+([^;]+);/gs)){const table=m[1];if(!tables.has(table)&&!table.startsWith('storage.'))errors.push(`${file}: ALTER before table creation: ${table}`);for(const a of m[2].matchAll(/add\s+column\s+(?:if\s+not\s+exists\s+)?([a-z_][\w]*)/g))columns.get(table)?.add(a[1]);if(/enable\s+row\s+level\s+security/.test(m[2]))rls.add(table)}
 for(const m of lower.matchAll(/references\s+(?:public\.)?([a-z_][\w]*)\s*\(/g))if(!tables.has(m[1]))errors.push(`${file}: FK references missing/late table ${m[1]}`);
 for(const m of lower.matchAll(/create\s+(?:unique\s+)?index\s+(?:if\s+not\s+exists\s+)?([a-z_][\w]*)\s+on\s+(?:public\.)?([a-z_][\w]*)/g))if(!tables.has(m[2]))errors.push(`${file}: index ${m[1]} on missing table ${m[2]}`);
 for(const m of lower.matchAll(/create\s+policy\s+([a-z_][\w]*)\s+on\s+(?:(public|storage)\.)?([a-z_][\w]*)/g)){const table=m[2]==='storage'?`storage.${m[3]}`:m[3],key=`${table}.${m[1]}`;if(!tables.has(table))errors.push(`${file}: policy on missing table ${table}`);if(policies.has(key)&&!new RegExp(`drop\\s+policy\\s+(?:if\\s+exists\\s+)?${m[1]}\\s+on\\s+(?:(?:public|storage)\\.)?${m[3]}`,'i').test(sql.slice(0,m.index)))errors.push(`${file}: duplicate policy ${key}`);policies.add(key);if(!table.startsWith('storage.')&&!rls.has(table))errors.push(`${file}: policy before RLS enable on ${table}`)}
 for(const m of lower.matchAll(/create\s+or\s+replace\s+function\s+(?:public\.)?([a-z_][\w]*)\s*\(([^)]*)\)([\s\S]*?)\$\$;/g)){const name=m[1],arity=signatureParams(m[2]),body=m[3];functions.set(name,{arity,file});if(/security\s+definer/.test(body)&&!/set\s+search_path\s*=/.test(body))errors.push(`${file}: SECURITY DEFINER ${name} lacks fixed search_path`)}
 for(const m of lower.matchAll(/create\s+(?!or\s+replace)function\s+(?:public\.)?([a-z_][\w]*)\s*\(([^)]*)\)([\s\S]*?)\$\$;/g)){const name=m[1],arity=signatureParams(m[2]),body=m[3];functions.set(name,{arity,file});if(/security\s+definer/.test(body)&&!/set\s+search_path\s*=/.test(body))errors.push(`${file}: SECURITY DEFINER ${name} lacks fixed search_path`)}
}
const combined=allSql.join("\n").toLowerCase(),revokedFunctions=new Set();for(const statement of combined.matchAll(/revoke\s+(?:all|execute)\s+on\s+function\s+([^;]+?)\s*from\s+/g))for(const item of splitColumns(statement[1])){const name=item.trim().match(/^(?:public\.)?([a-z_][\w]*)\s*\(/)?.[1];if(name)revokedFunctions.add(name)}for(const[name,{file}]of functions)if(new RegExp(`function\\s+(?:public\\.)?${name}\\s*\\([^)]*\\)[\\s\\S]{0,500}?security\\s+definer`,'i').test(combined)&&!revokedFunctions.has(name))errors.push(`${file}: SECURITY DEFINER ${name} has no explicit revoke`);
async function sourceFiles(root){const out=[];for(const e of await readdir(root,{withFileTypes:true})){const p=resolve(root,e.name);if(e.isDirectory())out.push(...await sourceFiles(p));else if(/\.(ts|tsx)$/.test(e.name))out.push(p)}return out}
for(const path of await sourceFiles(resolve("src"))){const source=await readFile(path,"utf8");for(const m of source.matchAll(/\.rpc\(["']([a-z_][\w]*)["']/g))if(!functions.has(m[1]))errors.push(`${path}: RPC ${m[1]} has no migration function`)}
for(const required of['support_tickets','support_messages','support_attachments_v2','contractor_bank_accounts','contractor_financial_transactions','contractor_settlement_requests'])if(!rls.has(required))errors.push(`RLS missing for ${required}`);
if(/\b(insert|update)\b[^;]*(otp|plain_password|temporary_password)\s*[,)]=?/i.test(combined))warnings.push("Review sensitive-token persistence match manually");
if(errors.length){console.error(errors.map(x=>`ERROR ${x}`).join("\n"));if(warnings.length)console.error(warnings.map(x=>`WARN ${x}`).join("\n"));process.exit(1)}console.log(`SQL static validation passed: ${files.length} migrations, ${tables.size-2} tables, ${functions.size} functions, ${policies.size} policies.`);if(warnings.length)console.log(warnings.map(x=>`WARN ${x}`).join("\n"));
