"use client";
import type {ReactNode} from "react";
import Link from "next/link";
export const contractorMoney=(value:number)=>new Intl.NumberFormat("ar-SA",{style:"currency",currency:"SAR",maximumFractionDigits:2}).format(value);
export const contractorDate=(value:string)=>new Intl.DateTimeFormat("ar-SA",{day:"numeric",month:"short",year:"numeric"}).format(new Date(value));
const labels:Record<string,string>={pending_review:"بانتظار المراجعة",pending_admin_review:"بانتظار الإدارة",approved_for_customer:"أُرسل للعميل",rejected_by_admin:"رفضته الإدارة",needs_contractor_revision:"يحتاج تعديلًا",accepted_by_customer:"قبله العميل",rejected_by_customer:"رفضه العميل",customer_requested_clarification:"يحتاج توضيحًا",approved:"معتمد",suspended:"موقوف",available:"متاح",busy:"مشغول",temporarily_unavailable:"غير متاح مؤقتًا",new:"جديد",viewed:"تمت المشاهدة",proposed:"تم تقديم عرض",expired:"منتهي",draft:"مسودة",under_review:"قيد مراجعة العميل",needs_changes:"يحتاج تعديلًا",accepted:"تم القبول",rejected:"تم الرفض",withdrawn:"مسحوب",awaiting_start:"بانتظار البدء",active:"نشط",paused:"متوقف مؤقتًا",delayed:"متأخر",awaiting_milestone_approval:"بانتظار اعتماد مرحلة",completed:"مكتمل",cancelled:"ملغي",not_started:"لم تبدأ",in_progress:"قيد التنفيذ",awaiting_customer_approval:"بانتظار اعتماد العميل",hidden:"مخفية",pending:"معلق",partial:"مدفوع جزئيًا",paid:"مدفوع",transferring:"قيد التحويل",transferred:"تم التحويل",not_uploaded:"غير مرفوع",expiring_soon:"سينتهي قريبًا",open:"مفتوحة",resolved:"محلولة"};
export function ContractorStatus({value}:{value:string}){const good=["approved","available","active","accepted","completed","paid","transferred"].includes(value);const bad=["suspended","rejected","expired","withdrawn","cancelled","delayed"].includes(value);return <span className={`contractor-status ${good?"good":bad?"bad":["new","under_review","awaiting_customer_approval"].includes(value)?"info":"warn"}`}>{labels[value]??value}</span>}
export function ContractorHeader({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:ReactNode}){return <header className="contractor-page-header"><div><p>{eyebrow}</p><h2>{title}</h2><span>{description}</span></div>{action}</header>}
export function ContractorEmpty({title,description,href,action}:{title:string;description:string;href?:string;action?:string}){return <div className="contractor-empty"><span>◇</span><h3>{title}</h3><p>{description}</p>{href&&action?<Link className="contractor-primary" href={href}>{action}</Link>:null}</div>}
export function ContractorToast({message,tone="success"}:{message:string;tone?:"success"|"error"}){return message?<div role="status" className={`contractor-toast ${tone}`}>{tone==="success"?"✓":"!"} {message}</div>:null}
export function ContractorConfirm({open,title,description,confirmLabel="تأكيد",onConfirm,onCancel}:{open:boolean;title:string;description:string;confirmLabel?:string;onConfirm:()=>void;onCancel:()=>void}){return open?<div className="contractor-modal-backdrop" onMouseDown={onCancel}><section className="contractor-modal" role="dialog" aria-modal="true" onMouseDown={event=>event.stopPropagation()}><span>!</span><h3>{title}</h3><p>{description}</p><footer><button className="contractor-secondary" onClick={onCancel}>تراجع</button><button className="contractor-danger" onClick={onConfirm}>{confirmLabel}</button></footer></section></div>:null}
export function ContractorFileInput({label,onFiles}:{label:string;onFiles:(files:File[])=>void}){return <label className="contractor-file-input"><input type="file" multiple onChange={event=>{onFiles(Array.from(event.target.files??[]));event.target.value=""}}/><span>＋ {label}</span><small>تحفظ metadata فقط، والملفات لا تحفظ في localStorage.</small></label>}
