/* eslint-disable react-hooks/exhaustive-deps, react-hooks/set-state-in-effect, @next/next/no-img-element */
"use client";
import { usePathname } from "next/navigation";
import type{FormEvent}from"react";
import{useEffect,useState}from"react";
import{useAuthIdentity}from"@/components/auth/AuthIdentityProvider";
import{createClient}from"@/lib/supabase/client";
import{optimizeUploadFile}from"@/lib/uploads/client";

type Row=Record<string,unknown>&{id:string};
const reviewLabels:Record<string,string>={draft:"مسودة",pending_review:"قيد المراجعة",approved:"معتمد",rejected:"مرفوض",needs_changes:"يحتاج تعديلات"};
const pricing=[['meter','بالمتر'],['project','بالمشروع'],['hour','بالساعة'],['day','باليوم'],['starting_from','يبدأ من'],['inspection','بعد المعاينة']]as const;
const serviceBlank={title:"",description:"",specialty:"",pricing_method:"project",minimum_price:"",maximum_price:"",estimated_duration:"",regions:"",is_active:true};
const portfolioBlank={title:"",description:"",project_type:"",completion_date:"",city:"",region:"",visibility:false,sort_order:"0"};

export function ContractorServicesManager(){const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[editing,setEditing]=useState<Row|null>(null),[form,setForm]=useState(serviceBlank),[busy,setBusy]=useState(false);const db=createClient();
 const load=async()=>{setLoading(true);const result=await db.from("contractor_services").select("*,contractor_service_regions(region_name)").is("deleted_at",null).order("updated_at",{ascending:false});setRows((result.data??[])as Row[]);setError(result.error?.message??"");setLoading(false)};useEffect(()=>{void load()},[]);
 const edit=(row:Row)=>{setEditing(row);setForm({title:String(row.title??row.name??""),description:String(row.description??""),specialty:String(row.primary_specialty??""),pricing_method:String(row.pricing_method??"project"),minimum_price:String(row.minimum_price??""),maximum_price:String(row.maximum_price??""),estimated_duration:String(row.estimated_duration??""),regions:((row.contractor_service_regions as {region_name:string}[]|undefined)??[]).map(x=>x.region_name).join("، "),is_active:Boolean(row.is_active)})};
 const save=async(event:FormEvent,submit:boolean)=>{event.preventDefault();setBusy(true);setError("");const regions=form.regions.split(/[،,]/).map(x=>x.trim()).filter(Boolean);const result=await db.rpc("save_contractor_service",{p_id:editing?.id??null,p_service:{...form,specialty:form.specialty},p_regions:regions,p_submit:submit});setBusy(false);if(result.error)return setError(result.error.message);setEditing(null);setForm(serviceBlank);await load()};
 const toggle=async(row:Row)=>{const result=await db.rpc("set_contractor_service_active",{p_id:row.id,p_active:!row.is_active});if(result.error)setError(result.error.message);else await load()};const remove=async(row:Row)=>{if(!confirm("سيتم حذف الخدمة حذفًا آمنًا. هل تريد المتابعة؟"))return;const result=await db.rpc("delete_contractor_service",{p_id:row.id});if(result.error)setError(result.error.message);else await load()};
 return <CatalogPage title="خدماتي" description="عرّف العملاء بما تقدمه، وحدد نطاق الخدمة وطريقة تسعيرها. تظهر خدماتك بعد اعتمادها." loading={loading} error={error}>
  <div className="contractor-catalog-summary"><p>خدمات واضحة، وفرص أقرب لتخصصك.</p><span>{rows.length} خدمة في ملفك</span></div>
  <Editor title={editing?"تعديل الخدمة":"إضافة خدمة"} onSubmit={e=>void save(e,false)}>
    <FormSection title="تفاصيل الخدمة" description="اسم واضح ووصف يشرح ما سيحصل عليه العميل.">
      <Field label="العنوان" value={form.title} onChange={title=>setForm({...form,title})}/><Field label="التخصص / التصنيف" value={form.specialty} onChange={specialty=>setForm({...form,specialty})}/>
      <label className="wide"><span>الوصف</span><textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>
    </FormSection>
    <FormSection title="التسعير ونطاق العمل" description="وضح طريقة احتساب الخدمة، ومدة التنفيذ ومناطق التغطية.">
      <label><span>طريقة التسعير</span><select value={form.pricing_method} onChange={e=>setForm({...form,pricing_method:e.target.value})}>{pricing.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><Field label="المدة التقديرية" value={form.estimated_duration} onChange={estimated_duration=>setForm({...form,estimated_duration})}/>
      <Field label="الحد الأدنى" type="number" value={form.minimum_price} onChange={minimum_price=>setForm({...form,minimum_price})}/><Field label="الحد الأعلى" type="number" value={form.maximum_price} onChange={maximum_price=>setForm({...form,maximum_price})}/>
      <Field label="مناطق الخدمة — مفصولة بفاصلة" value={form.regions} onChange={regions=>setForm({...form,regions})}/><label className="contractor-catalog-check"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/><span>تفعيل الخدمة بعد الاعتماد</span></label>
    </FormSection>
    <footer className="wide contractor-catalog-actions"><p>احفظ مسودة للعودة إليها، أو أرسل الخدمة للمراجعة.</p><div><button disabled={busy}>{busy?"جارٍ الحفظ…":"حفظ كمسودة"}</button><button className="contractor-catalog-primary" type="button" disabled={busy} onClick={e=>void save(e as unknown as FormEvent,true)}>إرسال للمراجعة</button>{editing?<button type="button" disabled={busy} onClick={()=>{setEditing(null);setForm(serviceBlank)}}>إلغاء التعديل</button>:null}</div></footer>
  </Editor>
  <section className="contractor-catalog-collection" aria-labelledby="contractor-services-heading"><header><div><h2 id="contractor-services-heading">الخدمات المضافة</h2><p>تابع حالة المراجعة وحدّث خدماتك من هنا.</p></div><span>{rows.length}</span></header>
  {!loading&&!rows.length?<Empty text="ابدأ بإضافة أول خدمة لك من النموذج أعلاه."/>:<div className="database-record-grid contractor-service-grid">{rows.map(row=><article className="database-panel contractor-service-card" key={row.id}>
    <header><div><small>{String(row.primary_specialty)}</small><h3>{String(row.title)}</h3></div><Status value={String(row.review_status)} active={Boolean(row.is_active)}/></header><p className="contractor-catalog-description">{String(row.description)}</p>
    <dl className="contractor-catalog-facts"><div><dt>طريقة التسعير</dt><dd>{pricing.find(([value])=>value===row.pricing_method)?.[1]??"غير محدد"}</dd></div><div><dt>المدة التقديرية</dt><dd>{String(row.estimated_duration)||"غير محددة"}</dd></div><div className="wide"><dt>مناطق الخدمة</dt><dd>{((row.contractor_service_regions as {region_name:string}[]|undefined)??[]).map(x=>x.region_name).join("، ")||"غير محددة"}</dd></div></dl>
    {row.review_notes?<aside className="contractor-catalog-review"><strong>ملاحظة المراجعة</strong><p>{String(row.review_notes)}</p></aside>:null}<footer className="contractor-card-actions"><button onClick={()=>edit(row)} disabled={row.review_status==='pending_review'}>تعديل الخدمة</button><button onClick={()=>void toggle(row)}>{row.is_active?'إيقاف':'تفعيل'}</button><button className="contractor-catalog-danger" onClick={()=>void remove(row)}>حذف الخدمة</button></footer>
  </article>)}</div>}</section>
 </CatalogPage>}


export function ContractorPortfolioManager(){const identity=useAuthIdentity(),contractorId=identity.details.contractor?.contractorProfileId??"",[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[editing,setEditing]=useState<Row|null>(null),[form,setForm]=useState(portfolioBlank),[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),db=createClient();
 const hydrateUrls=async(items:Row[])=>Promise.all(items.map(async row=>{const media=(row.contractor_portfolio_media as Row[]|undefined)??[];const hydrated=await Promise.all(media.map(async m=>({...m,signed_url:(await db.storage.from("contractor-portfolio").createSignedUrl(String(m.storage_path),300)).data?.signedUrl??null})));return{...row,contractor_portfolio_media:hydrated}}));
 const load=async()=>{setLoading(true);const result=await db.from("contractor_portfolio_items").select("*,contractor_portfolio_media(*)").is("deleted_at",null).order("sort_order");setRows(await hydrateUrls((result.data??[])as Row[]));setError(result.error?.message??"");setLoading(false)};useEffect(()=>{void load()},[]);
 const edit=(row:Row)=>{setEditing(row);setFiles([]);setForm({title:String(row.title??""),description:String(row.description??""),project_type:String(row.project_type??""),completion_date:String(row.completion_date??""),city:String(row.city??""),region:String(row.region??""),visibility:Boolean(row.is_visible),sort_order:String(row.sort_order??0)})};
 const save=async(event:FormEvent,submit:boolean)=>{event.preventDefault();for(const file of files)if(!['image/jpeg','image/png','image/webp','video/mp4'].includes(file.type)||file.size>10*1024*1024)return setError(`الملف ${file.name} غير مدعوم أو أكبر من 10MB.`);setBusy(true);setError("");const saved=await db.rpc("save_contractor_portfolio_item",{p_id:editing?.id??null,p_item:form,p_submit:submit});if(saved.error){setBusy(false);return setError(saved.error.message)}const itemId=String(saved.data);for(let index=0;index<files.length;index++){const file=await optimizeUploadFile(files[index]),safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${contractorId}/${itemId}/${crypto.randomUUID()}-${safe}`;const upload=await db.storage.from("contractor-portfolio").upload(path,file,{contentType:file.type,upsert:false});if(upload.error){setBusy(false);return setError(upload.error.message)}const inserted=await db.from("contractor_portfolio_media").insert({portfolio_item_id:itemId,storage_path:path,file_name:file.name,mime_type:file.type,size_bytes:file.size,is_primary:index===0&&!(editing?.contractor_portfolio_media as Row[]|undefined)?.length,sort_order:index});if(inserted.error){setBusy(false);return setError(inserted.error.message)}}setBusy(false);setEditing(null);setFiles([]);setForm(portfolioBlank);await load()};
 const visibility=async(row:Row)=>{const r=await db.rpc("set_contractor_portfolio_visibility",{p_id:row.id,p_visible:!row.is_visible});if(r.error)setError(r.error.message);else await load()};const primary=async(row:Row,media:Row)=>{const r=await db.rpc("set_contractor_portfolio_primary_media",{p_item_id:row.id,p_media_id:media.id});if(r.error)setError(r.error.message);else await load()};const remove=async(row:Row)=>{if(!confirm("سيُخفى العنصر ويُحذف حذفًا آمنًا. هل تريد المتابعة؟"))return;const r=await db.rpc("delete_contractor_portfolio_item",{p_id:row.id});if(r.error)setError(r.error.message);else await load()};
 return <CatalogPage title="معرض الأعمال" description="وثّق مشاريعك المنجزة بالصور والفيديو، واجعل خبرتك واضحة للعملاء." loading={loading} error={error}>
  <div className="contractor-catalog-summary"><p>أعمالك السابقة تعرّف بجودة تنفيذك.</p><span>{rows.length} عمل في المعرض</span></div>
  <Editor title={editing?"تعديل العمل":"إضافة عمل للمعرض"} onSubmit={e=>void save(e,false)}>
    <FormSection title="عن المشروع" description="أضف عنوان العمل وتفاصيل تنفيذه وموقعه.">
      <Field label="العنوان" value={form.title} onChange={title=>setForm({...form,title})}/><Field label="نوع المشروع" value={form.project_type} onChange={project_type=>setForm({...form,project_type})}/><Field label="تاريخ الإنجاز" type="date" value={form.completion_date} onChange={completion_date=>setForm({...form,completion_date})}/><Field label="المدينة" value={form.city} onChange={city=>setForm({...form,city})}/><Field label="المنطقة" value={form.region} onChange={region=>setForm({...form,region})}/><Field label="ترتيب العرض" type="number" value={form.sort_order} onChange={sort_order=>setForm({...form,sort_order})}/>
      <label className="wide"><span>الوصف</span><textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>
    </FormSection>
    <FormSection title="صور وفيديو العمل" description="اختر ملفات تظهر تفاصيل التنفيذ والنتيجة النهائية.">
      <label className="wide contractor-catalog-upload"><span>إضافة وسائط</span><small>صور JPEG أو PNG أو WebP وفيديو MP4 — حتى 10MB لكل ملف.</small><input type="file" multiple accept="image/jpeg,image/png,image/webp,video/mp4" onChange={e=>setFiles(Array.from(e.target.files??[]))}/></label>
      {files.length?<ul className="wide contractor-catalog-file-list" aria-label="الملفات المختارة">{files.map((file,index)=><li key={`${file.name}-${index}`}><span>{file.name}</span><small>{(file.size/1024/1024).toFixed(1)} MB</small></li>)}</ul>:null}
      {editing?<p className="wide contractor-catalog-hint">الملفات التي تضيفها ستنضم إلى الوسائط الحالية لهذا العمل.</p>:null}<label className="wide contractor-catalog-check"><input type="checkbox" checked={form.visibility} onChange={e=>setForm({...form,visibility:e.target.checked})}/><span>إظهار العمل للعامة بعد الاعتماد</span></label>
    </FormSection>
    <footer className="wide contractor-catalog-actions"><p>يمكنك حفظ العمل كمسودة قبل إرساله للمراجعة.</p><div><button disabled={busy}>{busy?"جارٍ حفظ العمل ورفع الملفات…":"حفظ كمسودة"}</button><button className="contractor-catalog-primary" type="button" disabled={busy} onClick={e=>void save(e as unknown as FormEvent,true)}>إرسال للمراجعة</button>{editing?<button type="button" disabled={busy} onClick={()=>{setEditing(null);setFiles([]);setForm(portfolioBlank)}}>إلغاء التعديل</button>:null}</div></footer>
  </Editor>
  <section className="contractor-catalog-collection" aria-labelledby="contractor-portfolio-heading"><header><div><h2 id="contractor-portfolio-heading">أعمالك السابقة</h2><p>راجع الوسائط واختر الملف الأساسي لكل عمل.</p></div><span>{rows.length}</span></header>
  {!loading&&!rows.length?<Empty text="أضف أول مشروع منجز لتبدأ بناء معرض أعمالك."/>:<div className="database-record-grid contractor-portfolio-grid">{rows.map(row=><article className="database-panel contractor-portfolio-card" key={row.id}>
    <header><div><small>{String(row.project_type??"عمل منجز")}</small><h3>{String(row.title)}</h3></div><Status value={String(row.review_status)} active={Boolean(row.is_visible)}/></header>
    <div className="contractor-catalog-gallery">{((row.contractor_portfolio_media as Row[]|undefined)??[]).map(media=><figure key={media.id} data-primary={Boolean(media.is_primary)}>
      <div className="contractor-catalog-media">{media.signed_url?(String(media.mime_type).startsWith('image/')?<img loading="lazy" src={String(media.signed_url)} alt={String(media.file_name)}/>:String(media.mime_type).startsWith('video/')?<video controls playsInline preload="metadata" aria-label={String(media.file_name)} src={String(media.signed_url)}>متصفحك لا يدعم تشغيل الفيديو.</video>:<span>{String(media.file_name)}</span>):<span>معاينة الملف غير متاحة</span>}</div>
      <figcaption><span title={String(media.file_name)}>{String(media.file_name)}</span><button type="button" aria-pressed={Boolean(media.is_primary)} onClick={()=>void primary(row,media)}>{media.is_primary?"الملف الأساسي":"تعيين كأساسي"}</button></figcaption>
    </figure>)}</div>
    {!((row.contractor_portfolio_media as Row[]|undefined)??[]).length?<p className="contractor-catalog-hint">لم تضف صورًا أو فيديو لهذا العمل بعد.</p>:null}<p className="contractor-catalog-description">{String(row.description)}</p><dl className="contractor-catalog-facts"><div><dt>الموقع</dt><dd>{[row.city,row.region].filter(Boolean).map(String).join("، ")||"غير محدد"}</dd></div><div><dt>تاريخ الإنجاز</dt><dd>{String(row.completion_date??"غير محدد")}</dd></div></dl>
    {row.review_notes?<aside className="contractor-catalog-review"><strong>ملاحظة المراجعة</strong><p>{String(row.review_notes)}</p></aside>:null}<footer className="contractor-card-actions"><button onClick={()=>edit(row)} disabled={row.review_status==='pending_review'}>تعديل العمل</button><button onClick={()=>void visibility(row)}>{row.is_visible?'إخفاء':'إظهار'}</button><button className="contractor-catalog-danger" onClick={()=>void remove(row)}>حذف العمل</button></footer>
  </article>)}</div>}</section>
 </CatalogPage>}


export function AdminContractorCatalogReview({kind}:{kind:'service'|'portfolio'}){
 const[query,setQuery]=useState(""),[busy,setBusy]=useState<string|null>(null),[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notes,setNotes]=useState<Record<string,string>>({}),db=createClient(),table=kind==='service'?'contractor_services':'contractor_portfolio_items';
 const load=async()=>{setLoading(true);const selection=kind==='service'?"*,contractor:contractor_profiles!contractor_profile_id(display_name),contractor_service_regions(region_name)":"*,contractor:contractor_profiles!profile_id(display_name),contractor_portfolio_media(*)",r=await db.from(table).select(selection).in("review_status",['pending_review','needs_changes']).is("deleted_at",null).order("created_at");let items=(r.data??[])as Row[];if(kind==='portfolio')items=await Promise.all(items.map(async row=>({...row,contractor_portfolio_media:await Promise.all(((row.contractor_portfolio_media as Row[]|undefined)??[]).map(async media=>({...media,signed_url:(await db.storage.from("contractor-portfolio").createSignedUrl(String(media.storage_path),300)).data?.signedUrl??null})))})));setRows(items);setError(r.error?.message??"");setLoading(false)};
 useEffect(()=>{void load()},[kind]);const decide=async(id:string,decision:string)=>{if(busy)return;setBusy(id);try{const r=await db.rpc("review_contractor_catalog_item",{p_kind:kind,p_id:id,p_decision:decision,p_notes:notes[id]??""});if(r.error)setError(r.error.message);else await load()}catch{setError("تعذر حفظ القرار. حاول مرة أخرى.")}finally{setBusy(null)}};
 return <CatalogPage title={kind==='service'?'مراجعة خدمات المقاولين':'مراجعة معرض الأعمال'} description="راجع تفاصيل العمل وملاحظاته، ثم اعتمده أو أعده للمقاول مع توضيح المطلوب." loading={loading} error={error}><div className="admin-review-search"><label>البحث في عناصر المراجعة<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="اسم الخدمة أو العمل أو المقاول"/></label><span>{rows.filter(row=>String(row.title??row.name??'').concat(String((row.contractor as {display_name?:string}|null)?.display_name??'')).includes(query.trim())).length} عنصر مطابق</span></div>{!loading&&rows.length>0&&!rows.some(row=>String(row.title??row.name??'').concat(String((row.contractor as {display_name?:string}|null)?.display_name??'')).includes(query.trim()))?<div className="database-state"><h2>لا توجد نتائج مطابقة</h2><button onClick={()=>setQuery("")}>عرض جميع العناصر</button></div>:null}{!loading&&!rows.length?<Empty text="لا توجد عناصر بانتظار المراجعة."/>:<div className="database-record-grid">{rows.filter(row=>String(row.title??row.name??'').concat(String((row.contractor as {display_name?:string}|null)?.display_name??'')).includes(query.trim())).map(row=><article className="database-panel" key={row.id}><header><div><small>{String((row.contractor as {display_name?:string}|null)?.display_name??"اسم المقاول غير متاح")}</small><h3>{String(row.title??row.name)}</h3></div><Status value={String(row.review_status)} active={true}/></header><p>{String(row.description)}</p>{kind==='service'?<small>{String(row.primary_specialty)} · {pricing.find(([value])=>value===row.pricing_method)?.[1]??"التسعير غير محدد"} · {((row.contractor_service_regions as {region_name:string}[]|undefined)??[]).map(x=>x.region_name).join("، ")}</small>:<div className="portfolio-media">{((row.contractor_portfolio_media as Row[]|undefined)??[]).map(media=><span key={media.id}>{String(media.mime_type).startsWith('image/')&&media.signed_url?<img src={String(media.signed_url)} alt={String(media.file_name)}/>:String(media.file_name)}</span>)}</div>}<label><span>ملاحظة المراجعة</span><textarea rows={3} placeholder="سبب القرار — إلزامي" value={notes[row.id]??""} onChange={e=>setNotes({...notes,[row.id]:e.target.value})}/></label><footer>{['approved','needs_changes','rejected'].map(d=><button key={d} disabled={(notes[row.id]??'').trim().length<5} onClick={()=>void decide(row.id,d)}>{busy===row.id?"جارٍ حفظ القرار…":reviewLabels[d]}</button>)}</footer></article>)}</div>}</CatalogPage>}


function CatalogPage({title,description,loading,error,children}:{title:string;description:string;loading:boolean;error:string;children:React.ReactNode}){const admin=usePathname().startsWith("/admin");const Container=admin?"main":"section";return <Container className={admin?"database-page":"database-page contractor-catalog-page"}><header className="database-page-header"><div><p>{admin?"مراجعة محتوى المقاولين":"مساحة المقاول"}</p><h1>{title}</h1><span>{description}</span></div></header>{error?<section className="database-state database-error" role="alert"><p>{error}</p></section>:null}{loading?<section className="database-state"><span className="database-spinner"/><h2>جارٍ تحميل البيانات</h2></section>:children}</Container>}
function Editor({title,onSubmit,children}:{title:string;onSubmit:(e:FormEvent)=>void;children:React.ReactNode}){return <form className="database-panel database-editor contractor-catalog-editor" onSubmit={onSubmit}><h2>{title}</h2><div className="database-form-grid">{children}</div></form>}
function Field({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label><span>{label}</span><input required={type!=='number'} type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Status({value,active}:{value:string;active:boolean}){return <span className="database-status" data-review-status={value}>{reviewLabels[value]??value}{!active?' · غير نشط':''}</span>}
function Empty({text}:{text:string}){return <section className="database-state"><span>∅</span><h2>{text}</h2></section>}

function FormSection({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <fieldset className="wide contractor-catalog-section"><legend>{title}</legend><p>{description}</p><div className="contractor-catalog-fields">{children}</div></fieldset>}
