/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import type {ProviderPricingResponse} from "@/lib/sourcing-types";
import {providerProfileMock} from "@/lib/provider-data";
import {readSourcing} from "@/lib/sourcing-storage";
import {formatMoney,formatProviderDate,ProviderEmpty,ProviderPageHeader,ProviderStatus} from "./ProviderUI";

const responseLabel:Record<ProviderPricingResponse["status"],string>={evaluating:"قيد التقييم الداخلي",selected:"تم الفوز داخليًا",not_selected:"لم يتم الاختيار",expired:"منتهية",needs_update:"تحتاج تحديثًا",rejected:"مرفوضة"};
export function ProviderSentQuotes(){const[responses,setResponses]=useState<ProviderPricingResponse[]>([]);const[query,setQuery]=useState("");const[status,setStatus]=useState("all");useEffect(()=>setResponses(readSourcing("responses").filter(item=>item.providerId===providerProfileMock.id)),[]);const filtered=useMemo(()=>responses.filter(item=>(!query||`${item.responseCode} ${item.productId}`.includes(query))&&(status==="all"||item.status===status)),[responses,query,status]);return <div className="provider-page-stack"><ProviderPageHeader eyebrow="التسعير الداخلي" title="استجابات التسعير" description="تابع استجاباتك لبُنية ونتيجة الاختيار الداخلي؛ لا توجد موافقة مباشرة من العميل."/><section className="provider-filters"><label className="provider-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="رقم الاستجابة أو المنتج"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">كل الحالات</option>{Object.entries(responseLabel).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></section>{filtered.length?<div className="provider-table-wrap"><table className="provider-table"><thead><tr><th>الاستجابة</th><th>طلب بُنية</th><th>المنتج</th><th>السعر</th><th>الكمية</th><th>صلاحية السعر</th><th>الحالة</th><th>التفاصيل</th></tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td><strong>{item.responseCode}</strong></td><td>{item.requestId}</td><td>{item.productId}</td><td>{formatMoney(item.unitPrice)}</td><td>{item.availability.availableQuantity.toLocaleString("ar-SA")}</td><td>{formatProviderDate(item.priceExpiresAt)}</td><td><ProviderStatus value={responseLabel[item.status]}/></td><td><Link href={`/merchant/quotes/${item.id}`}>عرض التفاصيل</Link></td></tr>)}</tbody></table></div>:<ProviderEmpty title="لا توجد استجابات مطابقة" description="ستظهر هنا استجابات التحقق والتسعير المرسلة إلى بُنية."/>}</div>}

export function ProviderQuoteDetails({id}:{id:string}){const[response,setResponse]=useState<ProviderPricingResponse|null>(null);useEffect(()=>setResponse(readSourcing("responses").find(item=>item.id===id&&item.providerId===providerProfileMock.id)??null),[id]);if(!response)return <ProviderEmpty title="الاستجابة غير موجودة" description="قد تكون غير متاحة لهذا الحساب." href="/merchant/quotes" action="العودة للاستجابات"/>;return <div className="provider-page-stack"><ProviderPageHeader eyebrow={response.responseCode} title="استجابة تحقق وتسعير" description="هذه البيانات داخلية بين منشأتك وبُنية." action={<ProviderStatus value={responseLabel[response.status]}/>}/><div className="provider-detail-layout"><section className="provider-detail-content"><article className="provider-panel"><div className="provider-panel-title"><span>◈</span><h3>السعر والتوفر</h3></div><dl className="provider-info-grid"><div><dt>المنتج</dt><dd>{response.productId}</dd></div><div><dt>سعر الوحدة</dt><dd>{formatMoney(response.unitPrice)}</dd></div><div><dt>شامل الضريبة</dt><dd>{response.vatInclusive?"نعم":"لا"}</dd></div><div><dt>متوفر</dt><dd>{response.availability.available?"نعم":"لا"}</dd></div><div><dt>الكمية</dt><dd>{response.availability.availableQuantity.toLocaleString("ar-SA")}</dd></div><div><dt>تأكيد السعر</dt><dd>{formatProviderDate(response.priceConfirmedAt)}</dd></div><div><dt>انتهاء السعر</dt><dd>{formatProviderDate(response.priceExpiresAt)}</dd></div><div><dt>رسوم التوصيل</dt><dd>{formatMoney(response.delivery.deliveryFee)}</dd></div></dl></article><article className="provider-panel"><div className="provider-panel-title"><span>⌖</span><h3>التجهيز والتوصيل</h3></div><dl className="provider-info-grid"><div><dt>المنطقة مخدومة</dt><dd>{response.delivery.regionEligible?"نعم":"لا"}</dd></div><div><dt>مدة التجهيز</dt><dd>{response.delivery.preparationDurationHours} ساعة</dd></div><div><dt>مدة التوصيل</dt><dd>{response.delivery.deliveryDurationHours} ساعة</dd></div><div className="wide"><dt>ملاحظات داخلية</dt><dd>{response.internalNotes??"لا توجد ملاحظات."}</dd></div></dl></article></section><aside className="provider-panel provider-action-panel"><h3>نتيجة بُنية الداخلية</h3><ProviderStatus value={responseLabel[response.status]}/><p>{response.status==="selected"?"تم اختيار استجابتك لهذا المنتج، وسيظهر أمر التوريد عند إسناده.":response.status==="evaluating"?"تراجع بُنية السعر والتوفر والمنطقة والموعد حاليًا.":"النتيجة داخلية ولا تعكس قرارًا مباشرًا من العميل."}</p><Link className="provider-secondary" href="/merchant/quote-requests">طلبات التحقق</Link></aside></div></div>}
