/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import type {FormEvent} from "react";
import {useEffect,useState} from "react";
import type {ProviderOrder} from "@/lib/provider-types";
import {confirmDelivery,readDriverAssignments,syncProviderAssignments} from "@/lib/driver-storage";
import {readProviderProfile} from "@/lib/provider-storage";

export function ProviderDeliveryConfirmation({order,onConfirmed}:{order:ProviderOrder;onConfirmed:()=>void}){const[assignmentId,setAssignmentId]=useState("");const[open,setOpen]=useState(false);const[form,setForm]=useState({code:"",delegateName:"",deliveryReference:"",note:""});const[message,setMessage]=useState("");useEffect(()=>{syncProviderAssignments();setAssignmentId(readDriverAssignments().find(item=>item.orderId===order.id)?.id??"")},[order.id]);const submit=async(event:FormEvent)=>{event.preventDefault();if(!assignmentId)return setMessage("أنشئ مهمة التوصيل أولًا.");const profile=readProviderProfile();const result=await confirmDelivery(assignmentId,form.code,"provider",profile.id,{delegateName:form.delegateName.trim()||undefined,deliveryReference:form.deliveryReference.trim()||undefined,note:form.note.trim()||undefined});setMessage(result.message);if(result.ok){setOpen(false);onConfirmed()}};return <div className="provider-direct-confirm"><button className="provider-secondary" type="button" onClick={()=>setOpen(true)}>تأكيد التسليم بدون حساب سائق</button><small>يُستخدم عند تنفيذ المزود للتوصيل بمندوب غير مسجل.</small>{message?<p>{message}</p>:null}{open?<div className="provider-modal-backdrop" onMouseDown={()=>setOpen(false)}><form className="provider-modal" onSubmit={submit} onMouseDown={event=>event.stopPropagation()}><h3>تأكيد التسليم بواسطة المزود</h3><p>لا يُنشأ حساب سائق، ولا يحفظ الكود الصريح.</p><label><span>كود العميل</span><input dir="ltr" inputMode="numeric" maxLength={6} value={form.code} onChange={event=>setForm(current=>({...current,code:event.target.value.replace(/\D/g,'')}))}/></label><label><span>اسم المندوب — اختياري</span><input value={form.delegateName} onChange={event=>setForm(current=>({...current,delegateName:event.target.value}))}/></label><label><span>مرجع التوصيل — اختياري</span><input value={form.deliveryReference} onChange={event=>setForm(current=>({...current,deliveryReference:event.target.value}))}/></label><label><span>ملاحظة — اختيارية</span><textarea rows={3} value={form.note} onChange={event=>setForm(current=>({...current,note:event.target.value}))}/></label><footer><button type="button" onClick={()=>setOpen(false)}>تراجع</button><button className="provider-primary" disabled={form.code.length!==6}>مطابقة وتأكيد</button></footer></form></div>:null}</div>}
