/* eslint-disable react-hooks/set-state-in-effect, react-hooks/purity */
"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import type { ProviderProduct } from "@/lib/provider-types";
import type {ProviderProductPrice} from "@/lib/sourcing-types";
import { providerProductsMock,providerProfileMock } from "@/lib/provider-data";
import { readProviderCollection, writeProviderCollection } from "@/lib/provider-storage";
import {getPriceFreshness} from "@/lib/sourcing-engine";
import {readSourcing,writeSourcing} from "@/lib/sourcing-storage";
import { formatMoney, ProviderConfirmDialog, ProviderEmpty, ProviderPageHeader, ProviderStatus, ProviderToast } from "./ProviderUI";

export function ProviderProducts() {
  const [products, setProducts] = useState<ProviderProduct[]>(providerProductsMock);
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("all");
  const [status, setStatus] = useState("all");
  const [offerType, setOfferType] = useState("all");
  const [preview, setPreview] = useState<ProviderProduct | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<ProviderProduct | null>(null);
  const [toast, setToast] = useState("");
  const [prices,setPrices]=useState<ProviderProductPrice[]>([]);
  useEffect(() => {setProducts(readProviderCollection("products"));setPrices(readSourcing("prices").filter(item=>item.providerId===providerProfileMock.id));}, []);
  const categories = Array.from(new Set(products.map((item) => item.category)));
  const filtered = useMemo(() => products.filter((item) => (!query.trim() || `${item.name} ${item.description}`.toLowerCase().includes(query.trim().toLowerCase())) && (category === "all" || item.category === category) && (status === "all" || item.status === status) && (offerType === "all" || item.offerType === offerType)), [products, query, category, status, offerType]);
  const persist = (next: ProviderProduct[], message: string) => { setProducts(next); writeProviderCollection("products", next); setToast(message); window.setTimeout(() => setToast(""), 2500); };
  const disable = (product: ProviderProduct) => persist(products.map((item) => item.id === product.id ? { ...item, availability: "unavailable", status: "unavailable", updatedAt: new Date().toISOString() } : item), "تم تعطيل المنتج محليًا.");
  const confirmPrice=(product:ProviderProduct)=>{const now=new Date();const expiresAt=new Date(now.getTime()+72*3600000).toISOString();const next:ProviderProductPrice={id:`price-${providerProfileMock.id}-${product.id}`,providerId:providerProfileMock.id,productId:product.id,unitPrice:product.price,vatInclusive:product.vatInclusive,lastUpdatedAt:prices.find(item=>item.productId===product.id)?.lastUpdatedAt??now.toISOString(),lastConfirmedAt:now.toISOString(),expiresAt,freshnessStatus:"valid"};const all=readSourcing("prices");writeSourcing("prices",[next,...all.filter(item=>!(item.providerId===providerProfileMock.id&&item.productId===product.id))]);setPrices([next,...prices.filter(item=>item.productId!==product.id)]);setToast("تم تأكيد السعر وتجديد صلاحيته لمدة 72 ساعة.");};
  return <div className="provider-page-stack"><ProviderToast message={toast} /><ProviderPageHeader eyebrow="الكتالوج" title="إدارة المنتجات" description="تابع حالة كل منتج، وعدّل بيانات العرض والتوفر من مكان واحد." action={<Link className="provider-primary" href="/merchant/products/new">＋ رفع منتج</Link>} />
    <section className="provider-filters"><label className="provider-search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ابحث باسم المنتج" /></label><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">كل التصنيفات</option>{categories.map((item) => <option key={item}>{item}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">كل الحالات</option><option value="draft">مسودة</option><option value="pending_review">بانتظار المراجعة</option><option value="active">نشط</option><option value="rejected">مرفوض</option><option value="unavailable">غير متوفر</option></select><select value={offerType} onChange={(event) => setOfferType(event.target.value)}><option value="all">بيع وتأجير</option><option value="sale">بيع</option><option value="rental">تأجير</option></select></section>
    {filtered.length ? <section className="provider-product-grid">{filtered.map((product) => {const price=prices.find(item=>item.productId===product.id);const freshness=price?getPriceFreshness(price):"needs_confirmation";const remaining=price?Math.max(0,Math.ceil((new Date(price.expiresAt).getTime()-Date.now())/3600000)):0;return <article className="provider-product-card" key={product.id}><div className="provider-product-visual"><span>{product.images[0]?.isPrimary ? "صورة رئيسية" : "بدون صورة"}</span><b>{product.category.slice(0, 1)}</b></div><div className="provider-product-body"><header><div><small>{product.category} · {product.offerType === "sale" ? "بيع" : "تأجير"}</small><h3>{product.name}</h3></div><ProviderStatus value={product.status} /></header><p>{product.description}</p><dl><div><dt>آخر سعر</dt><dd>{formatMoney(price?.unitPrice??product.price)}</dd></div><div><dt>صلاحية السعر</dt><dd><ProviderStatus value={freshness}/></dd></div><div><dt>الوقت المتبقي</dt><dd>{remaining?`${remaining.toLocaleString("ar-SA")} ساعة`:"يلزم التأكيد"}</dd></div><div><dt>آخر تحديث</dt><dd>{price?new Date(price.lastUpdatedAt).toLocaleDateString("ar-SA"):"—"}</dd></div><div><dt>آخر تأكيد</dt><dd>{price?new Date(price.lastConfirmedAt).toLocaleDateString("ar-SA"):"—"}</dd></div><div><dt>المخزون</dt><dd>{product.stockQuantity?.toLocaleString("ar-SA") ?? "غير محدد"}</dd></div></dl><footer><button type="button" onClick={() => confirmPrice(product)}>تأكيد أن السعر لم يتغير</button><button type="button" onClick={() => setPreview(product)}>معاينة</button><Link href={`/merchant/products/new?edit=${product.id}`}>تعديل السعر</Link><button type="button" onClick={() => disable(product)}>تعطيل</button><button className="danger" type="button" onClick={() => setDeleteTarget(product)}>حذف</button></footer></div></article>})}</section> : <ProviderEmpty title="لا توجد منتجات مطابقة" description="غيّر الفلاتر أو ارفع منتجًا جديدًا." href="/merchant/products/new" action="رفع منتج" />}
    {preview ? <div className="provider-modal-backdrop" onMouseDown={() => setPreview(null)}><section className="provider-modal provider-preview-modal" role="dialog" aria-modal="true" onMouseDown={(event) => event.stopPropagation()}><button className="provider-modal-close" onClick={() => setPreview(null)}>×</button><div className="provider-product-visual large"><b>{preview.category.slice(0, 1)}</b></div><ProviderStatus value={preview.status} /><h3>{preview.name}</h3><p>{preview.description}</p><dl><div><dt>نوع العرض</dt><dd>{preview.offerType === "sale" ? "بيع" : "تأجير"}</dd></div><div><dt>الضريبة</dt><dd>{preview.vatInclusive ? "شاملة" : "تضاف لاحقًا"}</dd></div><div><dt>التوصيل</dt><dd>{preview.delivery.available ? "متوفر" : "غير متوفر"}</dd></div></dl></section></div> : null}
    <ProviderConfirmDialog open={Boolean(deleteTarget)} title="حذف المنتج محليًا؟" description={`سيُحذف ${deleteTarget?.name ?? "المنتج"} من بيانات هذه التجربة فقط.`} confirmLabel="حذف المنتج" onCancel={() => setDeleteTarget(null)} onConfirm={() => { if (deleteTarget) persist(products.filter((item) => item.id !== deleteTarget.id), "تم حذف المنتج محليًا."); setDeleteTarget(null); }} />
  </div>;
}
