export const adminEventLabels: Record<string, string> = {
  "auth.phone_otp": "إرسال رمز التحقق",
  "auth.phone_otp_copy": "نسخة رمز التحقق",
  "join.application_submitted": "طلب انضمام جديد",
  "join.application_rejected": "رفض طلب الانضمام",
  "join.application_needs_changes": "طلب تعديل بيانات الانضمام",
  "onboarding.temporary_password": "إرسال بيانات الدخول المؤقتة",
  "onboarding.temporary_password_copy": "نسخة بيانات الدخول",
  "provider.rfq_new": "طلب تسعير جديد للمزود",
  "provider.rfq_reminder": "تذكير بطلب التسعير",
  "provider.rfq_expired": "انتهاء طلب التسعير",
  "provider.rfq_responded": "استلام رد المزود",
  "admin.rfq_no_providers": "طلب تسعير دون مزودين",
  "customer.quote_ready": "عرض العميل جاهز",
  "customer.quote_expiring": "اقتراب انتهاء العرض",
  "customer.quote_expired": "انتهاء صلاحية العرض",
  "admin.quote_assembly_failed": "تعذر تجهيز عرض العميل",
  "order_created": "إنشاء طلب شراء",
  "payment.pending": "بانتظار الدفع",
  "customer.payment_succeeded": "نجاح الدفع",
  "customer.payment_failed": "تعذر الدفع",
  "customer.payment_refunded": "استرداد المبلغ",
  "provider.fulfillment_assigned": "إسناد أمر توريد",
  "customer.delivery_assigned": "إسناد التوصيل",
  "customer.delivery_out_for_delivery": "خروج الشحنة للتوصيل",
  "customer.driver_arrived": "وصول السائق",
  "customer.delivery_code_issued": "إرسال رمز التسليم",
  "customer.delivery_code_reissued": "إعادة إرسال رمز التسليم",
  "delivery_confirmed": "تأكيد التسليم",
  "customer.delivery_failed": "تعذر التوصيل",
  "customer.order_cancelled": "إلغاء الطلب",
  "customer.order_completed": "اكتمال الطلب",
  "provider.product_approved": "اعتماد المنتج",
  "provider.product_rejected": "رفض المنتج",
  "provider.product_needs_changes": "طلب تعديل المنتج",
  "provider.price_expiring": "اقتراب انتهاء السعر",
  "provider.price_expired": "انتهاء صلاحية السعر",
  "provider.settlement_updated": "تحديث تصفية المزود",
  "provider.support_reply": "رد الدعم على المزود",
  "contractor.opportunity_new": "فرصة مشروع جديدة",
  "contractor.opportunity_deadline": "تذكير بموعد الفرصة",
  "contractor.proposal_submitted": "تقديم عرض مقاول",
  "contractor.proposal_needs_changes": "طلب تعديل عرض المقاول",
  "contractor.proposal_accepted": "قبول عرض المقاول",
  "contractor.proposal_rejected": "رفض عرض المقاول",
  "contractor.project_updated": "تحديث المشروع",
  "customer.milestone_approval_requested": "طلب اعتماد مرحلة",
  "contractor.milestone_approved": "اعتماد مرحلة المشروع",
  "contractor.milestone_rejected": "رفض مرحلة المشروع",
  "contractor.milestone_started": "بدء مرحلة المشروع",
  "contractor.document_expiring": "اقتراب انتهاء المستند",
  "contractor.document_expired": "انتهاء صلاحية المستند",
  "admin.project_no_contractors": "مشروع دون مقاولين مطابقين",
  "contractor.settlement_updated": "تحديث تصفية المقاول",
  "contractor.support_reply": "رد الدعم على المقاول",
  "customer.support_reply": "رد الدعم على العميل",
  "admin.outbox_dead_letter": "إشعار يحتاج تدخلًا",
  "admin.provisioning_failed": "تعذر إنشاء الحساب",
  "admin.credentials_delivery_failed": "تعذر إرسال بيانات الدخول",
  "admin.otp_delivery_failed": "تعذر إرسال رمز التحقق",
  "admin.payment_event_failed": "تعذر معالجة الدفع",
  "admin.delivery_attempts_exceeded": "تجاوز محاولات تأكيد التسليم",
  "admin.support_escalated": "تصعيد تذكرة دعم",
  "admin.settlement_review_required": "تصفية بانتظار المراجعة"
};
