export type AdminRow = Record<string, unknown>;
export type RecordField = { key: string; label: string; kind?: "money" | "date" | "status" | "text" | "percent" | "boolean"; empty?: string };
export type RecordPage = {
  title: string; description: string; table: string; select: string; columns: RecordField[];
  details?: RecordField[]; status?: string; order?: string; empty: string;
};
const f = (key: string, label: string, kind?: RecordField["kind"], empty?: string): RecordField => ({ key, label, kind, empty });
const created = f("created_at", "تاريخ الإنشاء", "date");
const updated = f("updated_at", "آخر تحديث", "date");
const state = f("status", "الحالة", "status");
const customer = f("customer.full_name", "العميل");
const contractor = f("contractor.display_name", "المقاول");
const total = f("total", "الإجمالي", "money");
const payments = f("payment_status", "الدفع", "status");
const priceDetails = [f("subtotal", "المجموع قبل الضريبة", "money"), f("vat_amount", "ضريبة القيمة المضافة", "money"), f("delivery_fee", "رسوم التوصيل", "money")];
const notes = [f("notes", "ملاحظات"), updated];
const profileJoin = "customer:profiles!customer_profile_id(full_name,email,mobile)";
const contractorJoin = "contractor:contractor_profiles!contractor_profile_id(display_name,commercial_name,phone,email)";
const requestJoin = "request:quote_requests!customer_request_id(request_code,city,requester:profiles!requester_id(full_name,mobile))";
const deliverySelect = "*,order:orders!order_id(order_code,customer:profiles!customer_profile_id(full_name,mobile)),provider:providers!provider_id(company_name),driver:provider_drivers!assigned_driver_id(full_name,mobile)";
const deliveryColumns = [f("order.order_code", "رقم الطلب"), f("order.customer.full_name", "العميل"), f("provider.company_name", "المزود"), f("driver.full_name", "السائق", "text", "لم يُعيّن سائق"), state, f("expected_at", "موعد التوصيل", "date")];

export const adminRecordPages: Record<string, RecordPage> = {
  "/admin/catalog": { title: "التصنيف", description: "معلومات التصنيف وترتيبه وحالة ظهوره في كتالوج مواد البناء.", table: "product_categories", select: "id,name,slug,is_active,sort_order,created_at", columns: [f("name", "اسم التصنيف"), f("is_active", "مفعّل", "boolean"), f("sort_order", "ترتيب الظهور")], details: [created], empty: "التصنيف غير متاح." },
  "/admin/drivers": { title: "السائقون", description: "حسابات السائقين والمنشآت التابعة لهم وجاهزيتهم لاستقبال مهام التوصيل.", table: "provider_drivers", select: "id,full_name,mobile,email,status,must_change_password,last_active_at,created_at,provider:providers!provider_id(company_name)", columns: [f("full_name", "السائق"), f("provider.company_name", "المنشأة"), f("mobile", "رقم الجوال"), state, f("last_active_at", "آخر نشاط", "date")], details: [f("email", "البريد الإلكتروني"), f("must_change_password", "يلزم تغيير كلمة المرور", "boolean"), created], status: "status", empty: "لم تضف المنشآت سائقين بعد. يظهر السائق هنا بعد إنشاء حسابه من بوابة المزود." },
  "/admin/admins": { title: "المدراء والصلاحيات", description: "تعرف على مسؤولي المنصة وأدوارهم وحالة وصولهم إلى لوحة الإدارة.", table: "admin_users", select: "id,is_active,last_active_at,created_at,profile:profiles!profile_id(full_name,email,mobile),role:admin_roles!role_id(name_ar,description)", columns: [f("profile.full_name", "المدير"), f("role.name_ar", "الدور الإداري"), f("profile.email", "البريد الإلكتروني"), f("is_active", "الحساب مفعّل", "boolean"), f("last_active_at", "آخر نشاط", "date")], details: [f("profile.mobile", "رقم الجوال"), f("role.description", "وصف الصلاحيات"), created], empty: "لا توجد حسابات إدارية متاحة للعرض وفق صلاحياتك." },
  "/admin/alerts": { title: "التنبيهات الحرجة", description: "راجع أولوية التنبيه وتفاصيله والجهة المسؤولة عن متابعته.", table: "admin_alerts", select: "id,title,description,priority,status,resolution_note,resolved_at,created_at,assigned:admin_users!assigned_admin_id(profile:profiles!profile_id(full_name))", columns: [f("title", "التنبيه"), f("priority", "الأولوية", "status"), state, f("assigned.profile.full_name", "مسؤول المتابعة", "text", "لم يُسند بعد"), created], details: [f("description", "تفاصيل التنبيه", "text"), f("resolution_note", "نتيجة المعالجة", "text"), f("resolved_at", "وقت المعالجة", "date")], status: "status", empty: "لا توجد تنبيهات مسجلة حاليًا. تظهر هنا الحالات التي تستدعي متابعة الإدارة." },
  "/admin/contractor-documents": { title: "مستندات المقاولين", description: "مستندات الاعتماد وأصحابها وصلاحيتها وملاحظات المراجعة.", table: "contractor_documents", select: "id,file_name,document_type,document_number,issued_at,expires_at,status,rejection_reason,created_at,contractor:contractor_profiles!contractor_profile_id(display_name),application:contractor_applications!application_id(contractor_name)", columns: [f("file_name", "المستند"), contractor, f("application.contractor_name", "صاحب طلب الانضمام"), state, f("expires_at", "تاريخ الانتهاء", "date")], details: [f("document_type", "نوع المستند", "status"), f("document_number", "رقم المستند"), f("issued_at", "تاريخ الإصدار", "date"), f("rejection_reason", "ملاحظة المراجعة", "text"), created], status: "status", empty: "لا توجد مستندات مسجلة للمقاولين بعد. راجع طلبات الانضمام لمتابعة المستندات الجديدة." },
  "/admin/reviews": { title: "التقييمات", description: "تجربة العملاء مع المقاولين بعد تنفيذ المشاريع، مع تفاصيل جودة العمل والالتزام.", table: "contractor_reviews", select: `id,rating,commitment,quality,communication,timeliness,comment,created_at,${contractorJoin},${profileJoin},project:contractor_projects!project_id(name)`, columns: [f("project.name", "المشروع"), contractor, customer, f("rating", "التقييم من 5"), created], details: [f("comment", "رأي العميل", "text"), f("quality", "جودة التنفيذ من 5"), f("commitment", "الالتزام من 5"), f("communication", "التواصل من 5"), f("timeliness", "الالتزام بالوقت من 5")], empty: "لم يسجل العملاء تقييمات بعد. تظهر التقييمات المرتبطة بالمشاريع المكتملة هنا." },
  "/admin/project-comments": { title: "مراجعة التعليقات", description: "ملاحظات المقاولين على المشاريع والتغييرات المقترحة قبل مشاركتها مع العميل.", table: "contractor_project_comments", select: `id,comment_code,project_request_id,type,body,current_budget,proposed_budget,current_duration,proposed_duration,reason,status,admin_reason,admin_note,created_at,${contractorJoin},project:project_requests!project_request_id(title)`, columns: [f("project.title", "المشروع"), contractor, f("type", "نوع الملاحظة", "status"), state, created], details: [f("body", "الملاحظة", "text"), f("reason", "مبرر التغيير", "text"), f("current_budget", "الميزانية الحالية", "money"), f("proposed_budget", "الميزانية المقترحة", "money"), f("current_duration", "المدة الحالية"), f("proposed_duration", "المدة المقترحة"), f("admin_reason", "سبب قرار الإدارة", "text"), f("admin_note", "ملاحظة الإدارة", "text")], status: "status", empty: "لا توجد ملاحظات مقدمة على المشاريع بعد." },
  "/admin/settlements/providers": { title: "تصفيات المزودين", description: "طلبات تحويل المستحقات وأسماء المنشآت وقيمة كل طلب ومرحلة معالجته.", table: "settlement_requests", select: "id,settlement_code,amount,status,notes,admin_notes,reviewed_at,transferred_at,created_at,provider:providers!provider_id(company_name)", columns: [f("settlement_code", "رقم التصفية"), f("provider.company_name", "المنشأة"), f("amount", "قيمة التصفية", "money"), state, created], details: [f("notes", "ملاحظات المزود", "text"), f("admin_notes", "ملاحظات الإدارة", "text"), f("reviewed_at", "تاريخ المراجعة", "date"), f("transferred_at", "تاريخ التحويل", "date")], status: "status", empty: "لا توجد طلبات تصفية من المزودين بعد." },
  "/admin/audit": { title: "سجل التدقيق", description: "تتبّع العمليات المسجلة ومن نفّذها وتوقيتها، مع الحفاظ على سرية محتوى السجلات.", table: "audit_logs", select: "id,action,entity_table,occurred_at,actor:profiles!actor_profile_id(full_name),provider:providers!provider_id(company_name),contractor:contractor_profiles!contractor_profile_id(display_name)", columns: [f("actor.full_name", "منفّذ العملية", "text", "عملية آلية أو حساب غير متاح"), f("action", "العملية", "status"), f("entity_table", "القسم", "status"), f("provider.company_name", "المنشأة"), contractor, f("occurred_at", "وقت التنفيذ", "date")], order: "occurred_at", empty: "لا توجد عمليات مسجلة في سجل التدقيق حتى الآن." },
  "/admin/pricing": { title: "الأسعار والتوفر", description: "أسعار المنتجات لدى المزودين وآخر مواعيد تأكيدها.", table: "provider_product_prices", select: "*,provider:providers!provider_id(company_name),product:products!product_id(name,sku)", columns: [f("product.name", "المنتج"), f("provider.company_name", "المزود"), f("unit_price", "سعر الوحدة", "money"), f("vat_inclusive", "شامل الضريبة", "boolean"), f("freshness_status", "صلاحية السعر", "status"), f("expires_at", "صالح حتى", "date")], details: [f("product.sku", "رمز المنتج"), f("last_confirmed_at", "آخر تأكيد", "date"), updated], status: "freshness_status", empty: "لا توجد أسعار مسجلة من المزودين حتى الآن." },
  "/admin/sourcing": { title: "محرك التوريد", description: "تابع تجهيز طلب العميل، ومقارنة الأسعار، ومرحلة إصدار العرض.", table: "internal_sourcing_requests", select: `*,${requestJoin}`, columns: [f("internal_code", "رقم عملية التوريد"), f("request.requester.full_name", "العميل"), f("request.request_code", "طلب المنتجات"), f("stage", "مرحلة التجهيز", "status"), f("response_deadline_at", "مهلة رد المزودين", "date"), f("expected_ready_at", "جاهزية العرض المتوقعة", "date")], details: [f("request.city", "المدينة"), created, f("completed_at", "اكتمال المعالجة", "date"), updated], status: "stage", empty: "تظهر عمليات التوريد بعد إرسال العميل طلب منتجات." },
  "/admin/bunya-quotes": { title: "عروض بُنية", description: "عروض الأسعار المقدمة للعملاء، وقيمتها وصلاحيتها وقرار العميل.", table: "bunya_customer_quotes", select: `*,${requestJoin}`, columns: [f("quote_code", "رقم العرض"), f("request.requester.full_name", "العميل"), total, state, f("valid_until", "صالح حتى", "date"), created], details: [f("request.request_code", "طلب المنتجات"), ...priceDetails, f("processing_stage", "مرحلة التجهيز", "status"), f("expected_delivery_at", "التوصيل المتوقع", "date"), f("customer_decided_at", "تاريخ قرار العميل", "date"), f("terms", "شروط العرض"), ...notes], status: "status", empty: "لا توجد عروض أسعار صادرة بعد. تبدأ العملية من محرك التوريد." },
  "/admin/quote-requests": { title: "طلبات المنتجات", description: "طلبات العملاء ومدينة الاستلام ومهلة تقديم الأسعار وحالة المعالجة.", table: "quote_requests", select: "*,customer:profiles!requester_id(full_name,email,mobile)", columns: [f("request_code", "رقم الطلب"), customer, f("city", "المدينة"), state, payments, f("quote_deadline", "مهلة الأسعار", "date"), created], details: [f("requester_role", "نوع الحساب", "status"), f("customer.mobile", "جوال العميل"), f("location_hint", "موقع الاستلام"), f("desired_receipt_at", "الاستلام المطلوب", "date"), ...notes], status: "status", empty: "لم تُرسل طلبات منتجات بعد. ستظهر هنا عند إرسالها من العملاء." },
  "/admin/orders": { title: "الطلبات", description: "طلبات الشراء المعتمدة ومتابعة الدفع والتجهيز والتسليم.", table: "orders", select: `*,${profileJoin}`, columns: [f("order_code", "رقم الطلب"), customer, total, payments, state, created], details: [f("customer.mobile", "جوال العميل"), ...priceDetails, f("discount_amount", "قيمة الخصم", "money"), f("desired_receipt_at", "الاستلام المطلوب", "date"), f("completed_at", "اكتمال الطلب", "date"), ...notes], status: "status", empty: "لا توجد طلبات شراء معتمدة حتى الآن." },
  "/admin/deliveries": { title: "التوصيل والسائقون", description: "كل شحنة مرتبطة بطلبها ومزودها والسائق المسؤول عنها.", table: "provider_delivery_assignments", select: deliverySelect, columns: deliveryColumns, details: [f("order.customer.mobile", "جوال العميل"), f("driver.mobile", "جوال السائق", "text", "لم يُعيّن سائق"), f("assigned_at", "تعيين السائق", "date"), f("pickup_at", "استلام الشحنة", "date"), f("delivered_at", "التسليم الفعلي", "date"), f("delivery_note", "ملاحظات التوصيل"), updated], status: "status", empty: "لا توجد شحنات مسندة بعد. تظهر هنا عند تجهيز الطلبات للتوصيل." },
  "/admin/delivery-monitoring": { title: "مراقبة التوصيل", description: "تابع حالة الشحنات ومواعيدها وآخر تحديث لكل عملية توصيل.", table: "provider_delivery_assignments", select: deliverySelect, columns: [...deliveryColumns, updated], details: [f("driver.mobile", "جوال السائق"), f("delivered_at", "التسليم الفعلي", "date"), f("delivery_note", "ملاحظات التوصيل")], status: "status", empty: "لا توجد شحنات للمتابعة حاليًا." },
  "/admin/delivery-codes": { title: "تأكيدات التسليم", description: "سجل عمليات التسليم المؤكدة وطريقة التأكيد والمستلم. رموز التحقق السرية لا تُعرض هنا.", table: "delivery_confirmation_records", select: "*,assignment:provider_delivery_assignments!assignment_id(order:orders!order_id(order_code),provider:providers!provider_id(company_name)),driver:provider_drivers!assigned_driver_id(full_name),actor:profiles!confirmed_by_user_id(full_name)", columns: [f("assignment.order.order_code", "رقم الطلب"), f("assignment.provider.company_name", "المزود"), f("method", "طريقة التأكيد", "status"), f("actor.full_name", "أكّد التسليم"), f("confirmed_at", "وقت التأكيد", "date")], details: [f("driver.full_name", "السائق"), f("delegate_name", "المستلم / المندوب"), f("delivery_reference", "مرجع التسليم"), f("note", "ملاحظات")], order: "confirmed_at", empty: "لم يُؤكّد تسليم أي شحنة بعد. يظهر السجل تلقائيًا بعد إتمام تأكيد الاستلام." },
  "/admin/project-requests": { title: "طلبات المشاريع", description: "مشاريع العملاء ونطاق العمل والميزانية والموعد المحدد للعروض.", table: "project_requests", select: `*,${profileJoin}`, columns: [f("title", "اسم المشروع"), customer, f("city", "المدينة"), f("estimated_budget_min", "الميزانية من", "money"), f("estimated_budget_max", "الميزانية إلى", "money"), f("proposal_deadline_at", "استقبال العروض حتى", "date")], details: [f("request_code", "رقم طلب المشروع"), f("project_type", "نوع المشروع"), f("is_open", "مفتوح للعروض", "boolean"), f("description", "وصف المشروع"), f("scope", "نطاق العمل"), f("expected_start_at", "البداية المتوقعة", "date"), f("estimated_duration", "المدة المتوقعة"), f("terms", "الشروط"), created], empty: "لا توجد طلبات مشاريع مقدمة من العملاء بعد." },
  "/admin/contractor-opportunities": { title: "فرص المشاريع", description: "الفرص الموجهة للمقاولين والمشروع المرتبط بكل فرصة ومرحلة استجابتها.", table: "contractor_opportunities", select: `*,${contractorJoin},project:project_requests!project_request_id(title,request_code,city,estimated_budget_min,estimated_budget_max,scope)`, columns: [f("project.title", "المشروع"), contractor, f("project.city", "المدينة"), state, f("expires_at", "تنتهي الفرصة", "date"), created], details: [f("project.request_code", "رقم طلب المشروع"), f("project.estimated_budget_min", "الميزانية من", "money"), f("project.estimated_budget_max", "الميزانية إلى", "money"), f("project.scope", "نطاق المشروع"), f("viewed_at", "اطّلع عليها المقاول", "date")], status: "status", empty: "لا توجد فرص موجهة للمقاولين حتى الآن." },
  "/admin/contractor-proposals": { title: "عروض المقاولين", description: "قارن اسم المقاول والمشروع وقيمة العرض وحالة مراجعته.", table: "contractor_proposals", select: `*,${contractorJoin},opportunity:contractor_opportunities!opportunity_id(project:project_requests!project_request_id(title,city))`, columns: [f("proposal_code", "رقم العرض"), contractor, f("opportunity.project.title", "المشروع"), f("amount", "قيمة العرض", "money"), state, created], details: [f("vat_inclusive", "شامل الضريبة", "boolean"), f("execution_duration", "مدة التنفيذ"), f("proposed_start_at", "البداية المقترحة", "date"), f("valid_until", "صلاحية العرض", "date"), f("scope_details", "نطاق التنفيذ"), f("includes", "يشمل العرض"), f("excludes", "لا يشمل العرض"), f("warranty", "الضمان"), f("rejection_reason", "سبب الرفض"), f("change_request", "التعديلات المطلوبة"), ...notes], status: "status", empty: "لم يقدم المقاولون عروضًا على المشاريع بعد." },
  "/admin/contractor-projects": { title: "مشاريع المقاولات", description: "المشاريع المعتمدة، والمقاول المسؤول، وقيمة التعاقد ونسبة الإنجاز.", table: "contractor_projects", select: `*,${contractorJoin},${profileJoin}`, columns: [f("name", "المشروع"), contractor, customer, f("project_value", "قيمة المشروع", "money"), f("progress", "الإنجاز", "percent"), state], details: [f("project_code", "رقم المشروع"), payments, f("start_at", "بداية المشروع", "date"), f("expected_end_at", "النهاية المتوقعة", "date"), f("scope", "نطاق العمل"), f("next_payment_label", "الدفعة القادمة"), ...notes], status: "status", empty: "لا توجد مشاريع متعاقد عليها بعد. تظهر المشاريع بعد قبول عروض المقاولين." },
  "/admin/invoices": { title: "الفواتير", description: "فواتير الطلبات باسم العميل مع تفاصيل المبالغ والضريبة وحالة السداد.", table: "invoices", select: `*,${profileJoin},order:orders!order_id(order_code)`, columns: [f("invoice_code", "رقم الفاتورة"), customer, f("order.order_code", "رقم الطلب"), total, state, f("issued_at", "تاريخ الإصدار", "date")], details: [...priceDetails, f("paid_at", "تاريخ السداد", "date"), updated], status: "status", empty: "لم تُصدر فواتير بعد. ترتبط كل فاتورة بطلب الشراء الخاص بها." },
  "/admin/settings": { title: "إعدادات المنصة", description: "الإعدادات التشغيلية المحفوظة وآخر تعديل عليها. السياسات والصلاحيات لها أقسام مستقلة.", table: "platform_settings", select: "setting_key,section,value_type,sensitivity,change_reason,updated_at", columns: [f("section", "القسم"), f("setting_key", "اسم الإعداد"), f("value_type", "نوع القيمة", "status"), f("sensitivity", "مستوى الوصول", "status"), f("change_reason", "سبب التعديل"), updated], order: "updated_at", empty: "لا توجد إعدادات تشغيلية مخصصة محفوظة حاليًا. يمكنك إدارة السياسات أو حسابات المدراء من الروابط أعلاه." },
};

export function recordValue(row: AdminRow, path: string): unknown {
  return path.split(".").reduce<unknown>((value, key) => value && typeof value === "object" && !Array.isArray(value) ? (value as AdminRow)[key] : undefined, row);
}

export const stateLabels: Record<string, string> = {
  closed: "مغلق", escalated: "تم التصعيد", assigned: "مسند للمزود", awaiting_reply: "بانتظار الرد", pending_review: "بانتظار المراجعة", approved: "معتمد", open: "مفتوح", in_progress: "قيد المتابعة", resolved: "تمت المعالجة", reopened: "أُعيد فتحه", blocked: "متعثر", low: "منخفضة", medium: "متوسطة", high: "عالية", suspended: "موقوف", must_change_password: "بانتظار تفعيل السائق", expiring_soon: "ينتهي قريبًا", not_uploaded: "لم يُرفق", transferring: "جارٍ التحويل", transferred: "تم التحويل",
  pending_admin_review: "بانتظار مراجعة الإدارة", approved_for_customer: "أُرسلت للعميل", rejected_by_admin: "رفضتها الإدارة", needs_contractor_revision: "مطلوب تعديل من المقاول", accepted_by_customer: "وافق العميل", rejected_by_customer: "رفض العميل", customer_requested_clarification: "طلب العميل توضيحًا", budget_change: "تعديل الميزانية", duration_change: "تعديل المدة", missing_drawings: "مخططات ناقصة", clarification: "طلب توضيح", general: "ملاحظة عامة",
  INSERT: "إضافة", UPDATE: "تعديل", DELETE: "حذف", insert: "إضافة", update: "تعديل", delete: "حذف", profiles: "المستخدمون", products: "المنتجات", providers: "المزودون", orders: "الطلبات", contractor_profiles: "المقاولون", contractor_projects: "المشاريع", invoices: "الفواتير", platform_policies: "السياسات", admin_users: "المدراء", settlement_requests: "تصفيات المزودين", contractor_settlement_requests: "تصفيات المقاولين", quote_requests: "طلبات المنتجات", platform_settings: "الإعدادات", commercial_registration: "السجل التجاري", tax_certificate: "الشهادة الضريبية", national_id: "الهوية الوطنية", license: "الرخصة",
  pending: "بانتظار المعالجة", unpaid: "غير مدفوع", paid: "مدفوع", partially_paid: "مدفوع جزئيًا", refunded: "مسترد", partially_refunded: "مسترد جزئيًا", failed: "فشل", processing: "قيد المعالجة",
  draft: "مسودة", submitted: "مُرسل", sourcing: "جارٍ التوريد", verifying: "جارٍ التحقق", quote_ready: "العرض جاهز", customer_review: "بانتظار العميل", accepted: "مقبول", rejected: "مرفوض", expired: "منتهي", cancelled: "ملغي",
  received: "تم استلام الطلب", comparing_prices: "مقارنة الأسعار", verifying_availability: "التحقق من التوفر", verifying_delivery: "التحقق من التوصيل", building_quote: "تجهيز العرض", sent_to_customer: "أُرسل للعميل",
  preparing: "قيد التجهيز", ready: "جاهز", confirmed: "مؤكد", ready_for_pickup: "جاهز للاستلام", assigned_driver: "تم تعيين السائق", out_for_delivery: "خرج للتوصيل", delivered: "تم التسليم", completed: "مكتمل",
  picked_up: "استلم السائق الشحنة", in_transit: "في الطريق", arrived: "وصل للموقع", failed_delivery: "تعذر التسليم",
  new: "جديدة", viewed: "تم الاطلاع", proposed: "تم تقديم عرض", under_review: "قيد المراجعة", needs_changes: "مطلوب تعديل", withdrawn: "مسحوب", awaiting_start: "بانتظار البدء", active: "قيد التنفيذ", paused: "متوقف مؤقتًا", delayed: "متأخر", awaiting_milestone_approval: "بانتظار اعتماد المرحلة",
  valid: "ساري", stale: "يحتاج تحديثًا", invalid: "غير صالح", customer: "العميل", contractor: "المقاول", provider: "المزود", driver: "السائق", admin: "الإدارة", code: "رمز التحقق", otp: "رمز التحقق", customer_code: "رمز العميل", delegate: "مندوب الاستلام", manual: "تأكيد يدوي",
  number: "رقم", string: "نص", boolean: "نعم / لا", json: "إعداد مركب", normal: "عادي", sensitive: "مقيد", critical: "عالي الحساسية",
};

export const unreadableText = "النص المحفوظ غير مقروء ويحتاج إلى تصحيح";
export function readableText(value: unknown, fallback = "غير مسجل"): string {
  if (value === null || value === undefined || value === "") return fallback;
  if (Array.isArray(value)) return value.map(item => readableText(item, "")).filter(Boolean).join("\n") || fallback;
  if (typeof value === "object") return "بيانات إضافية تحتاج إلى مراجعة";
  const text = String(value);
  if (/\?{3,}|\uFFFD/.test(text)) return unreadableText;
  if (/^[a-f0-9]{8}-[a-f0-9-]{27}$/i.test(text)) return "لم يتوفر الاسم المرتبط";
  return text;
}

export function formatRecordField(row: AdminRow, field: RecordField): string {
  const value = recordValue(row, field.key);
  if (value === null || value === undefined || value === "") return field.empty ?? "غير مسجل";
  if (field.key === "setting_key") return ({ "commerce.vat_rate": "نسبة ضريبة القيمة المضافة", "pricing.confirmation_hours": "مدة صلاحية تأكيد السعر", "quotes.customer_validity_hours": "مدة صلاحية عرض العميل", "delivery.max_code_attempts": "الحد الأقصى لمحاولات رمز التسليم", "delivery.lock_minutes": "مدة إيقاف محاولات رمز التسليم" } as Record<string,string>)[String(value)] ?? readableText(value);
  if (field.key === "section") return ({ commerce: "التجارة", pricing: "التسعير", quotes: "العروض", delivery: "التوصيل" } as Record<string,string>)[String(value)] ?? readableText(value);
  if (field.kind === "status") {
    if (value === "active" && "must_change_password" in row) return "نشط";
    if (field.key === "priority" && value === "critical") return "حرجة";
    return stateLabels[String(value)] ?? (field.key === "status" ? "حالة غير مصنفة" : "غير مصنف");
  }
  if (field.kind === "boolean") return value === true ? "نعم" : "لا";
  if (field.kind === "money" || field.kind === "percent") {
    const number = Number(value);
    if (!Number.isFinite(number)) return "غير مسجل";
    return field.kind === "money" ? `${number.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ر.س` : `${number.toLocaleString("en-US")}٪`;
  }
  if (field.kind === "date") {
    const date = new Date(String(value));
    if (Number.isNaN(date.getTime())) return "تاريخ غير صالح";
    return date.toLocaleString("ar-SA-u-ca-gregory-nu-latn", { dateStyle: "medium", ...(String(value).includes("T") ? { timeStyle: "short" as const } : {}), timeZone: "Asia/Riyadh" });
  }
  return readableText(value, field.empty);
}
